In [1]:
library(M4metalearning)
library(M4comp2018)
library(dplyr)
library(forecast)

载入程辑包：‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo

In [2]:
Weekly_M4 <- Filter(function(l) l$period == "Weekly", M4)
data=Weekly_M4

In [3]:
 data[[1]]$x

A Time Series:
   [1]  1089.20  1078.91  1079.88  1063.58  1060.61  1056.93  1056.63  1049.51
   [9]  1049.32  1049.89  1058.65  1062.35  1064.38  1061.96  1071.06  1073.73
  [17]  1066.97  1066.17  1064.43  1075.78  1070.45  1076.27  1072.98  1087.71
  [25]  1088.29  1095.81  1093.18  1097.80  1100.55  1089.55  1086.26  1086.63
  [33]  1098.57  1091.15  1091.59  1088.38  1093.82  1092.42  1093.99  1086.30
  [41]  1097.82  1104.85  1097.33  1100.56  1097.24  1117.60  1119.59  1121.28
  [49]  1119.58  1131.30  1135.79  1142.59  1138.05  1122.09  1119.01  1104.14
  [57]  1104.56  1097.51  1114.17  1105.50  1105.82  1101.62  1114.33  1118.28
  [65]  1118.86  1116.69  1126.44  1144.34  1133.41  1140.90  1127.98  1139.46
  [73]  1134.09  1138.07  1135.72  1148.23  1144.12  1150.09  1154.58  1153.86
  [81]  1164.40  1150.20  1156.06  1149.12  1162.70  1156.42  1152.20  1151.35
  [89]  1156.87  1158.77  1155.95  1159.13  1158.86  1176.97  1164.09  1169.36
  [97]  1168.44  1189.53  1189.41  1193.87  1187.82  1201.15  1209.10  1214.21
 [105]  1212.27  1200.88  1201.57  1190.88  1177.05  1173.78  1178.98  1183.40
 [113]  1176.37  1176.53  1185.60  1194.62  1194.19  1193.52  1198.95  1219.89
 [121]  1209.50  1211.40  1205.60  1215.07  1206.13  1211.71  1208.51  1214.98
 [129]  1222.91  1223.55  1239.74  1235.51  1252.08  1234.88  1243.08  1237.55
 [137]  1246.44  1242.71  1239.94  1240.17  1244.26  1248.39  1241.66  1253.08
 [145]  1246.01  1269.03  1259.10  1259.56  1262.08  1278.35  1285.59  1282.96
 [153]  1281.22  1289.03  1305.41  1310.57  1323.36  1308.07  1312.42  1290.91
 [161]  1282.05  1282.80  1287.41  1294.82  1281.74  1279.89  1284.32  1299.36
 [169]  1298.75  1303.12  1298.87  1323.80  1313.84  1320.48  1317.75  1326.68
 [177]  1321.63  1325.01  1323.13  1334.33  1343.47  1336.19  1360.98  1346.39
 [185]  1376.93  1351.23  1348.53  1342.95  1354.90  1357.57  1353.04  1358.32
 [193]  1357.41  1366.72  1362.46  1369.01  1368.22  1385.21  1378.58  1374.54
 [201]  1376.63  1385.96  1433.92  1433.65  1434.58  1430.48  1450.90  1454.58
 [209]  1476.08  1450.38  1454.57  1432.50  1421.60  1414.05  1412.12  1427.33
 [217]  1410.73  1419.89  1415.62  1432.87  1419.80  1431.18  1427.47  1456.53
 [225]  1450.54  1451.29  1439.78  1447.00  1445.32  1445.22  1449.25  1449.03
 [233]  1467.07  1459.79  1480.04  1469.61  1494.40  1483.64  1478.10  1475.30
 [241]  1485.24  1492.97  1487.99  1493.74  1488.81  1501.41  1495.13  1502.34
 [249]  1502.34  1522.96  1517.37  1524.19  1517.35  1530.45  1552.41  1548.78
 [257]  1549.89  1548.83  1568.12  1578.44  1589.07  1583.96  1565.02  1550.22
 [265]  1536.18  1532.63  1525.60  1558.57  1538.14  1538.92  1536.20  1560.80
 [273]  1554.16  1561.41  1572.10  1580.98  1592.40  1573.73  1572.15  1569.91
 [281]  1589.12  1580.76  1590.04  1581.09  1587.53  1591.00  1599.84  1600.64
 [289]  1612.60  1616.07  1571.77  1574.19  1571.17  1598.27  1585.00  1593.48
 [297]  1586.78  1594.88  1597.50  1597.13  1593.57  1604.73  1625.44  1612.24
 [305]  1618.84  1627.08  1618.46  1616.52  1621.51  1615.99  1634.22  1641.71
 [313]  1648.36  1642.74  1617.67  1611.63  1583.60  1581.79  1578.06  1602.37
 [321]  1592.55  1592.28  1580.45  1602.43  1603.37  1609.02  1602.77  1622.72
 [329]  1641.64  1628.83  1630.54  1623.11  1641.48  1633.49  1630.57  1628.52
 [337]  1638.64  1647.12  1647.84  1652.83  1660.76  1680.03  1652.56  1650.72
 [345]  1652.96  1675.73  1666.22  1655.60  1641.69  1649.33  1654.42  1639.52
 [353]  1634.68  1645.86  1669.74  1649.28  1648.14  1654.86  1680.04  1684.53
 [361]  1688.09  1684.19  1702.55  1718.81  1724.13  1727.13  1699.95  1709.07
 [369]  1674.52  1673.46  1662.22  1690.00  1675.73  1670.27  1644.38  1667.15
 [377]  1670.29  1663.46  1664.09  1681.40  1709.82  1691.36  1692.06  1691.35
 [385]  1708.85  1699.94  1710.50  1706.91  1722.57  1721.53  1717.97  1729.24
 [393]  1730.01  1753.74  1725.19  1726.91  1731.34  1752.91  1744.57  1737.15
 [401]  1731.27  1734.32  1743.73  1725.66  1732.89  1738.51  1770.24  1752.58
 [409]  1752.55  1756.78  1781.23  1784.75  1787.28  1783.39  1798.04  1819.58
 [417]  1825.38  1825.17  1796.43  1796.73  1768.03  1760.91  1755.55  1773.14
 [425]  1781.18  1776.27  1759.50  1767.89  1785.20  1777.61  1785.15  1792.96
 [433]  1817.73  1800.40  1807.62  1805.44  1817.04  1815.71  1821.97  1826.32
 [441]  1829.99  1840.45  1834.79  1853.10  1846.92  1871.99  1842.62  1846.77
 [449]  1848.29  1862.38  1860.31  1849.80  1851.04  1848.35  1861.08  1837.61
 [457]  1847.09  1854.98  1878.12  1873.27  1861.79  1870.41  1891.76  1904.36
 [465]  1904.27  1901.24  1905.21  1932.65  1934.77  1954.06  1933.92  1916.50
 [473]  1893.98  1881.89  1869.54  1869.54  1866.28  1866.28  1889.43  1889.43
 [481]  1887.93  1887.93  1914.96  1914.96  1928.03  1928.03  1923.56  1923.56
 [489]  1927.04  1927.04  1935.46  1935.46  1962.19  1962.19  1962.52  1962.52
 [497]  1987.75  1987.75  1964.92  1964.92  1973.21  1973.21  1958.92  1958.92
 [505]  1986.50  1986.50  1971.90  1971.90  1981.22  1981.22  1977.32  1977.32
 [513]  1986.97  1986.97  2005.04  2005.04  2022.02  2022.02  2038.61  2038.61
 [521]  2070.10  2070.10  2061.95  2061.95  1998.65  1998.65  1996.39  1996.39
 [529]  2005.66  2005.66  2030.36  2030.36  2019.10  2019.10  2045.24  2045.24
 [537]  2062.16  2062.16  2055.12  2055.12  2063.08  2063.08  2083.36  2083.36
 [545]  2107.56  2107.56  2104.76  2104.76  2139.23  2139.23  2110.19  2110.19
 [553]  2130.61  2130.61  2120.87  2120.87  2149.29  2149.29  2144.04  2144.04
 [561]  2148.68  2148.68  2164.36  2164.36  2165.12  2165.12  2193.54  2193.54
 [569]  2214.92  2214.92  2241.55  2241.55  2263.28  2263.28  2257.27  2257.27
 [577]  2180.94  2180.94  2164.02  2164.02  2184.79  2184.79  2208.71  2208.71
 [585]  2208.73  2208.73  2238.69  2238.69  2258.65  2258.65  2249.96  2249.96
 [593]  2259.93  2259.93  2280.25  2280.25  2308.44  2308.44  2300.26  2300.26
 [601]  2345.69  2345.69  2318.34  2318.34  2330.76  2330.76  2327.52  2327.52
 [609]  2354.56  2354.56  2349.96  2349.96  2348.02  2348.02  2377.16  2377.16
 [617]  2378.57  2378.57  2420.23  2420.23  2437.26  2437.26  2465.88  2465.88
 [625]  2517.12  2517.12  2512.01  2512.01  2438.36  2438.36  2418.60  2418.60
 [633]  2425.18  2425.18  2443.29  2443.29  2443.67  2443.67  2465.42  2465.42
 [641]  2511.94  2511.94  2497.89  2497.89  2502.26  2502.26  2515.00  2515.00
 [649]  2539.77  2539.77  2519.69  2519.69  2563.68  2563.68  2534.43  2534.43
 [657]  2547.75  2547.75  2540.00  2540.00  2556.06  2556.06  2569.30  2569.30
 [665]  2557.51  2557.51  2577.22  2577.22  2603.11  2603.11  2621.44  2621.44
 [673]  2632.91  2632.91  2663.12  2663.12  2677.32  2677.32  2700.34  2700.34
 [681]  2645.35  2645.35  2599.68  2599.68  2608.15  2608.15  2619.84  2619.84
 [689]  2630.89  2630.89  2654.92  2654.92  2698.76  2698.76  2682.23  2682.23
 [697]  2689.55  2689.55  2688.66  2688.66  2738.44  2738.44  2723.16  2723.16
 [705]  2773.28  2773.28  2746.44  2746.44  2751.58  2751.58  2744.69  2744.69
 [713]  2749.87  2749.87  2761.59  2761.59  2739.79  2739.79  2761.69  2761.69
 [721]  2752.00  2752.00  2798.66  2798.66  2790.18  2790.18  2826.60  2826.60
 [729]  2841.23  2841.23  2875.06  2875.06  2813.81  2813.81  2742.05  2742.05
 [737]  2749.71  2749.71  2773.91  2773.91  2791.19  2791.19  2795.14  2795.14
 [745]  2825.20  2825.20  2814.61  2814.61  2811.56  2811.56  2798.23  2798.23
 [753]  2844.75  2844.75  2823.08  2823.08  2875.80  2875.80  2847.47  2847.47
 [761]  2838.63  2838.63  2838.79  2838.79  2838.02  2838.02  2855.66  2855.66
 [769]  2820.35  2820.35  2852.42  2852.42  2838.36  2838.36  2872.48  2872.48
 [777]  2883.47  2883.47  2922.56  2922.56  2950.32  2950.32  2985.62  2985.62
 [785]  2931.31  2931.31  2853.78  2853.78  2876.13  2876.13  2902.73  2902.73
 [793]  2929.10  2929.10  2931.83  2931.83  2987.66  2987.66  2972.22  2972.22
 [801]  2979.25  2979.25  2963.12  2963.12  3018.94  3018.94  3009.63  3009.63
 [809]  3047.19  3047.19  3034.68  3034.68  3033.44  3033.44  3054.08  3054.08
 [817]  3063.43  3063.43  3097.71  3097.71  3065.90  3065.90  3099.70  3099.70
 [825]  3080.25  3080.25  3126.08  3126.08  3143.45  3143.45  3163.78  3163.78
 [833]  3142.85  3142.85  3153.73  3153.73  3086.47  3086.47  3047.63  3047.63
 [841]  3070.65  3070.65  3083.74  3083.74  3120.45  3120.45  3113.53  3113.53
 [849]  3155.26  3155.26  3131.26  3131.26  3143.69  3143.69  3138.82  3138.82
 [857]  3179.46  3179.46  3174.36  3174.36  3206.69  3206.69  3198.85  3198.85
 [865]  3192.18  3192.18  3198.96  3198.96  3208.52  3208.52  3239.65  3239.65
 [873]  3196.53  3196.53  3234.09  3234.09  3228.57  3228.57  3277.38  3277.38
 [881]  3279.10  3279.10  3337.05  3337.05  3352.21  3352.21  3390.02  3390.02
 [889]  3334.38  3334.38  3274.98  3274.98  3316.82  3316.82  3324.97  3324.97
 [897]  3367.36  3367.36  3353.21  3353.21  3331.12  3331.12  3328.98  3328.98
 [905]  3342.73  3342.73  3341.83  3341.83  3366.65  3366.65  3368.61  3368.61
 [913]  3383.74  3383.74  3412.58  3412.58  3409.48  3409.48  3435.06  3435.06
 [921]  3425.61  3425.61  3486.57  3486.57  3457.70  3457.70  3493.65  3493.65
 [929]  3494.49  3494.49  3535.56  3535.56  3570.15  3570.15  3580.77  3580.77
 [937]  3613.30  3613.30  3672.12  3672.12  3617.90  3617.90  3556.21  3556.21
 [945]  3594.07  3594.07  3607.62  3607.62  3624.84  3624.84  3633.83  3633.83
 [953]  3680.66  3680.66  3696.72  3696.72  3685.67  3685.67  3712.99  3712.99
 [961]  3750.43  3750.43  3754.87  3754.87  3775.76  3775.76  3810.85  3810.85
 [969]  3774.55  3774.55  3816.60  3816.60  3811.23  3811.23  3857.09  3857.09
 [977]  3837.53  3837.53  3875.73  3875.73  3886.88  3886.88  3887.37  3887.37
 [985]  3930.09  3930.09  3948.84  3948.84  3978.31  3978.31  4032.32  4032.32
 [993]  3992.45  3992.45  3938.16  3938.16  3969.83  3969.83  3997.12  3997.12
[1001]  4001.02  4001.02  4011.40  4011.40  4064.97  4064.97  4077.10  4077.10
[1009]  4053.50  4053.50  4069.73  4069.73  4105.43  4105.43  4110.65  4110.65
[1017]  4135.60  4135.60  4169.41  4169.41  4133.43  4133.43  4159.50  4159.50
[1025]  4149.87  4149.87  4183.50  4183.50  4152.23  4152.23  4179.83  4179.83
[1033]  4190.46  4190.46  4193.21  4193.21  4243.71  4243.71  4252.58  4252.58
[1041]  4267.45  4267.45  4331.93  4331.93  4290.49  4290.49  4210.33  4210.33
[1049]  4219.90  4219.90  4240.14  4240.14  4267.51  4267.51  4284.58  4284.58
[1057]  4313.10  4313.10  4355.11  4355.11  4333.34  4333.34  4338.88  4338.88
[1065]  4352.12  4352.12  4347.66  4347.66  4346.87  4346.87  4378.84  4378.84
[1073]  4341.29  4341.29  4364.85  4364.85  4346.43  4346.43  4378.73  4378.73
[1081]  4349.66  4349.66  4360.30  4360.30  4373.58  4373.58  4357.20  4357.20
[1089]  4391.44  4391.44  4423.77  4423.77  4431.93  4431.93  4510.98  4510.98
[1097]  4457.56  4457.56  4357.03  4357.03  4342.64  4342.64  4368.98  4368.98
[1105]  4394.35  4394.35  4406.32  4406.32  4431.49  4431.49  4446.05  4446.05
[1113]  4408.90  4408.90  4426.48  4426.48  4454.72  4454.72  4458.01  4458.01
[1121]  4476.48  4476.48  4519.88  4519.88  4481.43  4481.43  4506.93  4506.93
[1129]  4504.92  4504.92  4538.91  4538.91  4508.80  4508.80  4506.99  4506.99
[1137]  4535.98  4535.98  4525.90  4525.90  4567.08  4567.08  4600.86  4600.86
[1145]  4623.64  4623.64  4692.44  4692.44  4666.89  4666.89  4584.53  4584.53
[1153]  4582.06  4582.06  4611.41  4611.41  4615.77  4615.77  4619.33  4619.33
[1161]  4650.62  4650.62  4659.40  4659.40  4650.90  4650.90  4661.08  4661.08
[1169]  4697.04  4697.04  4687.69  4687.69  4710.75  4710.75  4754.24  4754.24
[1177]  4710.72  4710.72  4733.60  4733.60  4743.30  4743.30  4774.30  4774.30
[1185]  4741.50  4741.50  4751.41  4751.41  4781.66  4781.66  4791.37  4791.37
[1193]  4836.31  4836.31  4883.65  4883.65  4889.81  4889.81  4981.85  4981.85
[1201]  4967.74  4967.74  4868.31  4868.31  4859.45  4859.45  4898.59  4898.59
[1209]  4907.78  4907.78  4906.93  4906.93  4921.57  4921.57  4958.24  4958.24
[1217]  4930.96  4930.96  4942.00  4942.00  4977.08  4977.08  4976.52  4976.52
[1225]  4986.93  4986.93  5032.95  5032.95  5014.96  5014.96  5050.31  5050.31
[1233]  5036.10  5036.10  5079.88  5079.88  5082.97  5082.97  5099.54  5099.54
[1241]  5128.58  5128.58  5139.44  5139.44  5170.26  5170.26  5213.61  5213.61
[1249]  5231.11  5231.11  5301.09  5301.09  5316.95  5316.95  5254.80  5254.80
[1257]  5238.10  5238.10  5272.31  5272.31  5298.76  5298.76  5307.52  5307.52
[1265]  5331.58  5331.58  5349.08  5349.08  5371.46  5371.46  5395.48  5395.48
[1273]  5433.19  5433.19  5441.77  5441.77  5439.56  5439.56  5490.77  5490.77
[1281]  5482.33  5482.33  5503.33  5503.33  5506.81  5506.81  5548.34  5548.34
[1289]  5570.42  5570.42  5584.48  5584.48  5641.78  5641.78  5686.75  5686.75
[1297]  5789.45  5789.45  5901.14  5901.14  6009.14  6009.14  6236.31  6236.31
[1305]  6268.69  6268.69  5889.40  5889.40  5780.62  5780.62  5784.14  5784.14
[1313]  5770.87  5770.87  5768.94  5768.94  5774.51  5774.51  5786.19  5786.19
[1321]  5790.66  5790.66  5800.64  5800.64  5813.68  5813.68  5824.32  5824.32
[1329]  5808.46  5808.46  5864.58  5864.58  5826.90  5826.90  5831.47  5831.47
[1337]  5829.21  5829.21  5846.12  5846.12  5839.27  5839.27  5829.91  5829.91
[1345]  5859.45  5859.45  5852.01  5852.01  5878.16  5878.16  5928.56  5928.56
[1353]  5937.16  5937.16  6005.15  6005.15  6054.83  6054.83  5969.14  5969.14
[1361]  5924.35  5924.35  5965.03  5965.03  5980.50  5980.50  5988.98  5988.98
[1369]  6001.35  6001.35  6015.36  6015.36  6024.82  6024.82  6040.94  6040.94
[1377]  6080.44  6080.44  6086.20  6086.20  6083.99  6083.99  6144.20  6144.20
[1385]  6159.07  6159.07  6190.32  6190.32  6214.67  6214.67  6269.40  6269.40
[1393]  6674.12  6674.12  6307.48  6307.48  6344.26  6344.26  6368.26  6368.26
[1401]  6357.82  6357.82  6426.04  6426.04  6432.87  6432.87  6539.23  6539.23
[1409]  6599.30  6599.30  6521.79  6521.79  6495.87  6495.87  6552.71  6552.71
[1417]  6573.21  6573.21  6579.43  6579.43  6611.37  6611.37  6632.55  6632.55
[1425]  6640.81  6640.81  6655.56  6655.56  6714.25  6714.25  6724.81  6724.81
[1433]  6734.38  6734.38  6802.68  6802.68  6790.02  6790.02  6785.57  6785.57
[1441]  6784.93  6784.93  6823.92  6823.92  6804.64  6804.64  6796.55  6796.55
[1449]  6812.77  6812.77  6824.98  6824.98  6853.40  6853.40  6900.35  6900.35
[1457]  6949.76  6949.76  7000.58  7000.58  7050.24  7050.24  6981.87  6981.87
[1465]  6958.12  6958.12  7007.44  7007.44  7041.49  7041.49  7042.72  7042.72
[1473]  7068.99  7068.99  7086.00  7086.00  7108.83  7108.83  7108.10  7108.10
[1481]  7163.82  7163.82  7147.90  7147.90  7138.57  7138.57  7185.37  7185.37
[1489]  7174.02  7174.02  7169.46  7169.46  7208.99  7208.99  7231.22  7231.22
[1497]  7204.63  7204.63  7212.32  7212.32  7223.46  7223.46  7270.73  7270.73
[1505]  7271.71  7271.71  7320.24  7320.24  7361.79  7361.79  7389.53  7389.53
[1513]  7449.30  7449.30  7350.27  7350.27  7324.70  7324.70  7350.83  7350.83
[1521]  7365.71  7365.71  7366.21  7366.21  7369.84  7369.84  7396.67  7396.67
[1529]  7425.11  7425.11  7428.61  7428.61  7451.35  7451.35  7500.01  7500.01
[1537]  7485.15  7485.15  7559.58  7559.58  7579.30  7579.30  7573.70  7573.70
[1545]  7554.06  7554.06  7590.35  7590.35  7629.39  7629.39  7617.59  7617.59
[1553]  7621.92  7621.92  7645.84  7645.84  7668.74  7668.74  7711.09  7711.09
[1561]  7750.87  7750.87  7742.01  7742.01  7805.71  7805.71  7735.86  7735.86
[1569]  7749.02  7749.02  7707.25  7707.25  7750.62  7750.62  7725.12  7725.12
[1577]  7741.33  7741.33  7747.50  7747.50  7765.01  7765.01  7744.49  7744.49
[1585]  7756.10  7756.10  7815.95  7815.95  7789.43  7789.43  7827.67  7827.67
[1593]  7825.67  7825.67  7832.83  7832.83  7819.69  7819.69  7833.66  7833.66
[1601]  7876.82  7876.82  7882.55  7882.55  7875.96  7875.96  7867.21  7867.21
[1609]  7876.92  7876.92  7949.76  7949.76  7978.95  7978.95  7994.06  7994.06
[1617]  8119.91  8119.91  8040.49  8040.49  8019.00  8019.00  8025.95  8025.95
[1625]  8075.17  8075.17  8106.84  8106.84  8101.33  8101.33  8077.96  8077.96
[1633]  8097.82  8097.82  8113.09  8113.09  8118.88  8118.88  8156.97  8156.97
[1641]  8106.27  8106.27  8124.82  8124.82  8120.34  8120.34  8104.82  8104.82
[1649]  8090.22  8090.22  8100.97  8100.97  8125.07  8125.07  8086.58  8086.58
[1657]  8094.11  8094.11  8094.69  8094.69  8114.89  8114.89  8161.65  8161.65
[1665]  8231.69  8231.69  8219.30  8219.30  8347.86  8347.86  8247.98  8247.98
[1673]  8186.28  8186.28  8173.43  8173.43  8227.46  8227.46  8212.44  8212.44
[1681]  8203.04  8203.04  8222.22  8222.22  8230.00  8230.00  8245.83  8245.83
[1689]  8242.56  8242.56  8294.76  8294.76  8256.86  8256.86  8278.30  8278.30
[1697]  8297.89  8297.89  8283.62  8283.62  8341.29  8341.29  8253.99  8253.99
[1705]  8279.53  8279.53  8260.60  8260.60  8305.69  8305.69  8275.28  8275.28
[1713]  8298.75  8298.75  8353.95  8353.95  8360.90  8360.90  8320.75  8320.75
[1721]  8436.21  8436.21  8327.05  8327.05  8269.79  8269.79  8267.76  8267.76
[1729]  8318.00  8318.00  8315.00  8315.00  8346.66  8346.66  8319.29  8319.29
[1737]  8292.73  8292.73  8299.77  8299.77  8326.19  8326.19  8408.43  8408.43
[1745]  8376.37  8376.37  8429.14  8429.14  8472.82  8472.82  8473.10  8473.10
[1753]  8474.44  8474.44  8466.85  8466.85  8515.25  8515.25  9161.89  9161.89
[1761]  9914.51  9914.51 11511.15 11511.15 12423.95 12423.95 14837.87 14837.87
[1769] 14802.32 14802.32 16669.78 16669.78 17056.38 17056.38 17537.32 17537.32
[1777] 17097.54 17097.54 15278.82 15278.82 15924.42 15924.42 15422.28 15422.28
[1785] 16931.33 16931.33 17330.17 17330.17 17898.78 17898.78 17093.69 17093.69
[1793] 18053.73 18053.73 17724.36 17724.36 17227.16 17227.16 16212.14 16212.14
[1801] 16822.17 16822.17 16722.88 16722.88 16486.36 16486.36 17444.41 17444.41
[1809] 17656.35 17656.35 17955.81 17955.81 18580.17 18580.17 19278.28 19278.28
[1817] 20030.03 20030.03 19899.40 19899.40 20722.56 20722.56 20368.38 20368.38
[1825] 20142.12 20142.12 19536.07 19536.07 20131.08 20131.08 20658.54 20658.54
[1833] 21486.84 21486.84 21212.48 21212.48 20621.02 20621.02 20550.62 20550.62
[1841] 20190.74 20190.74 19756.69 19756.69 20193.97 20193.97 20193.65 20193.65
[1849] 20075.79 20075.79 19948.68 19948.68 20021.37 20021.37 19859.12 19859.12
[1857] 19968.56 19968.56 19944.04 19944.04 19860.85 19860.85 19552.95 19552.95
[1865] 19467.49 19467.49 19669.65 19669.65 19632.11 19632.11 19633.34 19633.34
[1873] 19859.90 19859.90 20319.54 20319.54 20042.94 20042.94 20167.70 20167.70
[1881] 20544.22 20544.22 21044.60 21044.60 22396.02 22396.02 23260.78 23260.78
[1889] 23979.24 23979.24 24686.99 24686.99 25169.91 25169.91 24847.16 24847.16
[1897] 25518.40 25518.40 26090.86 26090.86 26666.26 26666.26 26297.38 26297.38
[1905] 26982.59 26982.59 26758.77 26758.77 26723.01 26723.01 26489.63 26489.63
[1913] 26542.21 26542.21 26340.75 26340.75 26304.23 26304.23 26587.41 26587.41
[1921] 26163.33 26163.33 26334.76 26334.76 25758.06 25758.06 26394.06 26394.06
[1929] 25945.58 25945.58 26438.93 26438.93 26303.13 26303.13 26594.17 26594.17
[1937] 27152.07 27152.07 26928.60 26928.60 26489.97 26489.97 26375.82 26375.82
[1945] 26594.05 26594.05 26177.91 26177.91 26042.99 26042.99 26261.06 26261.06
[1953] 26495.40 26495.40 25889.39 25889.39 26244.95 26244.95 26560.01 26560.01
[1961] 26711.40 26711.40 26500.77 26500.77 26336.71 26336.71 26054.83 26054.83
[1969] 25638.34 25638.34 26123.88 26123.88 26214.36 26214.36 26431.77 26431.77
[1977] 26462.09 26462.09 26764.35 26764.35 26704.77 26704.77 26900.80 26900.80
[1985] 27418.03 27418.03 27997.58 27997.58 28409.88 28409.88 28868.33 28868.33
[1993] 29320.71 29320.71 29651.02 29651.02 30283.62 30283.62 30045.95 30045.95
[2001] 30692.17 30692.17 31587.07 31587.07 32146.86 32146.86 31775.50 31775.50
[2009] 32455.62 32455.62 32889.34 32889.34 33595.91 33595.91 33831.04 33831.04

In [4]:
length(data)

[1] 359

In [5]:
set.seed(100)
index = sample(3,length(data),replace = TRUE,prob=c(0.3,0.4,0.3))
trainindex=c(1:length(data))[index==1]
trainoptindex=c(1:length(data))[index==2]
testindex=c(1:length(data))[index==3]

In [6]:
M4_train <- data[trainindex]
M4_trainopt <- data[trainoptindex]
M4_test <- data[testindex]
#we create the temporal holdout version of the training and test sets
# M4_train <- temp_holdout(M4_train)
# M4_trainopt <- temp_holdout(M4_trainopt)
# M4_test <- temp_holdout(M4_test)

In [7]:
length(testindex)

[1] 114

In [8]:
datalength=length(data)
h=data[[1]]$h
m=5
n=4
freq=frequency(data[[1]]$x)

In [9]:
M4_test[[1]]

$st
[1] "W3"

$x
Time Series:
Start = 261
End = 2438
Frequency = 1
   [1]  258.7  259.8  260.2  260.8  261.1  263.1  264.5  266.3  267.2  269.2
  [11]  270.7  271.7  273.6  275.1  276.1  276.2  276.9  277.6  278.9  279.5
  [21]  280.8  281.9  283.8  285.0  286.3  287.6  288.8  289.3  289.6  289.8
  [31]  290.0  290.7  290.4  290.6  291.4  291.8  291.4  291.4  292.2  293.4
  [41]  294.4  294.7  294.7  294.5  295.6  296.2  297.2  297.7  299.4  300.0
  [51]  300.5  301.2  302.5  305.0  306.3  308.3  309.8  312.5  314.0  314.9
  [61]  315.4  316.5  317.8  318.3  319.0  320.5  321.6  321.1  322.6  323.8
  [71]  325.4  326.5  327.1  327.2  327.6  327.5  327.0  327.1  328.0  329.3
  [81]  329.7  330.5  331.0  332.2  333.0  333.9  335.2  336.8  337.9  338.5
  [91]  339.6  341.5  343.6  344.6  346.3  346.9  348.1  348.3  349.2  350.0
 [101]  351.8  353.4  354.1  354.0  356.7  359.5  360.6  362.2  362.7  364.1
 [111]  365.3  366.4  367.4  369.0  370.9  372.1  373.2  375.4  376.5  375.6
 [121]  375.8  376.2  377.9  378.5  378.9  379.3  380.1  380.5  380.3  380.0
 [131]  381.0  381.9  381.6  381.7  381.5  381.9  382.0  381.8  381.7  382.0
 [141]  382.4  381.7  382.1  383.2  384.3  383.7  383.4  382.2  382.1  382.3
 [151]  382.4  382.2  382.6  383.0  382.0  382.5  385.1  386.8  387.1  387.2
 [161]  387.2  387.9  388.9  389.7  390.0  390.7  391.7  392.2  392.4  394.0
 [171]  394.7  393.8  393.3  393.0  394.0  394.9  395.3  396.0  396.4  396.7
 [181]  396.1  396.5  397.8  397.2  396.4  396.2  396.3  396.4  397.2  396.7
 [191]  397.1  398.7  399.0  399.1  399.9  401.9  403.8  402.3  401.0  400.4
 [201]  399.9  400.1  398.1  399.2  399.4  398.1  397.2  398.0  401.4  402.0
 [211]  401.4  401.1  400.7  400.8  401.7  401.8  401.6  401.9  403.3  403.7
 [221]  404.6  406.3  408.2  407.5  407.4  407.5  408.8  409.6  410.4  411.3
 [231]  412.7  414.2  414.5  414.6  415.0  416.8  417.5  418.2  418.5  419.6
 [241]  420.2  421.2  421.6  421.7  423.1  422.6  422.9  423.9  425.9  425.8
 [251]  425.9  425.4  425.8  426.3  426.3  426.1  426.5  427.7  427.5  427.7
 [261]  427.8  430.4  431.8  432.4  434.8  475.3  476.0  478.0  480.1  482.3
 [271]  485.6  486.8  488.3  489.1  491.8  492.5  491.2  491.6  492.0  494.9
 [281]  497.4  499.3  500.9  504.1  505.4  507.1  508.6  511.4  513.1  514.2
 [291]  514.9  516.1  517.6  517.7  518.9  518.7  519.7  520.1  522.1  520.9
 [301]  523.0  525.2  525.1  525.5 1182.7 1182.9 1183.7 1183.8 1184.0 1186.0
 [311] 1184.9 1183.5 1186.0 1190.6 1193.1 1194.7 1195.1 1197.7 1202.0 1204.4
 [321] 1206.5 1211.2 1215.2 1218.9 1222.6 1227.7 1234.3 1235.6 1232.5 1231.7
 [331] 1233.8 1236.6 1236.9 1237.3 1239.1 1243.1 1243.8 1244.1 1245.5 1253.5
 [341] 1255.1 1257.9 1259.8 1262.4 1265.7 1268.7 1270.5 1272.5 1276.8 1277.9
 [351] 1278.6 1282.0 1291.5 1296.0 1296.7 1297.7 1300.4 1303.7 1306.0 1306.0
 [361] 1309.2 1312.7 1313.9 1313.2 1312.4 1317.6 1321.6 1325.1 1326.4 1328.3
 [371] 1331.4 1332.6 1333.3 1335.4 1340.5 1343.8 1346.8 1351.4 1358.7 1359.3
 [381] 1355.6 1354.4 1356.0 1359.6 1363.1 1365.9 1370.4 1374.1 1376.1 1376.3
 [391] 1377.9 1384.9 1383.1 1384.5 1386.3 1388.9 1393.1 1395.8 1397.5 1399.1
 [401] 1401.9 1402.4 1401.9 1402.6 1408.3 1408.1 1409.5 1410.7 1412.2 1414.5
 [411] 1415.5 1416.7 1416.8 1417.6 1412.9 1429.8 1438.5 1452.3 1468.5 1480.9
 [421] 1488.8 1496.0 1505.5 1510.9 1513.8 1516.5 1522.5 1525.4 1527.4 1529.7
 [431] 1535.5 1537.6 1534.4 1530.7 1532.9 1535.3 1537.4 1540.0 1542.4 1547.9
 [441] 1550.5 1547.0 1546.2 1554.2 1558.1 1559.4 1560.0 1560.4 1563.5 1564.8
 [451] 1564.7 1564.3 1567.3 1568.9 1569.0 1569.6 1576.1 1582.7 1584.8 1586.6
 [461] 1588.1 1593.5 1596.3 1596.5 1596.9 1599.5 1601.0 1599.6 1598.9 1606.2
 [471] 1613.1 1616.4 1616.9 1613.7 1625.6 1629.8 1632.0 1633.3 1638.7 1643.2
 [481] 1645.0 1647.3 1655.7 1659.9 1657.8 1654.4 1651.6 1654.8 1659.4 1662.2
 [491] 1664.2 1668.8 1673.0 1672.7 1671.4 1678.0 1682.8 1685.1 1685.6 1685.8
 [501] 1688.6 1689.1 1689.7 1690.5 1693.5 1698.1 1699.9 1699.7 1706.7 1713.5
 [511] 1717.0 1718.4 1720.3 1727.2 1734.0 1737.1 1740.0 1745.6 1751.2 1753.2
 [521] 1754.1 1759.6 1770.0 1779.4 1781.2 1781.4 1785.2 1790.3 1792.0 1792.9
 [531] 1797.4 1800.9 1801.1 1802.0 1807.2 1810.5 1807.5 1802.5 1797.9 1800.3
 [541] 1804.5 1807.5 1810.4 1816.4 1825.0 1828.2 1829.9 1835.4 1840.8 1844.3
 [551] 1843.5 1842.8 1845.3 1848.2 1847.9 1847.6 1848.1 1850.7 1851.3 1849.0
 [561] 1852.3 1860.0 1862.4 1861.4 1860.3 1863.1 1866.5 1866.8 1868.0 1869.2
 [571] 1872.7 1871.0 1868.6 1869.9 1881.2 1885.2 1885.7 1884.7 1884.7 1889.2
 [581] 1889.2 1889.6 1892.9 1899.0 1902.4 1904.4 1910.9 1919.4 1921.6 1917.0
 [591] 1914.4 1916.7 1922.5 1925.4 1929.5 1932.5 1940.0 1943.3 1943.3 1945.2
 [601] 1955.2 1959.0 1960.5 1960.7 1963.6 1968.2 1967.7 1967.4 1968.2 1974.0
 [611] 1976.5 1977.8 1979.9 1989.6 1994.4 1992.9 1991.7 1992.9 1995.2 1996.7
 [621] 1997.6 1998.0 2000.3 2000.9 1999.1 2001.1 2013.7 2020.3 2017.5 2015.1
 [631] 2012.3 2018.2 2019.1 2018.1 2019.2 2024.8 2025.9 2023.9 2025.1 2033.1
 [641] 2034.7 2026.1 2019.4 2017.9 2018.2 2018.9 2021.5 2025.0 2032.3 2031.8
 [651] 2027.2 2026.2 2037.0 2040.4 2039.6 2038.7 2039.9 2044.6 2044.0 2043.4
 [661] 2042.2 2048.3 2052.3 2048.7 2045.8 2053.4 2057.6 2056.8 2060.8 2059.8
 [671] 2063.8 2066.3 2067.7 2067.6 2073.2 2075.1 2072.8 2070.4 2077.6 2088.5
 [681] 2095.3 2096.6 2100.7 2108.8 2113.6 2116.9 2119.1 2127.7 2133.2 2136.9
 [691] 2139.2 2147.9 2155.3 2148.5 2142.2 2139.2 2143.0 2146.4 2150.3 2150.7
 [701] 2156.0 2158.3 2155.3 2156.0 2163.2 2169.0 2170.7 2168.3 2167.7 2169.9
 [711] 2170.8 2171.1 2168.3 2170.8 2173.3 2171.4 2168.7 2174.7 2182.1 2184.5
 [721] 2181.8 2182.1 2193.5 2196.8 2199.0 2198.2 2199.0 2201.1 2198.5 2195.2
 [731] 2200.9 2208.2 2211.6 2209.2 2204.1 2208.8 2211.9 2212.8 2213.4 2219.8
 [741] 2224.8 2225.7 2227.1 2235.4 2242.5 2238.7 2228.7 2223.3 2225.6 2229.6
 [751] 2233.8 2234.6 2242.7 2251.3 2251.7 2251.8 2261.2 2274.0 2277.9 2277.9
 [761] 2279.7 2289.8 2295.6 2297.8 2299.2 2304.1 2309.5 2311.4 2308.6 2315.5
 [771] 2324.8 2327.0 2329.3 2330.2 2341.1 2347.8 2347.8 2349.2 2354.3 2358.2
 [781] 2356.7 2353.3 2358.3 2369.0 2373.4 2372.4 2370.0 2378.0 2384.9 2386.1
 [791] 2387.5 2391.2 2398.4 2400.1 2400.9 2406.2 2414.1 2410.3 2398.6 2394.1
 [801] 2392.3 2394.5 2390.8 2391.0 2397.5 2403.2 2406.7 2400.3 2405.0 2413.0
 [811] 2417.8 2414.3 2414.1 2419.7 2427.5 2428.1 2429.7 2431.8 2436.3 2434.5
 [821] 2429.1 2431.8 2441.0 2441.7 2437.7 2435.0 2436.9 2442.4 2442.0 2442.7
 [831] 2443.2 2447.1 2445.5 2439.7 2440.1 2448.2 2460.6 2462.4 2460.6 2465.2
 [841] 2474.0 2473.8 2477.8 2484.1 2491.6 2496.2 2496.7 2498.2 2507.9 2507.1
 [851] 2494.2 2484.6 2486.6 2491.8 2491.1 2490.8 2492.3 2498.5 2497.7 2488.3
 [861] 2488.5 2495.9 2499.8 2493.7 2487.6 2486.7 2491.8 2488.8 2487.8 2484.0
 [871] 2487.9 2486.7 2478.6 2472.4 2480.9 2485.3 2480.6 2476.0 2475.6 2481.9
 [881] 2480.6 2478.5 2474.6 2479.8 2482.1 2465.1 2456.9 2457.0 2470.4 2470.1
 [891] 2467.2 2468.0 2476.2 2476.4 2473.5 2474.7 2479.4 2478.9 2472.5 2468.8
 [901] 2476.0 2480.9 2462.7 2449.6 2447.3 2449.1 2447.0 2440.2 2439.5 2445.9
 [911] 2445.4 2433.7 2424.9 2430.0 2439.2 2430.8 2425.9 2424.5 2428.6 2428.3
 [921] 2424.5 2421.8 2424.7 2425.9 2415.7 2408.6 2411.4 2424.4 2420.2 2412.9
 [931] 2413.5 2418.5 2415.4 2406.7 2403.3 2407.3 2405.9 2392.4 2381.3 2383.5
 [941] 2393.3 2387.2 2377.5 2370.9 2378.4 2380.0 2378.4 2376.1 2382.9 2383.8
 [951] 2377.4 2375.0 2377.9 2386.7 2371.0 2360.4 2361.0 2369.9 2369.4 2366.0
 [961] 2366.1 2376.7 2379.0 2363.8 2353.5 2355.4 2368.3 2361.0 2352.8 2352.0
 [971] 2358.9 2356.5 2350.3 2343.2 2347.3 2354.4 2341.8 2336.1 2338.4 2348.9
 [981] 2341.9 2333.6 2335.7 2345.8 2348.5 2345.2 2340.6 2347.9 2353.6 2339.9
 [991] 2330.6 2329.4 2342.6 2346.1 2335.7 2326.7 2335.2 2339.4 2332.9 2331.3
[1001] 2342.7 2350.8 2347.7 2339.6 2348.3 2362.7 2352.3 2341.2 2336.3 2343.7
[1011] 2343.3 2342.2 2336.3 2339.5 2341.6 2330.1 2328.0 2332.0 2343.4 2342.3
[1021] 2336.4 2334.6 2340.6 2339.6 2336.6 2328.2 2329.2 2335.9 2329.7 2322.2
[1031] 2321.3 2332.7 2331.9 2325.7 2323.9 2331.1 2334.9 2334.5 2332.9 2335.4
[1041] 2339.0 2331.6 2324.5 2322.1 2331.6 2338.5 2334.7 2329.0 2333.5 2338.8
[1051] 2335.8 2336.9 2340.1 2351.1 2350.5 2351.3 2353.8 2367.7 2364.8 2354.2
[1061] 2348.3 2361.0 2364.9 2372.2 2377.8 2392.5 2406.8 2403.0 2398.2 2403.6
[1071] 2418.5 2423.3 2424.1 2422.7 2438.6 2443.4 2443.9 2443.5 2448.1 2455.5
[1081] 2454.6 2449.1 2453.7 2471.9 2469.4 2463.2 2461.2 2473.6 2483.1 2481.8
[1091] 2483.2 2490.7 2502.2 2501.3 2493.4 2492.6 2513.6 2531.7 2520.6 2512.4
[1101] 2522.4 2537.0 2541.5 2543.9 2556.8 2571.1 2575.3 2570.3 2575.2 2601.1
[1111] 2602.0 2580.6 2562.0 2573.0 2584.6 2579.4 2580.3 2588.6 2610.1 2609.4
[1121] 2595.6 2596.1 2622.6 2623.8 2621.0 2614.8 2632.1 2642.8 2643.0 2638.4
[1131] 2637.0 2659.0 2656.7 2641.6 2633.5 2670.0 2679.5 2673.0 2667.5 2681.4
[1141] 2702.8 2699.0 2695.3 2700.3 2731.2 2728.3 2719.7 2708.4 2732.9 2750.5
[1151] 2744.6 2725.7 2730.2 2758.3 2759.3 2748.4 2761.6 2796.7 2794.8 2787.5
[1161] 2784.7 2832.8 2843.1 2821.9 2784.9 2790.4 2804.4 2799.5 2798.5 2798.5
[1171] 2837.9 2830.5 2812.1 2800.8 2847.7 2849.1 2836.9 2825.0 2846.7 2874.1
[1181] 2875.0 2865.0 2865.8 2902.5 2905.8 2883.0 2863.5 2900.7 2916.8 2911.5
[1191] 2895.5 2897.3 2933.9 2933.4 2924.4 2925.2 2960.0 2952.3 2939.4 2925.6
[1201] 2951.0 2985.0 2978.1 2954.4 2955.2 3000.4 3002.8 2998.9 3006.8 3050.9
[1211] 3049.9 3037.0 3029.2 3083.8 3103.6 3082.4 3040.0 3040.7 3063.4 3056.9
[1221] 3051.5 3057.7 3102.9 3098.3 3079.3 3058.8 3106.8 3119.3 3105.7 3089.9
[1231] 3097.6 3147.8 3144.2 3130.8 3124.7 3187.9 3190.3 3166.6 3134.8 3176.3
[1241] 3207.3 3204.6 3189.2 3193.8 3245.6 3244.9 3225.6 3213.3 3275.5 3278.2
[1251] 3260.9 3244.3 3256.6 3310.6 3308.7 3274.4 3271.1 3324.7 3324.8 3310.0
[1261] 3310.5 3358.0 3352.2 3337.3 3322.2 3373.8 3399.4 3389.5 3344.7 3313.4
[1271] 3362.2 3356.4 3343.1 3344.7 3400.9 3399.7 3376.3 3347.6 3394.0 3420.4
[1281] 3407.9 3390.2 3391.9 3442.6 3439.8 3422.3 3411.9 3464.5 3473.5 3451.6
[1291] 3416.8 3443.8 3474.8 3471.8 3444.9 3446.6 3489.2 3489.6 3473.4 3461.6
[1301] 3510.9 3513.8 3502.3 3477.1 3478.8 3545.7 3546.3 3521.2 3507.0 3567.5
[1311] 3564.5 3554.3 3546.3 3599.0 3616.7 3617.8 3597.4 3622.2 3696.3 3695.5
[1321] 3652.9 3604.0 3626.4 3622.2 3605.9 3596.2 3649.5 3664.6 3641.9 3603.1
[1331] 3612.2 3670.4 3665.4 3643.1 3634.4 3708.0 3703.2 3693.4 3670.5 3715.6
[1341] 3757.9 3748.0 3701.9 3710.9 3767.6 3767.9 3731.7 3704.9 3773.2 3787.2
[1351] 3769.9 3753.1 3796.8 3829.2 3829.2 3808.4 3812.4 3884.2 3892.4 3859.2
[1361] 3812.6 3876.3 3902.9 3897.6 3888.7 3949.9 3976.8 3967.1 3952.1 3976.0
[1371] 4066.1 4071.9 4020.1 3946.5 3995.7 3993.3 3971.2 3945.1 4008.4 4039.4
[1381] 4030.2 3975.1 3986.1 4057.9 4049.2 4010.0 3993.5 4073.0 4081.0 4059.9
[1391] 4030.5 4047.7 4134.6 4166.2 4107.9 4097.2 4164.9 4165.6 4125.8 4097.9
[1401] 4178.4 4204.6 4197.1 4171.4 4192.2 4260.0 4260.1 4211.6 4196.1 4267.7
[1411] 4269.4 4232.1 4189.0 4240.9 4282.2 4268.2 4249.7 4292.8 4323.2 4308.3
[1421] 4259.9 4283.7 4357.8 4364.4 4302.7 4226.8 4300.1 4315.6 4294.1 4257.1
[1431] 4273.9 4350.4 4350.8 4286.6 4289.6 4375.7 4375.0 4338.4 4317.8 4424.0
[1441] 4445.3 4421.1 4373.4 4373.9 4484.2 4479.5 4408.5 4374.1 4488.9 4492.3
[1451] 4466.6 4418.2 4496.7 4546.5 4551.8 4487.5 4498.8 4569.2 4569.9 4512.4
[1461] 4475.1 4570.4 4586.2 4551.7 4489.9 4497.4 4593.4 4596.4 4544.5 4564.4
[1471] 4639.4 4643.1 4581.6 4575.2 4697.9 4700.2 4644.7 4581.7 4660.5 4679.6
[1481] 4643.9 4600.2 4629.8 4713.2 4715.9 4656.3 4635.5 4774.4 4756.5 4704.2
[1491] 4665.2 4759.5 4811.9 4804.0 4717.0 4722.9 4819.9 4808.3 4720.3 4658.5
[1501] 4765.6 4778.7 4745.0 4672.2 4688.8 4787.9 4797.0 4719.3 4728.3 4788.9
[1511] 4773.6 4723.0 4669.5 4747.2 4780.8 4738.8 4672.8 4685.7 4767.6 4770.9
[1521] 4738.1 4750.3 4832.8 4830.8 4791.2 4753.6 4877.2 4921.9 4884.7 4796.5
[1531] 4805.9 4926.8 4925.2 4846.6 4855.2 4957.1 4949.7 4885.0 4808.2 4924.5
[1541] 4965.7 4917.8 4845.7 4873.4 4967.6 4957.6 4889.6 4848.3 4992.2 5017.3
[1551] 4962.2 4877.2 4947.8 5011.0 5006.6 4918.7 4940.8 5041.7 5051.9 4985.9
[1561] 4929.3 5056.6 5071.8 5026.2 4952.9 4958.6 5082.2 5070.3 4977.6 4918.3
[1571] 5054.4 5042.2 5002.3 4978.7 5092.8 5094.1 5047.7 4996.8 5096.0 5176.2
[1581] 5157.0 5035.8 5014.8 5108.6 5103.5 5029.1 4986.3 5141.5 5154.1 5105.4
[1591] 5016.5 5104.5 5186.0 5157.1 5073.5 5101.9 5210.6 5191.2 5127.9 5061.0
[1601] 5206.4 5261.7 5212.7 5110.5 5147.0 5265.1 5284.6 5179.0 5142.4 5292.5
[1611] 5302.3 5247.4 5175.8 5283.7 5330.6 5293.9 5220.6 5242.9 5370.7 5358.1
[1621] 5285.7 5192.7 5330.2 5354.4 5330.2 5292.2 5417.5 5419.4 5372.5 5305.4
[1631] 5357.1 5500.1 5507.3 5391.1 5342.9 5417.2 5416.8 5357.0 5304.1 5452.6
[1641] 5493.3 5464.0 5372.1 5406.4 5539.7 5526.1 5429.4 5394.2 5544.1 5537.2
[1651] 5488.5 5416.3 5512.7 5598.6 5573.0 5470.9 5496.5 5615.8 5637.5 5539.8
[1661] 5483.6 5646.1 5668.9 5628.6 5570.6 5642.1 5718.1 5698.2 5634.5 5647.5
[1671] 5769.9 5751.7 5690.5 5596.0 5705.0 5749.8 5731.0 5705.1 5775.8 5821.6
[1681] 5812.1 5761.4 5796.9 5932.1 5944.3 5857.3 5747.6 5866.5 5867.0 5821.7
[1691] 5758.0 5856.2 5926.6 5924.8 5823.8 5833.9 5946.0 5929.3 5856.6 5810.4
[1701] 5950.9 5973.4 5957.1 5909.8 5910.6 6038.1 6033.8 5932.7 5929.6 6029.5
[1711] 6026.9 5953.1 5907.8 6010.2 6058.2 6059.5 5999.6 6020.3 6121.6 6117.5
[1721] 6045.5 6024.3 6138.8 6135.7 6087.6 6037.9 6127.4 6206.0 6190.8 6172.0
[1731] 6201.8 6304.1 6328.9 6272.3 6244.6 6404.5 6414.6 6349.8 6194.8 6262.4
[1741] 6318.3 6298.8 6237.6 6256.5 6345.7 6346.2 6262.4 6208.7 6348.5 6350.9
[1751] 6299.3 6220.6 6289.3 6359.4 6338.1 6260.8 6243.3 6346.9 6363.7 6375.3
[1761] 6293.8 6421.6 6497.1 6502.3 6347.8 6351.3 6484.9 6509.0 6438.7 6478.8
[1771] 6593.7 6607.1 6567.3 6512.8 6616.6 6696.7 6708.5 6635.8 6625.9 6735.8
[1781] 6747.9 6701.7 6727.7 6855.9 6891.8 6799.7 6723.7 6768.7 6885.7 6831.2
[1791] 6686.6 6744.7 6828.2 6806.1 6723.6 6736.8 6843.5 6829.1 6705.3 6609.2
[1801] 6765.8 6782.5 6725.0 6644.2 6651.6 6773.0 6750.5 6658.2 6628.1 6773.6
[1811] 6804.2 6719.3 6617.1 6729.6 6794.0 6770.7 6656.3 6670.5 6824.1 6853.0
[1821] 6760.8 6719.4 6868.3 6865.6 6781.1 6688.7 6712.8 6842.6 6803.2 6705.9
[1831] 6689.5 6808.2 6823.2 6778.4 6767.2 6877.0 6870.9 6787.6 6735.5 6892.9
[1841] 6943.3 6880.3 6752.6 6747.5 6886.2 6910.5 6797.0 6794.3 6932.2 6921.2
[1851] 6831.7 6718.6 6833.4 6899.0 6847.9 6748.5 6771.3 6902.6 6897.5 6797.7
[1861] 6746.0 6916.5 6964.8 6884.9 6775.0 6871.7 6966.5 6968.7 6836.9 6843.6
[1871] 6897.1 7002.7 6917.4 6843.2 6997.7 7030.6 6965.2 6873.2 6891.0 7061.3
[1881] 7052.6 6905.7 6835.6 7022.3 7046.5 6977.2 6941.6 7118.3 7131.2 7059.9
[1891] 6975.9 7084.9 7190.1 7168.7 7026.0 6982.9 7121.0 7132.2 7024.1 6969.4
[1901] 7149.1 7177.0 7129.0 7075.0 7193.8 7298.5 7277.8 7168.3 7216.5 7397.3
[1911] 7407.6 7315.2 7221.8 7386.1 7476.4 7400.0 7259.7 7281.0 7466.3 7492.9
[1921] 7344.1 7278.4 7483.7 7531.9 7436.2 7333.5 7485.9 7579.7 7520.2 7398.1
[1931] 7420.4 7632.5 7627.4 7486.9 7376.1 7564.8 7625.8 7563.0 7494.7 7645.3
[1941] 7717.3 7650.1 7536.0 7568.2 7778.6 7779.5 7576.3 7464.6 7676.6 7685.0
[1951] 7605.7 7501.2 7633.2 7757.2 7718.4 7554.6 7592.2 7748.7 7759.3 7627.4
[1961] 7543.7 7750.1 7797.0 7726.3 7616.1 7632.5 7869.7 7886.5 7712.4 7718.5
[1971] 7876.6 7907.2 7784.0 7671.6 7881.8 7979.9 7930.0 7821.8 7850.4 8053.7
[1981] 8084.3 7959.3 7917.1 8137.8 8126.1 7981.2 7837.0 7929.6 8062.3 8019.4
[1991] 7928.3 8067.3 8191.1 8163.0 8007.8 8023.5 8242.3 8230.8 8031.7 7853.7
[2001] 8079.0 8135.8 8046.0 7922.1 7968.4 8203.7 8189.7 7996.2 8014.8 8212.2
[2011] 8209.7 8086.9 7971.0 8174.3 8272.5 8201.2 8070.7 8074.4 8318.4 8323.3
[2021] 8174.3 8111.0 8362.7 8378.4 8310.5 8161.6 8289.2 8420.3 8395.4 8258.6
[2031] 8259.2 8460.1 8449.1 8323.3 8225.1 8432.2 8506.2 8395.7 8245.9 8219.8
[2041] 8482.2 8497.0 8381.7 8368.8 8562.9 8574.1 8430.4 8348.9 8635.2 8642.6
[2051] 8477.7 8281.8 8449.9 8553.0 8490.6 8369.9 8395.2 8592.2 8582.1 8411.6
[2061] 8339.4 8613.7 8629.6 8522.7 8391.3 8525.6 8693.7 8671.1 8527.4 8480.9
[2071] 8719.7 8727.1 8572.5 8433.9 8692.0 8759.5 8689.2 8534.7 8519.7 8813.7
[2081] 8828.5 8671.7 8653.2 8849.9 8843.1 8716.1 8589.4 8762.2 8929.9 8852.3
[2091] 8670.8 8657.2 8885.4 8899.3 8807.8 8808.1 8999.5 9013.2 8856.2 8763.8
[2101] 9074.9 9120.9 8966.7 8717.0 8829.0 8997.4 8967.9 8815.4 8818.3 9040.7
[2111] 9027.6 8865.1 8731.9 9027.3 9078.1 8965.8 8808.5 8819.9 9122.0 9123.9
[2121] 8983.0 8905.9 9201.7 9245.2 9094.1 8901.8 9119.2 9247.6 9181.2 9020.9
[2131] 9028.7 9302.0 9327.0 9167.1 9084.9 9368.2 9374.7 9268.0 9115.7 9146.0
[2141] 9529.4 9466.1 9284.9 9256.1 9459.5 9471.2 9385.7 9281.7 9586.3 9612.3
[2151] 9480.1 9349.9 9509.5 9696.4 9634.9 9363.2 9320.8 9564.6 9562.9 9421.9
[2161] 9321.0 9611.8 9675.5 9535.9 9355.5 9501.3 9708.9 9671.1 9498.5 9506.7
[2171] 9756.7 9737.7 9606.2 9457.8 9730.3 9886.8 9796.8 9573.5

$n
[1] 2178

$type
[1] Other
Levels: Demographic Finance Industry Macro Micro Other

$h
[1] 13

$period
[1] Weekly
Levels: Daily Hourly Monthly Quarterly Weekly Yearly

$xx
Time Series:
Start = 2439
End = 2451
Frequency = 1
 [1]  9602.4  9895.9  9915.9  9726.6  9626.5  9966.1 10008.5  9911.7  9760.7
[10]  9968.2 10089.1 10005.9  9823.3

$pt_ff
          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]      [,7]     [,8]
 [1,] 9841.870 9929.782 9798.596 9630.768 9716.806 9987.374  9934.412 9744.142
 [2,] 9672.263 9871.002 9886.600 9700.110 9676.817 9839.982  9933.976 9817.569
 [3,] 9692.778 9794.692 9792.315 9742.141 9757.548 9766.803  9776.059 9785.314
 [4,] 9757.480 9808.607 9764.643 9676.845 9707.937 9835.352  9805.675 9756.373
 [5,] 9688.519 9780.150 9790.199 9709.281 9701.523 9776.747  9821.969 9772.891
 [6,] 9799.467 9887.906 9847.237 9704.667 9711.890 9913.615  9949.799 9810.124
 [7,] 9698.867 9775.873 9752.354 9684.552 9688.648 9779.017  9800.680 9759.115
 [8,] 9576.939 9580.356 9583.773 9587.191 9590.610 9594.029  9597.449 9600.870
 [9,] 9626.819 9662.092 9712.888 9654.633 9669.257 9757.046  9783.542 9696.548
[10,] 9712.961 9721.777 9730.600 9739.432 9748.271 9757.118  9765.974 9774.837
[11,] 9712.915 9721.700 9730.492 9739.293 9748.101 9756.918  9765.742 9774.574
[12,] 9674.064 9877.893 9857.235 9667.269 9655.059 9852.692  9928.370 9768.368
[13,] 9697.858 9701.784 9705.713 9709.644 9713.577 9717.513  9721.451 9725.390
[14,] 9745.631 9918.602 9851.842 9681.100 9735.688 9939.308  9925.879 9794.950
[15,] 9675.610 9871.316 9879.222 9706.089 9681.343 9866.212  9943.228 9849.611
[16,] 9758.313 9899.281 9843.672 9680.882 9689.969 9982.130 10009.242 9837.820
[17,] 9748.933 9758.723 9768.839 9778.145 9787.799 9797.669  9806.064 9815.371
[18,] 9691.885 9693.852 9695.819 9697.786 9699.752 9701.719  9703.686 9705.652
[19,] 9705.147 9710.901 9716.605 9722.260 9727.866 9733.423  9738.935 9744.400
[20,] 9672.263 9871.203 9887.685 9700.720 9677.376 9839.617  9934.759 9818.999
[21,] 9679.208 9879.533 9851.268 9657.688 9648.585 9853.779  9937.370 9782.324
[22,] 9711.191 9718.792 9726.242 9733.543 9740.698 9747.710  9754.582 9761.316
[23,] 9717.912 9727.579 9737.246 9746.913 9756.580 9766.246  9775.913 9785.580
[24,] 9712.268 9715.705 9719.242 9722.844 9726.501 9730.191  9733.907 9737.646
[25,] 9639.852 9936.486 9907.858 9705.821 9631.392 9852.794  9943.608 9803.618
          [,9]     [,10]     [,11]    [,12]    [,13]
 [1,] 9776.338  9995.254 10007.286 9818.312 9702.714
 [2,] 9727.415  9820.711  9948.944 9911.299 9805.750
 [3,] 9794.569  9803.825  9813.080 9822.335 9831.591
 [4,] 9737.728  9833.619  9832.798 9819.249 9731.963
 [5,] 9735.436  9779.056  9838.996 9825.401 9781.458
 [6,] 9768.226  9952.559  9974.400 9883.004 9787.063
 [7,] 9740.601  9809.958  9820.299 9817.760 9788.752
 [8,] 9604.291  9607.713  9611.135 9614.558 9617.982
 [9,] 9674.828  9763.687  9804.755 9726.843 9694.648
[10,] 9783.709  9792.589  9801.476 9810.372 9819.276
[11,] 9783.414  9792.263  9801.119 9809.983 9818.856
[12,] 9669.285  9816.033  9964.130 9871.908 9718.746
[13,] 9729.333  9733.277  9737.223 9741.172 9745.123

In [18]:
# length5=matrix(0,datalength,1)
# for(k in 1:datalength)
# {
# y = data[[k]]$x
# y_l=length(y)
# loc = 1:length(y)
# loc_m = as.integer(loc*m/length(y))
# filt_d = data.frame(y,loc_m)
# filt_0=filter(filt_d ,loc_m==0)
# m_l=count(filt_0)
# m_l=as.integer(m_l)
# length5[k,]=m_l*(frequent_matrix[k]-1)
#     }

In [ ]:
#this will take time
M4_train <- calc_forecasts(M4_train, forec_methods(), n.cores=3)
#once we have the forecasts, we can calculate the errors
M4_train <- calc_errors(M4_train)

In [ ]:
M4_train <- THA_features(M4_train)

In [ ]:
# M4train=load('Weekly_M4train.RData')
# M4_train <- eval(parse(text = M4train))

# M4test=load('Weekly_M4test_opt.RData')
# M4_test <- eval(parse(text = M4test))

In [ ]:
train_data <- create_feat_classif_problem(M4_train)
# set.seed(1345) #set the seed because xgboost is random!
meta_model <- train_selection_ensemble(train_data$data, train_data$errors)

In [23]:
meta_model

##### xgb.Booster
raw: 319.8 Kb
call:
  xgboost::xgb.train(params = param, data = dtrain, nrounds = 94)
params (as set within xgb.train):
  max_depth = "14", eta = "0.575188", nthread = "3", silent = "1", num_class = "9", subsample = "0.9161483", colsample_bytree = "0.7670739", silent = "1"
xgb.attributes:
  niter
callbacks:
  cb.print.evaluation(period = print_every_n)
niter: 94

In [39]:
pre_forecast_fforma=function(data,freq,h,m,n,meta_model)
{
    datapre=data
    model=ets(data[[1]]$x)
    fore_l=forecast(model,h=h)
    data_length=length(data)
    pred = array(0,dim = c(data_length,m,n,6))
    predh = array(0,dim = c(data_length,m,n,h))
    for(k in 1:data_length){
        start_time = Sys.time()
        y = data[[k]]$x
        y_pred = data[[k]]$xx
        y_l=length(y)
        loc = 1:length(y)
        loc_m = as.integer(loc*m/length(y))
        filt_d = data.frame(y,loc_m)
        filt_0=filter(filt_d ,loc_m==0)
        m_l=count(filt_0)
        n_l=m_l/n
        m_l=as.integer(m_l)
        n_l=as.numeric(n_l)
        for(i in 0:(m-1)){
            for(j in 0:(n-1)){
                Y = ts(y[round((i*m_l+j*n_l)+1):y_l], end = end(y), frequency=freq)
                datapre[[k]]$x=Y
                datapre[k] <- calc_forecasts(datapre[k], forec_methods(), n.cores=1)
                datapre[k] <- THA_features(datapre[k], n.cores=1)
                test_data <- create_feat_classif_problem(datapre[k])
                preds <- predict_selection_ensemble(meta_model, test_data$data)
                datapre[k] <- ensemble_forecast(preds, datapre[k])
                #print(datapre[[k]]$y_hat)
                fore_l$x=Y
                fore_l$mean=ts(datapre[[k]]$y_hat,start=start(datapre[[k]]$xx),frequency=freq)
                predh[k,(i+1),(j+1),] =datapre[[k]]$y_hat 
                pred[k,(i+1),(j+1),] = accuracy(fore_l,datapre[[k]]$xx)[2,1:6]
            }
        }
}
    return(list(pred, predh))
}

In [40]:
h=data[[1]]$h
freq=1
m=5
n=4

In [42]:
opttrain_list=pre_forecast_fforma(M4_trainopt,freq,h,m,n,meta_model)

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [46]:
save(opttrain_list,file='Weekly_FForma_datalist.RData')

In [50]:
opttest_list=pre_forecast_fforma(M4_test,freq,h,m,n,meta_model)

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in optimize(guer.cv, c(lower, upper), x = x, nonseasonal.length = nonseasonal.length):
“NA/Inf被换成最大的正值”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W297"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W297"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W297"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W297"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W297"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W297"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W299"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W299"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W299"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W299"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W299"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W299"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W300"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W300"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W300"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W300"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W300"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W300"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W302"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W302"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W302"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W302"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W302"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W302"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W304"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W304"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W304"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W304"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W304"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W304"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W305"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W305"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W305"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W305"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W305"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W305"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W307"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W307"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W307"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W307"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W307"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W307"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W308"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W308"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W308"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W308"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W308"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W308"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W309"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W309"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W309"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W309"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W309"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W309"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W313"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W313"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W313"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W313"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W313"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W313"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W314"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W314"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W314"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W314"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W314"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W314"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W315"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W315"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W315"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W315"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W315"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W315"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W316"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W316"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W316"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W316"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W316"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W316"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W317"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W317"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W317"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W317"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W317"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W317"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W319"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W319"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W319"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W319"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W319"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W319"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W321"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W321"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W321"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W321"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W321"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W321"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W322"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W322"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W322"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W322"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W322"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W322"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W323"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W323"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W323"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W323"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W323"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W323"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W325"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W325"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W325"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W325"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W325"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W325"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W328"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W328"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W328"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W328"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W328"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W328"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W329"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W329"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W329"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W329"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W329"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W329"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W333"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W333"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W333"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W333"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W333"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W333"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W334"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W334"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W334"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W334"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W334"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W334"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W337"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W337"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W337"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W337"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W337"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W337"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W340"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W340"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W340"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W340"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W340"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W340"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W342"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W342"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W342"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W342"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W342"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W342"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W343"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W343"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W343"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W343"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W343"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W343"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W345"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W345"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W345"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W345"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W345"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W345"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W347"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W347"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W347"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W347"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W347"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W347"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W349"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W349"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W349"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W349"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W349"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W349"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W353"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W353"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W353"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W353"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W353"
[1] "The forecast method that produced the error is: rw_drift_forec"
[1] "Returning snaive forecasts instead"
<simpleError in forecast.forecast(model, h = h): Please select a longer horizon when the forecasts are first computed>
[1] "ERROR processing series:  W353"
[1] "The forecast method that produced the error is: naive_forec"
[1] "Returning snaive forecasts instead"

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

In [51]:
save(opttest_list,file='Weekly_FForma_datatestlist.RData')

In [52]:
ll=pre_forecast_fforma(M4_test[1],freq,h,m,n,meta_model)

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”
Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

In [55]:
ll[[1]][,1,1,]

[1] 56.5384505 82.5370455 66.0038430  0.5787189  0.6787124  2.0188028

In [56]:
ll[[2]][,1,1,]

 [1] 9512.949 9672.341 9626.648 9452.851 9488.168 9649.577 9688.635 9554.163
 [9] 9507.676 9624.534 9716.969 9643.950 9558.838

In [59]:
M4_test[[1]]

$st
[1] "W3"

$x
Time Series:
Start = 1
End = 2165
Frequency = 1
   [1]  258.7  259.8  260.2  260.8  261.1  263.1  264.5  266.3  267.2  269.2
  [11]  270.7  271.7  273.6  275.1  276.1  276.2  276.9  277.6  278.9  279.5
  [21]  280.8  281.9  283.8  285.0  286.3  287.6  288.8  289.3  289.6  289.8
  [31]  290.0  290.7  290.4  290.6  291.4  291.8  291.4  291.4  292.2  293.4
  [41]  294.4  294.7  294.7  294.5  295.6  296.2  297.2  297.7  299.4  300.0
  [51]  300.5  301.2  302.5  305.0  306.3  308.3  309.8  312.5  314.0  314.9
  [61]  315.4  316.5  317.8  318.3  319.0  320.5  321.6  321.1  322.6  323.8
  [71]  325.4  326.5  327.1  327.2  327.6  327.5  327.0  327.1  328.0  329.3
  [81]  329.7  330.5  331.0  332.2  333.0  333.9  335.2  336.8  337.9  338.5
  [91]  339.6  341.5  343.6  344.6  346.3  346.9  348.1  348.3  349.2  350.0
 [101]  351.8  353.4  354.1  354.0  356.7  359.5  360.6  362.2  362.7  364.1
 [111]  365.3  366.4  367.4  369.0  370.9  372.1  373.2  375.4  376.5  375.6
 [121]  375.8  376.2  377.9  378.5  378.9  379.3  380.1  380.5  380.3  380.0
 [131]  381.0  381.9  381.6  381.7  381.5  381.9  382.0  381.8  381.7  382.0
 [141]  382.4  381.7  382.1  383.2  384.3  383.7  383.4  382.2  382.1  382.3
 [151]  382.4  382.2  382.6  383.0  382.0  382.5  385.1  386.8  387.1  387.2
 [161]  387.2  387.9  388.9  389.7  390.0  390.7  391.7  392.2  392.4  394.0
 [171]  394.7  393.8  393.3  393.0  394.0  394.9  395.3  396.0  396.4  396.7
 [181]  396.1  396.5  397.8  397.2  396.4  396.2  396.3  396.4  397.2  396.7
 [191]  397.1  398.7  399.0  399.1  399.9  401.9  403.8  402.3  401.0  400.4
 [201]  399.9  400.1  398.1  399.2  399.4  398.1  397.2  398.0  401.4  402.0
 [211]  401.4  401.1  400.7  400.8  401.7  401.8  401.6  401.9  403.3  403.7
 [221]  404.6  406.3  408.2  407.5  407.4  407.5  408.8  409.6  410.4  411.3
 [231]  412.7  414.2  414.5  414.6  415.0  416.8  417.5  418.2  418.5  419.6
 [241]  420.2  421.2  421.6  421.7  423.1  422.6  422.9  423.9  425.9  425.8
 [251]  425.9  425.4  425.8  426.3  426.3  426.1  426.5  427.7  427.5  427.7
 [261]  427.8  430.4  431.8  432.4  434.8  475.3  476.0  478.0  480.1  482.3
 [271]  485.6  486.8  488.3  489.1  491.8  492.5  491.2  491.6  492.0  494.9
 [281]  497.4  499.3  500.9  504.1  505.4  507.1  508.6  511.4  513.1  514.2
 [291]  514.9  516.1  517.6  517.7  518.9  518.7  519.7  520.1  522.1  520.9
 [301]  523.0  525.2  525.1  525.5 1182.7 1182.9 1183.7 1183.8 1184.0 1186.0
 [311] 1184.9 1183.5 1186.0 1190.6 1193.1 1194.7 1195.1 1197.7 1202.0 1204.4
 [321] 1206.5 1211.2 1215.2 1218.9 1222.6 1227.7 1234.3 1235.6 1232.5 1231.7
 [331] 1233.8 1236.6 1236.9 1237.3 1239.1 1243.1 1243.8 1244.1 1245.5 1253.5
 [341] 1255.1 1257.9 1259.8 1262.4 1265.7 1268.7 1270.5 1272.5 1276.8 1277.9
 [351] 1278.6 1282.0 1291.5 1296.0 1296.7 1297.7 1300.4 1303.7 1306.0 1306.0
 [361] 1309.2 1312.7 1313.9 1313.2 1312.4 1317.6 1321.6 1325.1 1326.4 1328.3
 [371] 1331.4 1332.6 1333.3 1335.4 1340.5 1343.8 1346.8 1351.4 1358.7 1359.3
 [381] 1355.6 1354.4 1356.0 1359.6 1363.1 1365.9 1370.4 1374.1 1376.1 1376.3
 [391] 1377.9 1384.9 1383.1 1384.5 1386.3 1388.9 1393.1 1395.8 1397.5 1399.1
 [401] 1401.9 1402.4 1401.9 1402.6 1408.3 1408.1 1409.5 1410.7 1412.2 1414.5
 [411] 1415.5 1416.7 1416.8 1417.6 1412.9 1429.8 1438.5 1452.3 1468.5 1480.9
 [421] 1488.8 1496.0 1505.5 1510.9 1513.8 1516.5 1522.5 1525.4 1527.4 1529.7
 [431] 1535.5 1537.6 1534.4 1530.7 1532.9 1535.3 1537.4 1540.0 1542.4 1547.9
 [441] 1550.5 1547.0 1546.2 1554.2 1558.1 1559.4 1560.0 1560.4 1563.5 1564.8
 [451] 1564.7 1564.3 1567.3 1568.9 1569.0 1569.6 1576.1 1582.7 1584.8 1586.6
 [461] 1588.1 1593.5 1596.3 1596.5 1596.9 1599.5 1601.0 1599.6 1598.9 1606.2
 [471] 1613.1 1616.4 1616.9 1613.7 1625.6 1629.8 1632.0 1633.3 1638.7 1643.2
 [481] 1645.0 1647.3 1655.7 1659.9 1657.8 1654.4 1651.6 1654.8 1659.4 1662.2
 [491] 1664.2 1668.8 1673.0 1672.7 1671.4 1678.0 1682.8 1685.1 1685.6 1685.8
 [501] 1688.6 1689.1 1689.7 1690.5 1693.5 1698.1 1699.9 1699.7 1706.7 1713.5
 [511] 1717.0 1718.4 1720.3 1727.2 1734.0 1737.1 1740.0 1745.6 1751.2 1753.2
 [521] 1754.1 1759.6 1770.0 1779.4 1781.2 1781.4 1785.2 1790.3 1792.0 1792.9
 [531] 1797.4 1800.9 1801.1 1802.0 1807.2 1810.5 1807.5 1802.5 1797.9 1800.3
 [541] 1804.5 1807.5 1810.4 1816.4 1825.0 1828.2 1829.9 1835.4 1840.8 1844.3
 [551] 1843.5 1842.8 1845.3 1848.2 1847.9 1847.6 1848.1 1850.7 1851.3 1849.0
 [561] 1852.3 1860.0 1862.4 1861.4 1860.3 1863.1 1866.5 1866.8 1868.0 1869.2
 [571] 1872.7 1871.0 1868.6 1869.9 1881.2 1885.2 1885.7 1884.7 1884.7 1889.2
 [581] 1889.2 1889.6 1892.9 1899.0 1902.4 1904.4 1910.9 1919.4 1921.6 1917.0
 [591] 1914.4 1916.7 1922.5 1925.4 1929.5 1932.5 1940.0 1943.3 1943.3 1945.2
 [601] 1955.2 1959.0 1960.5 1960.7 1963.6 1968.2 1967.7 1967.4 1968.2 1974.0
 [611] 1976.5 1977.8 1979.9 1989.6 1994.4 1992.9 1991.7 1992.9 1995.2 1996.7
 [621] 1997.6 1998.0 2000.3 2000.9 1999.1 2001.1 2013.7 2020.3 2017.5 2015.1
 [631] 2012.3 2018.2 2019.1 2018.1 2019.2 2024.8 2025.9 2023.9 2025.1 2033.1
 [641] 2034.7 2026.1 2019.4 2017.9 2018.2 2018.9 2021.5 2025.0 2032.3 2031.8
 [651] 2027.2 2026.2 2037.0 2040.4 2039.6 2038.7 2039.9 2044.6 2044.0 2043.4
 [661] 2042.2 2048.3 2052.3 2048.7 2045.8 2053.4 2057.6 2056.8 2060.8 2059.8
 [671] 2063.8 2066.3 2067.7 2067.6 2073.2 2075.1 2072.8 2070.4 2077.6 2088.5
 [681] 2095.3 2096.6 2100.7 2108.8 2113.6 2116.9 2119.1 2127.7 2133.2 2136.9
 [691] 2139.2 2147.9 2155.3 2148.5 2142.2 2139.2 2143.0 2146.4 2150.3 2150.7
 [701] 2156.0 2158.3 2155.3 2156.0 2163.2 2169.0 2170.7 2168.3 2167.7 2169.9
 [711] 2170.8 2171.1 2168.3 2170.8 2173.3 2171.4 2168.7 2174.7 2182.1 2184.5
 [721] 2181.8 2182.1 2193.5 2196.8 2199.0 2198.2 2199.0 2201.1 2198.5 2195.2
 [731] 2200.9 2208.2 2211.6 2209.2 2204.1 2208.8 2211.9 2212.8 2213.4 2219.8
 [741] 2224.8 2225.7 2227.1 2235.4 2242.5 2238.7 2228.7 2223.3 2225.6 2229.6
 [751] 2233.8 2234.6 2242.7 2251.3 2251.7 2251.8 2261.2 2274.0 2277.9 2277.9
 [761] 2279.7 2289.8 2295.6 2297.8 2299.2 2304.1 2309.5 2311.4 2308.6 2315.5
 [771] 2324.8 2327.0 2329.3 2330.2 2341.1 2347.8 2347.8 2349.2 2354.3 2358.2
 [781] 2356.7 2353.3 2358.3 2369.0 2373.4 2372.4 2370.0 2378.0 2384.9 2386.1
 [791] 2387.5 2391.2 2398.4 2400.1 2400.9 2406.2 2414.1 2410.3 2398.6 2394.1
 [801] 2392.3 2394.5 2390.8 2391.0 2397.5 2403.2 2406.7 2400.3 2405.0 2413.0
 [811] 2417.8 2414.3 2414.1 2419.7 2427.5 2428.1 2429.7 2431.8 2436.3 2434.5
 [821] 2429.1 2431.8 2441.0 2441.7 2437.7 2435.0 2436.9 2442.4 2442.0 2442.7
 [831] 2443.2 2447.1 2445.5 2439.7 2440.1 2448.2 2460.6 2462.4 2460.6 2465.2
 [841] 2474.0 2473.8 2477.8 2484.1 2491.6 2496.2 2496.7 2498.2 2507.9 2507.1
 [851] 2494.2 2484.6 2486.6 2491.8 2491.1 2490.8 2492.3 2498.5 2497.7 2488.3
 [861] 2488.5 2495.9 2499.8 2493.7 2487.6 2486.7 2491.8 2488.8 2487.8 2484.0
 [871] 2487.9 2486.7 2478.6 2472.4 2480.9 2485.3 2480.6 2476.0 2475.6 2481.9
 [881] 2480.6 2478.5 2474.6 2479.8 2482.1 2465.1 2456.9 2457.0 2470.4 2470.1
 [891] 2467.2 2468.0 2476.2 2476.4 2473.5 2474.7 2479.4 2478.9 2472.5 2468.8
 [901] 2476.0 2480.9 2462.7 2449.6 2447.3 2449.1 2447.0 2440.2 2439.5 2445.9
 [911] 2445.4 2433.7 2424.9 2430.0 2439.2 2430.8 2425.9 2424.5 2428.6 2428.3
 [921] 2424.5 2421.8 2424.7 2425.9 2415.7 2408.6 2411.4 2424.4 2420.2 2412.9
 [931] 2413.5 2418.5 2415.4 2406.7 2403.3 2407.3 2405.9 2392.4 2381.3 2383.5
 [941] 2393.3 2387.2 2377.5 2370.9 2378.4 2380.0 2378.4 2376.1 2382.9 2383.8
 [951] 2377.4 2375.0 2377.9 2386.7 2371.0 2360.4 2361.0 2369.9 2369.4 2366.0
 [961] 2366.1 2376.7 2379.0 2363.8 2353.5 2355.4 2368.3 2361.0 2352.8 2352.0
 [971] 2358.9 2356.5 2350.3 2343.2 2347.3 2354.4 2341.8 2336.1 2338.4 2348.9
 [981] 2341.9 2333.6 2335.7 2345.8 2348.5 2345.2 2340.6 2347.9 2353.6 2339.9
 [991] 2330.6 2329.4 2342.6 2346.1 2335.7 2326.7 2335.2 2339.4 2332.9 2331.3
[1001] 2342.7 2350.8 2347.7 2339.6 2348.3 2362.7 2352.3 2341.2 2336.3 2343.7
[1011] 2343.3 2342.2 2336.3 2339.5 2341.6 2330.1 2328.0 2332.0 2343.4 2342.3
[1021] 2336.4 2334.6 2340.6 2339.6 2336.6 2328.2 2329.2 2335.9 2329.7 2322.2
[1031] 2321.3 2332.7 2331.9 2325.7 2323.9 2331.1 2334.9 2334.5 2332.9 2335.4
[1041] 2339.0 2331.6 2324.5 2322.1 2331.6 2338.5 2334.7 2329.0 2333.5 2338.8
[1051] 2335.8 2336.9 2340.1 2351.1 2350.5 2351.3 2353.8 2367.7 2364.8 2354.2
[1061] 2348.3 2361.0 2364.9 2372.2 2377.8 2392.5 2406.8 2403.0 2398.2 2403.6
[1071] 2418.5 2423.3 2424.1 2422.7 2438.6 2443.4 2443.9 2443.5 2448.1 2455.5
[1081] 2454.6 2449.1 2453.7 2471.9 2469.4 2463.2 2461.2 2473.6 2483.1 2481.8
[1091] 2483.2 2490.7 2502.2 2501.3 2493.4 2492.6 2513.6 2531.7 2520.6 2512.4
[1101] 2522.4 2537.0 2541.5 2543.9 2556.8 2571.1 2575.3 2570.3 2575.2 2601.1
[1111] 2602.0 2580.6 2562.0 2573.0 2584.6 2579.4 2580.3 2588.6 2610.1 2609.4
[1121] 2595.6 2596.1 2622.6 2623.8 2621.0 2614.8 2632.1 2642.8 2643.0 2638.4
[1131] 2637.0 2659.0 2656.7 2641.6 2633.5 2670.0 2679.5 2673.0 2667.5 2681.4
[1141] 2702.8 2699.0 2695.3 2700.3 2731.2 2728.3 2719.7 2708.4 2732.9 2750.5
[1151] 2744.6 2725.7 2730.2 2758.3 2759.3 2748.4 2761.6 2796.7 2794.8 2787.5
[1161] 2784.7 2832.8 2843.1 2821.9 2784.9 2790.4 2804.4 2799.5 2798.5 2798.5
[1171] 2837.9 2830.5 2812.1 2800.8 2847.7 2849.1 2836.9 2825.0 2846.7 2874.1
[1181] 2875.0 2865.0 2865.8 2902.5 2905.8 2883.0 2863.5 2900.7 2916.8 2911.5
[1191] 2895.5 2897.3 2933.9 2933.4 2924.4 2925.2 2960.0 2952.3 2939.4 2925.6
[1201] 2951.0 2985.0 2978.1 2954.4 2955.2 3000.4 3002.8 2998.9 3006.8 3050.9
[1211] 3049.9 3037.0 3029.2 3083.8 3103.6 3082.4 3040.0 3040.7 3063.4 3056.9
[1221] 3051.5 3057.7 3102.9 3098.3 3079.3 3058.8 3106.8 3119.3 3105.7 3089.9
[1231] 3097.6 3147.8 3144.2 3130.8 3124.7 3187.9 3190.3 3166.6 3134.8 3176.3
[1241] 3207.3 3204.6 3189.2 3193.8 3245.6 3244.9 3225.6 3213.3 3275.5 3278.2
[1251] 3260.9 3244.3 3256.6 3310.6 3308.7 3274.4 3271.1 3324.7 3324.8 3310.0
[1261] 3310.5 3358.0 3352.2 3337.3 3322.2 3373.8 3399.4 3389.5 3344.7 3313.4
[1271] 3362.2 3356.4 3343.1 3344.7 3400.9 3399.7 3376.3 3347.6 3394.0 3420.4
[1281] 3407.9 3390.2 3391.9 3442.6 3439.8 3422.3 3411.9 3464.5 3473.5 3451.6
[1291] 3416.8 3443.8 3474.8 3471.8 3444.9 3446.6 3489.2 3489.6 3473.4 3461.6
[1301] 3510.9 3513.8 3502.3 3477.1 3478.8 3545.7 3546.3 3521.2 3507.0 3567.5
[1311] 3564.5 3554.3 3546.3 3599.0 3616.7 3617.8 3597.4 3622.2 3696.3 3695.5
[1321] 3652.9 3604.0 3626.4 3622.2 3605.9 3596.2 3649.5 3664.6 3641.9 3603.1
[1331] 3612.2 3670.4 3665.4 3643.1 3634.4 3708.0 3703.2 3693.4 3670.5 3715.6
[1341] 3757.9 3748.0 3701.9 3710.9 3767.6 3767.9 3731.7 3704.9 3773.2 3787.2
[1351] 3769.9 3753.1 3796.8 3829.2 3829.2 3808.4 3812.4 3884.2 3892.4 3859.2
[1361] 3812.6 3876.3 3902.9 3897.6 3888.7 3949.9 3976.8 3967.1 3952.1 3976.0
[1371] 4066.1 4071.9 4020.1 3946.5 3995.7 3993.3 3971.2 3945.1 4008.4 4039.4
[1381] 4030.2 3975.1 3986.1 4057.9 4049.2 4010.0 3993.5 4073.0 4081.0 4059.9
[1391] 4030.5 4047.7 4134.6 4166.2 4107.9 4097.2 4164.9 4165.6 4125.8 4097.9
[1401] 4178.4 4204.6 4197.1 4171.4 4192.2 4260.0 4260.1 4211.6 4196.1 4267.7
[1411] 4269.4 4232.1 4189.0 4240.9 4282.2 4268.2 4249.7 4292.8 4323.2 4308.3
[1421] 4259.9 4283.7 4357.8 4364.4 4302.7 4226.8 4300.1 4315.6 4294.1 4257.1
[1431] 4273.9 4350.4 4350.8 4286.6 4289.6 4375.7 4375.0 4338.4 4317.8 4424.0
[1441] 4445.3 4421.1 4373.4 4373.9 4484.2 4479.5 4408.5 4374.1 4488.9 4492.3
[1451] 4466.6 4418.2 4496.7 4546.5 4551.8 4487.5 4498.8 4569.2 4569.9 4512.4
[1461] 4475.1 4570.4 4586.2 4551.7 4489.9 4497.4 4593.4 4596.4 4544.5 4564.4
[1471] 4639.4 4643.1 4581.6 4575.2 4697.9 4700.2 4644.7 4581.7 4660.5 4679.6
[1481] 4643.9 4600.2 4629.8 4713.2 4715.9 4656.3 4635.5 4774.4 4756.5 4704.2
[1491] 4665.2 4759.5 4811.9 4804.0 4717.0 4722.9 4819.9 4808.3 4720.3 4658.5
[1501] 4765.6 4778.7 4745.0 4672.2 4688.8 4787.9 4797.0 4719.3 4728.3 4788.9
[1511] 4773.6 4723.0 4669.5 4747.2 4780.8 4738.8 4672.8 4685.7 4767.6 4770.9
[1521] 4738.1 4750.3 4832.8 4830.8 4791.2 4753.6 4877.2 4921.9 4884.7 4796.5
[1531] 4805.9 4926.8 4925.2 4846.6 4855.2 4957.1 4949.7 4885.0 4808.2 4924.5
[1541] 4965.7 4917.8 4845.7 4873.4 4967.6 4957.6 4889.6 4848.3 4992.2 5017.3
[1551] 4962.2 4877.2 4947.8 5011.0 5006.6 4918.7 4940.8 5041.7 5051.9 4985.9
[1561] 4929.3 5056.6 5071.8 5026.2 4952.9 4958.6 5082.2 5070.3 4977.6 4918.3
[1571] 5054.4 5042.2 5002.3 4978.7 5092.8 5094.1 5047.7 4996.8 5096.0 5176.2
[1581] 5157.0 5035.8 5014.8 5108.6 5103.5 5029.1 4986.3 5141.5 5154.1 5105.4
[1591] 5016.5 5104.5 5186.0 5157.1 5073.5 5101.9 5210.6 5191.2 5127.9 5061.0
[1601] 5206.4 5261.7 5212.7 5110.5 5147.0 5265.1 5284.6 5179.0 5142.4 5292.5
[1611] 5302.3 5247.4 5175.8 5283.7 5330.6 5293.9 5220.6 5242.9 5370.7 5358.1
[1621] 5285.7 5192.7 5330.2 5354.4 5330.2 5292.2 5417.5 5419.4 5372.5 5305.4
[1631] 5357.1 5500.1 5507.3 5391.1 5342.9 5417.2 5416.8 5357.0 5304.1 5452.6
[1641] 5493.3 5464.0 5372.1 5406.4 5539.7 5526.1 5429.4 5394.2 5544.1 5537.2
[1651] 5488.5 5416.3 5512.7 5598.6 5573.0 5470.9 5496.5 5615.8 5637.5 5539.8
[1661] 5483.6 5646.1 5668.9 5628.6 5570.6 5642.1 5718.1 5698.2 5634.5 5647.5
[1671] 5769.9 5751.7 5690.5 5596.0 5705.0 5749.8 5731.0 5705.1 5775.8 5821.6
[1681] 5812.1 5761.4 5796.9 5932.1 5944.3 5857.3 5747.6 5866.5 5867.0 5821.7
[1691] 5758.0 5856.2 5926.6 5924.8 5823.8 5833.9 5946.0 5929.3 5856.6 5810.4
[1701] 5950.9 5973.4 5957.1 5909.8 5910.6 6038.1 6033.8 5932.7 5929.6 6029.5
[1711] 6026.9 5953.1 5907.8 6010.2 6058.2 6059.5 5999.6 6020.3 6121.6 6117.5
[1721] 6045.5 6024.3 6138.8 6135.7 6087.6 6037.9 6127.4 6206.0 6190.8 6172.0
[1731] 6201.8 6304.1 6328.9 6272.3 6244.6 6404.5 6414.6 6349.8 6194.8 6262.4
[1741] 6318.3 6298.8 6237.6 6256.5 6345.7 6346.2 6262.4 6208.7 6348.5 6350.9
[1751] 6299.3 6220.6 6289.3 6359.4 6338.1 6260.8 6243.3 6346.9 6363.7 6375.3
[1761] 6293.8 6421.6 6497.1 6502.3 6347.8 6351.3 6484.9 6509.0 6438.7 6478.8
[1771] 6593.7 6607.1 6567.3 6512.8 6616.6 6696.7 6708.5 6635.8 6625.9 6735.8
[1781] 6747.9 6701.7 6727.7 6855.9 6891.8 6799.7 6723.7 6768.7 6885.7 6831.2
[1791] 6686.6 6744.7 6828.2 6806.1 6723.6 6736.8 6843.5 6829.1 6705.3 6609.2
[1801] 6765.8 6782.5 6725.0 6644.2 6651.6 6773.0 6750.5 6658.2 6628.1 6773.6
[1811] 6804.2 6719.3 6617.1 6729.6 6794.0 6770.7 6656.3 6670.5 6824.1 6853.0
[1821] 6760.8 6719.4 6868.3 6865.6 6781.1 6688.7 6712.8 6842.6 6803.2 6705.9
[1831] 6689.5 6808.2 6823.2 6778.4 6767.2 6877.0 6870.9 6787.6 6735.5 6892.9
[1841] 6943.3 6880.3 6752.6 6747.5 6886.2 6910.5 6797.0 6794.3 6932.2 6921.2
[1851] 6831.7 6718.6 6833.4 6899.0 6847.9 6748.5 6771.3 6902.6 6897.5 6797.7
[1861] 6746.0 6916.5 6964.8 6884.9 6775.0 6871.7 6966.5 6968.7 6836.9 6843.6
[1871] 6897.1 7002.7 6917.4 6843.2 6997.7 7030.6 6965.2 6873.2 6891.0 7061.3
[1881] 7052.6 6905.7 6835.6 7022.3 7046.5 6977.2 6941.6 7118.3 7131.2 7059.9
[1891] 6975.9 7084.9 7190.1 7168.7 7026.0 6982.9 7121.0 7132.2 7024.1 6969.4
[1901] 7149.1 7177.0 7129.0 7075.0 7193.8 7298.5 7277.8 7168.3 7216.5 7397.3
[1911] 7407.6 7315.2 7221.8 7386.1 7476.4 7400.0 7259.7 7281.0 7466.3 7492.9
[1921] 7344.1 7278.4 7483.7 7531.9 7436.2 7333.5 7485.9 7579.7 7520.2 7398.1
[1931] 7420.4 7632.5 7627.4 7486.9 7376.1 7564.8 7625.8 7563.0 7494.7 7645.3
[1941] 7717.3 7650.1 7536.0 7568.2 7778.6 7779.5 7576.3 7464.6 7676.6 7685.0
[1951] 7605.7 7501.2 7633.2 7757.2 7718.4 7554.6 7592.2 7748.7 7759.3 7627.4
[1961] 7543.7 7750.1 7797.0 7726.3 7616.1 7632.5 7869.7 7886.5 7712.4 7718.5
[1971] 7876.6 7907.2 7784.0 7671.6 7881.8 7979.9 7930.0 7821.8 7850.4 8053.7
[1981] 8084.3 7959.3 7917.1 8137.8 8126.1 7981.2 7837.0 7929.6 8062.3 8019.4
[1991] 7928.3 8067.3 8191.1 8163.0 8007.8 8023.5 8242.3 8230.8 8031.7 7853.7
[2001] 8079.0 8135.8 8046.0 7922.1 7968.4 8203.7 8189.7 7996.2 8014.8 8212.2
[2011] 8209.7 8086.9 7971.0 8174.3 8272.5 8201.2 8070.7 8074.4 8318.4 8323.3
[2021] 8174.3 8111.0 8362.7 8378.4 8310.5 8161.6 8289.2 8420.3 8395.4 8258.6
[2031] 8259.2 8460.1 8449.1 8323.3 8225.1 8432.2 8506.2 8395.7 8245.9 8219.8
[2041] 8482.2 8497.0 8381.7 8368.8 8562.9 8574.1 8430.4 8348.9 8635.2 8642.6
[2051] 8477.7 8281.8 8449.9 8553.0 8490.6 8369.9 8395.2 8592.2 8582.1 8411.6
[2061] 8339.4 8613.7 8629.6 8522.7 8391.3 8525.6 8693.7 8671.1 8527.4 8480.9
[2071] 8719.7 8727.1 8572.5 8433.9 8692.0 8759.5 8689.2 8534.7 8519.7 8813.7
[2081] 8828.5 8671.7 8653.2 8849.9 8843.1 8716.1 8589.4 8762.2 8929.9 8852.3
[2091] 8670.8 8657.2 8885.4 8899.3 8807.8 8808.1 8999.5 9013.2 8856.2 8763.8
[2101] 9074.9 9120.9 8966.7 8717.0 8829.0 8997.4 8967.9 8815.4 8818.3 9040.7
[2111] 9027.6 8865.1 8731.9 9027.3 9078.1 8965.8 8808.5 8819.9 9122.0 9123.9
[2121] 8983.0 8905.9 9201.7 9245.2 9094.1 8901.8 9119.2 9247.6 9181.2 9020.9
[2131] 9028.7 9302.0 9327.0 9167.1 9084.9 9368.2 9374.7 9268.0 9115.7 9146.0
[2141] 9529.4 9466.1 9284.9 9256.1 9459.5 9471.2 9385.7 9281.7 9586.3 9612.3
[2151] 9480.1 9349.9 9509.5 9696.4 9634.9 9363.2 9320.8 9564.6 9562.9 9421.9
[2161] 9321.0 9611.8 9675.5 9535.9 9355.5

$n
[1] 2165

$type
[1] Other
Levels: Demographic Finance Industry Macro Micro Other

$h
[1] 13

$period
[1] Weekly
Levels: Daily Hourly Monthly Quarterly Weekly Yearly

$xx
Time Series:
Start = 2426
End = 2438
Frequency = 1
 [1] 9501.3 9708.9 9671.1 9498.5 9506.7 9756.7 9737.7 9606.2 9457.8 9730.3
[11] 9886.8 9796.8 9573.5

$pt_ff
          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]      [,7]     [,8]
 [1,] 9841.870 9929.782 9798.596 9630.768 9716.806 9987.374  9934.412 9744.142
 [2,] 9672.263 9871.002 9886.600 9700.110 9676.817 9839.982  9933.976 9817.569
 [3,] 9692.778 9794.692 9792.315 9742.141 9757.548 9766.803  9776.059 9785.314
 [4,] 9757.480 9808.607 9764.643 9676.845 9707.937 9835.352  9805.675 9756.373
 [5,] 9688.519 9780.150 9790.199 9709.281 9701.523 9776.747  9821.969 9772.891
 [6,] 9799.467 9887.906 9847.237 9704.667 9711.890 9913.615  9949.799 9810.124
 [7,] 9698.867 9775.873 9752.354 9684.552 9688.648 9779.017  9800.680 9759.115
 [8,] 9576.939 9580.356 9583.773 9587.191 9590.610 9594.029  9597.449 9600.870
 [9,] 9626.819 9662.092 9712.888 9654.633 9669.257 9757.046  9783.542 9696.548
[10,] 9712.961 9721.777 9730.600 9739.432 9748.271 9757.118  9765.974 9774.837
[11,] 9712.915 9721.700 9730.492 9739.293 9748.101 9756.918  9765.742 9774.574
[12,] 9674.064 9877.893 9857.235 9667.269 9655.059 9852.692  9928.370 9768.368
[13,] 9697.858 9701.784 9705.713 9709.644 9713.577 9717.513  9721.451 9725.390
[14,] 9745.631 9918.602 9851.842 9681.100 9735.688 9939.308  9925.879 9794.950
[15,] 9675.610 9871.316 9879.222 9706.089 9681.343 9866.212  9943.228 9849.611
[16,] 9758.313 9899.281 9843.672 9680.882 9689.969 9982.130 10009.242 9837.820
[17,] 9748.933 9758.723 9768.839 9778.145 9787.799 9797.669  9806.064 9815.371
[18,] 9691.885 9693.852 9695.819 9697.786 9699.752 9701.719  9703.686 9705.652
[19,] 9705.147 9710.901 9716.605 9722.260 9727.866 9733.423  9738.935 9744.400
[20,] 9672.263 9871.203 9887.685 9700.720 9677.376 9839.617  9934.759 9818.999
[21,] 9679.208 9879.533 9851.268 9657.688 9648.585 9853.779  9937.370 9782.324
[22,] 9711.191 9718.792 9726.242 9733.543 9740.698 9747.710  9754.582 9761.316
[23,] 9717.912 9727.579 9737.246 9746.913 9756.580 9766.246  9775.913 9785.580
[24,] 9712.268 9715.705 9719.242 9722.844 9726.501 9730.191  9733.907 9737.646
[25,] 9639.852 9936.486 9907.858 9705.821 9631.392 9852.794  9943.608 9803.618
          [,9]     [,10]     [,11]    [,12]    [,13]
 [1,] 9776.338  9995.254 10007.286 9818.312 9702.714
 [2,] 9727.415  9820.711  9948.944 9911.299 9805.750
 [3,] 9794.569  9803.825  9813.080 9822.335 9831.591
 [4,] 9737.728  9833.619  9832.798 9819.249 9731.963
 [5,] 9735.436  9779.056  9838.996 9825.401 9781.458
 [6,] 9768.226  9952.559  9974.400 9883.004 9787.063
 [7,] 9740.601  9809.958  9820.299 9817.760 9788.752
 [8,] 9604.291  9607.713  9611.135 9614.558 9617.982
 [9,] 9674.828  9763.687  9804.755 9726.843 9694.648
[10,] 9783.709  9792.589  9801.476 9810.372 9819.276
[11,] 9783.414  9792.263  9801.119 9809.983 9818.856
[12,] 9669.285  9816.033  9964.130 9871.908 9718.746
[13,] 9729.333  9733.277  9737.223 9741.172 9745.123
[14,] 9746.118  9956.896 10039.423 9916.521 9800.581
[15,] 9756.360  9868.173  9971.031 9932.834 9829.764

In [57]:
accuracy(ll[[2]][,1,1,],M4_test[[1]]$xx)

         ME       RMSE     MAE      MPE       MAPE      ACF1      Theil's U
Test set 56.53845 82.53705 66.00384 0.5787189 0.6787124 0.1612234 0.5097746

In [34]:
M4_test <- calc_forecasts(M4_test, forec_methods(), n.cores=1)
M4_test <- THA_features(M4_test, n.cores=1)

Warning message in bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend, :
“optim() did not converge.”

In [35]:
test_data <- create_feat_classif_problem(M4_test)
preds <- predict_selection_ensemble(meta_model, test_data$data)
M4_test <- ensemble_forecast(preds, M4_test)

Warning message in if (class(newdata) != "xgb.DMatrix") newdata <- xgb.DMatrix(newdata, :
“条件的长度大于一，因此只能用其第一元素”

In [36]:
M4_test[[1]]$y_hat

 [1] 2938.958 2990.806 2966.705 2939.820 2944.849 2973.696 2974.069 2953.924
 [9] 2957.228 2971.226 2971.414 2953.753 2953.871

In [37]:
predres=function(data)
    {
    data_length=length(data)
    pred_res=matrix(0,data_length,6)
    model=nnetar(data[[1]]$x)
    h=data[[1]]$h
    fore_l=forecast(model,h=h)
    freq=frequency(data[[1]]$x)
    for (i in 1:data_length){
    fore_l$x=data[[i]]$x
    real=data[[i]]$xx
    fore_l$mean=ts(data[[i]]$y_hat,start=start(real),frequency=freq)
    res=accuracy(fore_l,real)
    pred_res[i,]=res[2,1:6]
    }
    return(pred_res)
    }

In [38]:
pred_res=predres(M4_test)

In [39]:
mean1=function(x)
    {
# 使用is.finite函数检查哪些值是有限的
finite_values <- x[is.finite(x)]
# 计算有限值的平均值
d=mean(finite_values, na.rm = TRUE)
return(d)
}

In [40]:
print(apply(pred_res,2,mean1))

[1]  30.593280 364.802501 306.569845  -1.575977   8.251161   2.601867

In [34]:
summary <- summary_performance(preds, dataset = M4_test)

[1] "Classification error:  0.6759"
[1] "Selected OWI :  0.8821"
[1] "Weighted OWI :  0.8283"
[1] "Naive Weighted OWI :  1.6037"
[1] "Oracle OWI:  0.657"
[1] "Single method OWI:  0.901"
[1] "Average OWI:  1.797"

In [46]:
save(M4_train, file = "Weekly_M4train_opt.RData")
save(M4_test, file = "Weekly_M4test_opt.RData")