In [1]:
library("xgboost")
library("Matrix")
library('Ckmeans.1d.dp')
library('lightgbm')

载入程辑包：‘lightgbm’


The following object is masked from ‘package:xgboost’:

    slice

## Read data and process data labels

In [2]:
time_matrix <- matrix(0,ncol = 3, nrow =4)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [3]:
data=read.csv('Weekly_features_matrix.csv')
data=data[,2:dim(data)[2]]

In [4]:
dim(data)

[1] 359  23

In [5]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9939369 6.320946e-11  36.725978
2 1         0        1               0.9946734 6.529056e-11  34.006351
3 1         0        1               0.9991252 8.840224e-13  44.955510
4 1         0        1               0.4159002 3.556671e-07   5.567640
5 1         0        1               0.2103179 9.307235e-06 -12.975059
6 1         0        1               0.4338204 1.481087e-06   6.188379
  curvature   e_acf1    e_acf10   entropy    ⋯ diff1_acf10 diff2_acf1
1  23.3448845 0.9600554 6.8563381 0.12476627 ⋯ 0.06449135  -0.45466261
2  19.8560557 0.9377499 5.8511863 0.09129043 ⋯ 0.16413331  -0.36322842
3  11.0485829 0.6469218 2.6893773 0.02284238 ⋯ 2.84368811  -0.07717025
4 -13.7061999 0.8181018 2.1703527 0.72989048 ⋯ 0.09272949  -0.55370413
5  -1.0188984 0.6064015 0.7164726 0.87229229 ⋯ 0.10934385  -0.57273878
6   0.3520556 0.5692734 0.6017905 0.78743719 ⋯ 0.11337659  -0.56140364
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.2879798   2179   0.13012409 0.13012409  0.13012409   0
2 0.3123634   1710   0.11726213 0.11726213  0.11726213   0
3 2.4288344   2178   0.11671782 0.11671782  0.11671782   0
4 0.3546872   2597   0.09217238 0.09217238  0.09217238   0
5 0.3857296   1603   0.07539105 0.07539105  0.07539105   0
6 0.3372221   1602   0.13123631 0.13123631  0.13123631   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [6]:
dlist= load('Weekly_FForma_datalist.RData')
datalist=eval(parse(text = dlist ))
res=datalist[[1]]
MASE=res[,,,6]
m=5

In [7]:
dim(MASE)

[1] 137   5   4

In [8]:
whichmin<-function(x){
    minx=min(x[x>0])
    loc=which(x==minx)[1]-1
    loc
}

meanunique=function(x)
    {
    mean(unique(x))
}

In [9]:
nanum=c()
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    a=apply(count,1,min)
    if(sum(is.na(a))>0)
        {
        nanum=append(nanum,i)
    }
    }

In [10]:
nanum

NULL

In [11]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [12]:
table(realbestmin)

realbestmin
 0  1  2  3  4
20 12 24 29 52

In [13]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [14]:
realbestmean

      [,1]
 [1,] 4
 [2,] 4
 [3,] 1
 [4,] 1
 [5,] 2
 [6,] 4
 [7,] 4
 [8,] 3
 [9,] 3
[10,] 0
[11,] 0
[12,] 0
[13,] 2
[14,] 4
[15,] 3
[16,] 1
[17,] 4
[18,] 4
[19,] 4
[20,] 2
[21,] 3
[22,] 1
[23,] 4
[24,] 2
[25,] 0
[26,] 0
[27,] 4
[28,] 2
[29,] 0
[30,] 3
[31,] ⋮
[32,] 0
[33,] 0
[34,] 4
[35,] 1
[36,] 4
[37,] 2
[38,] 0
[39,] 1
[40,] 1
[41,] 0
[42,] 4
[43,] 4
[44,] 4
[45,] 2
[46,] 0
[47,] 3
[48,] 2
[49,] 1
[50,] 4
[51,] 2
[52,] 1
[53,] 2
[54,] 2
[55,] 1
[56,] 2
[57,] 0
[58,] 4
[59,] 0
[60,] 3
[61,] 4

In [15]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9939369 6.320946e-11  36.725978
2 1         0        1               0.9946734 6.529056e-11  34.006351
3 1         0        1               0.9991252 8.840224e-13  44.955510
4 1         0        1               0.4159002 3.556671e-07   5.567640
5 1         0        1               0.2103179 9.307235e-06 -12.975059
6 1         0        1               0.4338204 1.481087e-06   6.188379
  curvature   e_acf1    e_acf10   entropy    ⋯ diff1_acf10 diff2_acf1
1  23.3448845 0.9600554 6.8563381 0.12476627 ⋯ 0.06449135  -0.45466261
2  19.8560557 0.9377499 5.8511863 0.09129043 ⋯ 0.16413331  -0.36322842
3  11.0485829 0.6469218 2.6893773 0.02284238 ⋯ 2.84368811  -0.07717025
4 -13.7061999 0.8181018 2.1703527 0.72989048 ⋯ 0.09272949  -0.55370413
5  -1.0188984 0.6064015 0.7164726 0.87229229 ⋯ 0.10934385  -0.57273878
6   0.3520556 0.5692734 0.6017905 0.78743719 ⋯ 0.11337659  -0.56140364
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.2879798   2179   0.13012409 0.13012409  0.13012409   0
2 0.3123634   1710   0.11726213 0.11726213  0.11726213   0
3 2.4288344   2178   0.11671782 0.11671782  0.11671782   0
4 0.3546872   2597   0.09217238 0.09217238  0.09217238   0
5 0.3857296   1603   0.07539105 0.07539105  0.07539105   0
6 0.3372221   1602   0.13123631 0.13123631  0.13123631   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [16]:
set.seed(100)
index = sample(3,dim(data)[1],replace = TRUE,prob=c(0.3,0.4,0.3))

In [17]:
train_data=data[index==2,]
test_data=data[index==3,]
train_label_min=realbestmin
train_label_mean=realbestmean

In [18]:
dim(data)

[1] 359  23

In [19]:
dim(train_data)

[1] 137  23

In [20]:
length(realbestmin)

[1] 137

In [21]:
realbestmean

      [,1]
 [1,] 4
 [2,] 4
 [3,] 1
 [4,] 1
 [5,] 2
 [6,] 4
 [7,] 4
 [8,] 3
 [9,] 3
[10,] 0
[11,] 0
[12,] 0
[13,] 2
[14,] 4
[15,] 3
[16,] 1
[17,] 4
[18,] 4
[19,] 4
[20,] 2
[21,] 3
[22,] 1
[23,] 4
[24,] 2
[25,] 0
[26,] 0
[27,] 4
[28,] 2
[29,] 0
[30,] 3
[31,] ⋮
[32,] 0
[33,] 0
[34,] 4
[35,] 1
[36,] 4
[37,] 2
[38,] 0
[39,] 1
[40,] 1
[41,] 0
[42,] 4
[43,] 4
[44,] 4
[45,] 2
[46,] 0
[47,] 3
[48,] 2
[49,] 1
[50,] 4
[51,] 2
[52,] 1
[53,] 2
[54,] 2
[55,] 1
[56,] 2
[57,] 0
[58,] 4
[59,] 0
[60,] 3
[61,] 4

In [22]:
head(train_data)

   frequency nperiods seasonal_period trend      spike        linearity
1  1         0        1               0.99393691 6.320946e-11 36.7259783
2  1         0        1               0.99467342 6.529056e-11 34.0063507
4  1         0        1               0.41590018 3.556671e-07  5.5676401
8  1         0        1               0.09782747 1.600440e-06 -0.8409878
10 1         0        1               0.95876248 1.637368e-08 23.3042393
13 1         0        1               0.97296035 1.611864e-08 25.3135326
   curvature  e_acf1    e_acf10  entropy    ⋯ diff1_acf10 diff2_acf1
1   23.344885 0.9600554 6.856338 0.12476627 ⋯ 0.06449135  -0.4546626
2   19.856056 0.9377499 5.851186 0.09129043 ⋯ 0.16413331  -0.3632284
4  -13.706200 0.8181018 2.170353 0.72989048 ⋯ 0.09272949  -0.5537041
8   -3.329146 0.7405379 2.127181 0.82683581 ⋯ 0.13902275  -0.6097405
10  -1.569799 0.8756885 3.238336 0.32979571 ⋯ 0.05755811  -0.4687462
13   5.425562 0.8144504 1.562147 0.14940563 ⋯ 0.17241185  -0.3284326
   diff2_acf10 length user_time  system_time elapsed_time user_time.1
1  0.2879798   2179   0.13012409 0.13012409  0.13012409   0
2  0.3123634   1710   0.11726213 0.11726213  0.11726213   0
4  0.3546872   2597   0.09217238 0.09217238  0.09217238   0
8  0.3962204   1623   0.10430646 0.10430646  0.10430646   0
10 0.3042919    934   0.03887081 0.03887081  0.03887081   0
13 0.3229872    721   0.04600835 0.04600835  0.04600835   0
   system_time.1 elapsed_time.1
1  0             0
2  0             0
4  0             0
8  0             0
10 0             0
13 0             0

In [23]:
end_time = Sys.time()

In [24]:
time_matrix[1,]=end_time-start_time

In [25]:
end_time-start_time

Time difference of 13.45654 secs

## Target the interval where the actual error is minimum

In [26]:
start_time = Sys.time()

In [27]:
dtrain_xg_min_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_min)) 
dtrain_xg_min_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)) )

In [28]:
dtrain_lg_min_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_min))
dtrain_lg_min_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)))

In [29]:
xgb_min_reg <- xgboost(data = dtrain_xg_min_reg, nround=500)

[1]	train-rmse:1.863476
[2]	train-rmse:1.393774
[3]	train-rmse:1.064971
[4]	train-rmse:0.820268
[5]	train-rmse:0.645372
[6]	train-rmse:0.523084
[7]	train-rmse:0.405903
[8]	train-rmse:0.327577
[9]	train-rmse:0.284502
[10]	train-rmse:0.248049
[11]	train-rmse:0.211356
[12]	train-rmse:0.187845
[13]	train-rmse:0.164951
[14]	train-rmse:0.142395
[15]	train-rmse:0.127618
[16]	train-rmse:0.116635
[17]	train-rmse:0.104215
[18]	train-rmse:0.089077
[19]	train-rmse:0.080898
[20]	train-rmse:0.067610
[21]	train-rmse:0.056197
[22]	train-rmse:0.048316
[23]	train-rmse:0.042923
[24]	train-rmse:0.036937
[25]	train-rmse:0.033136
[26]	train-rmse:0.028506
[27]	train-rmse:0.024385
[28]	train-rmse:0.021892
[29]	train-rmse:0.019957
[30]	train-rmse:0.017078
[31]	train-rmse:0.014950
[32]	train-rmse:0.012959
[33]	train-rmse:0.011637
[34]	train-rmse:0.009607
[35]	train-rmse:0.008084
[36]	train-rmse:0.007141
[37]	train-rmse:0.006659
[38]	train-rmse:0.005937
[39]	train-rmse:0.005100
[40]	train-rmse:0.004615
[41]	train-rmse:0.004102
[42]	train-rmse:0.003809
[43]	train-rmse:0.003615
[44]	train-rmse:0.003382
[45]	train-rmse:0.003170
[46]	train-rmse:0.002870
[47]	train-rmse:0.002643
[48]	train-rmse:0.002390
[49]	train-rmse:0.002221
[50]	train-rmse:0.001929
[51]	train-rmse:0.001855
[52]	train-rmse:0.001617
[53]	train-rmse:0.001435
[54]	train-rmse:0.001238
[55]	train-rmse:0.001089
[56]	train-rmse:0.000993
[57]	train-rmse:0.000932
[58]	train-rmse:0.000819
[59]	train-rmse:0.000819
[60]	train-rmse:0.000819
[61]	train-rmse:0.000819
[62]	train-rmse:0.000819
[63]	train-rmse:0.000819
[64]	train-rmse:0.000819
[65]	train-rmse:0.000819
[66]	train-rmse:0.000819
[67]	train-rmse:0.000819
[68]	train-rmse:0.000819
[69]	train-rmse:0.000819
[70]	train-rmse:0.000819
[71]	train-rmse:0.000819
[72]	train-rmse:0.000819
[73]	train-rmse:0.000819
[74]	train-rmse:0.000819
[75]	train-rmse:0.000819
[76]	train-rmse:0.000819
[77]	train-rmse:0.000819
[78]	train-rmse:0.000819
[79]	train-rmse:0.000819
[80]	train-rmse:0.000819
[81]	train-rmse:0.000819
[82]	train-rmse:0.000819
[83]	train-rmse:0.000819
[84]	train-rmse:0.000819
[85]	train-rmse:0.000819
[86]	train-rmse:0.000819
[87]	train-rmse:0.000819
[88]	train-rmse:0.000819
[89]	train-rmse:0.000819
[90]	train-rmse:0.000819
[91]	train-rmse:0.000819
[92]	train-rmse:0.000819
[93]	train-rmse:0.000819
[94]	train-rmse:0.000819
[95]	train-rmse:0.000819
[96]	train-rmse:0.000819
[97]	train-rmse:0.000819
[98]	train-rmse:0.000819
[99]	train-rmse:0.000819
[100]	train-rmse:0.000819
[101]	train-rmse:0.000819
[102]	train-rmse:0.000819
[103]	train-rmse:0.000819
[104]	train-rmse:0.000819
[105]	train-rmse:0.000819
[106]	train-rmse:0.000819
[107]	train-rmse:0.000819
[108]	train-rmse:0.000819
[109]	train-rmse:0.000819
[110]	train-rmse:0.000819
[111]	train-rmse:0.000819
[112]	train-rmse:0.000819
[113]	train-rmse:0.000819
[114]	train-rmse:0.000819
[115]	train-rmse:0.000819
[116]	train-rmse:0.000819
[117]	train-rmse:0.000819
[118]	train-rmse:0.000819
[119]	train-rmse:0.000819
[120]	train-rmse:0.000819
[121]	train-rmse:0.000819
[122]	train-rmse:0.000819
[123]	train-rmse:0.000819
[124]	train-rmse:0.000819
[125]	train-rmse:0.000819
[126]	train-rmse:0.000819
[127]	train-rmse:0.000819
[128]	train-rmse:0.000819
[129]	train-rmse:0.000819
[130]	train-rmse:0.000819
[131]	train-rmse:0.000819
[132]	train-rmse:0.000819
[133]	train-rmse:0.000819
[134]	train-rmse:0.000819
[135]	train-rmse:0.000819
[136]	train-rmse:0.000819
[137]	train-rmse:0.000819
[138]	train-rmse:0.000819
[139]	train-rmse:0.000819
[140]	train-rmse:0.000819
[141]	train-rmse:0.000819
[142]	train-rmse:0.000819
[143]	train-rmse:0.000819
[144]	train-rmse:0.000819
[145]	train-rmse:0.000819
[146]	train-rmse:0.000819
[147]	train-rmse:0.000819
[148]	train-rmse:0.000819
[149]	train-rmse:0.000819
[150]	train-rmse:0.000819
[151]	train-rmse:0.000819
[152]	train-rmse:0.000819
[153]	train-rmse:0.000819
[154]	train-rmse:0.000819
[155]	train-rmse:0.000819
[156]	train-rmse:0.000819
[157]	train-rmse:0.000819
[158]	train-rmse:0.000819
[159]	train-rmse:0.000819
[160]	train-rmse:0.000819
[161]	train-rmse:0.000819
[162]	train-rmse:0.000819
[163]	train-rmse:0.000819
[164]	train-rmse:0.000819
[165]	train-rmse:0.000819
[166]	train-rmse:0.000819
[167]	train-rmse:0.000819
[168]	train-rmse:0.000819
[169]	train-rmse:0.000819
[170]	train-rmse:0.000819
[171]	train-rmse:0.000819
[172]	train-rmse:0.000819
[173]	train-rmse:0.000819
[174]	train-rmse:0.000819
[175]	train-rmse:0.000819
[176]	train-rmse:0.000819
[177]	train-rmse:0.000819
[178]	train-rmse:0.000819
[179]	train-rmse:0.000819
[180]	train-rmse:0.000819
[181]	train-rmse:0.000819
[182]	train-rmse:0.000819
[183]	train-rmse:0.000819
[184]	train-rmse:0.000819
[185]	train-rmse:0.000819
[186]	train-rmse:0.000819
[187]	train-rmse:0.000819
[188]	train-rmse:0.000819
[189]	train-rmse:0.000819
[190]	train-rmse:0.000819
[191]	train-rmse:0.000819
[192]	train-rmse:0.000819
[193]	train-rmse:0.000819
[194]	train-rmse:0.000819
[195]	train-rmse:0.000819
[196]	train-rmse:0.000819
[197]	train-rmse:0.000819
[198]	train-rmse:0.000819
[199]	train-rmse:0.000819
[200]	train-rmse:0.000819
[201]	train-rmse:0.000819
[202]	train-rmse:0.000819
[203]	train-rmse:0.000819
[204]	train-rmse:0.000819
[205]	train-rmse:0.000819
[206]	train-rmse:0.000819
[207]	train-rmse:0.000819
[208]	train-rmse:0.000819
[209]	train-rmse:0.000819
[210]	train-rmse:0.000819
[211]	train-rmse:0.000819
[212]	train-rmse:0.000819
[213]	train-rmse:0.000819
[214]	train-rmse:0.000819
[215]	train-rmse:0.000819
[216]	train-rmse:0.000819
[217]	train-rmse:0.000819
[218]	train-rmse:0.000819
[219]	train-rmse:0.000819
[220]	train-rmse:0.000819
[221]	train-rmse:0.000819
[222]	train-rmse:0.000819
[223]	train-rmse:0.000819
[224]	train-rmse:0.000819
[225]	train-rmse:0.000819
[226]	train-rmse:0.000819
[227]	train-rmse:0.000819
[228]	train-rmse:0.000819
[229]	train-rmse:0.000819
[230]	train-rmse:0.000819
[231]	train-rmse:0.000819
[232]	train-rmse:0.000819
[233]	train-rmse:0.000819
[234]	train-rmse:0.000819
[235]	train-rmse:0.000819
[236]	train-rmse:0.000819
[237]	train-rmse:0.000819
[238]	train-rmse:0.000819
[239]	train-rmse:0.000819
[240]	train-rmse:0.000819
[241]	train-rmse:0.000819
[242]	train-rmse:0.000819
[243]	train-rmse:0.000819
[244]	train-rmse:0.000819
[245]	train-rmse:0.000819
[246]	train-rmse:0.000819
[247]	train-rmse:0.000819
[248]	train-rmse:0.000819
[249]	train-rmse:0.000819
[250]	train-rmse:0.000819
[251]	train-rmse:0.000819
[252]	train-rmse:0.000819
[253]	train-rmse:0.000819
[254]	train-rmse:0.000819
[255]	train-rmse:0.000819
[256]	train-rmse:0.000819
[257]	train-rmse:0.000819
[258]	train-rmse:0.000819
[259]	train-rmse:0.000819
[260]	train-rmse:0.000819
[261]	train-rmse:0.000819
[262]	train-rmse:0.000819
[263]	train-rmse:0.000819
[264]	train-rmse:0.000819
[265]	train-rmse:0.000819
[266]	train-rmse:0.000819
[267]	train-rmse:0.000819
[268]	train-rmse:0.000819
[269]	train-rmse:0.000819
[270]	train-rmse:0.000819
[271]	train-rmse:0.000819
[272]	train-rmse:0.000819
[273]	train-rmse:0.000819
[274]	train-rmse:0.000819
[275]	train-rmse:0.000819
[276]	train-rmse:0.000819
[277]	train-rmse:0.000819
[278]	train-rmse:0.000819
[279]	train-rmse:0.000819
[280]	train-rmse:0.000819
[281]	train-rmse:0.000819
[282]	train-rmse:0.000819
[283]	train-rmse:0.000819
[284]	train-rmse:0.000819
[285]	train-rmse:0.000819
[286]	train-rmse:0.000819
[287]	train-rmse:0.000819
[288]	train-rmse:0.000819
[289]	train-rmse:0.000819
[290]	train-rmse:0.000819
[291]	train-rmse:0.000819
[292]	train-rmse:0.000819
[293]	train-rmse:0.000819
[294]	train-rmse:0.000819
[295]	train-rmse:0.000819
[296]	train-rmse:0.000819
[297]	train-rmse:0.000819
[298]	train-rmse:0.000819
[299]	train-rmse:0.000819
[300]	train-rmse:0.000819
[301]	train-rmse:0.000819
[302]	train-rmse:0.000819
[303]	train-rmse:0.000819
[304]	train-rmse:0.000819
[305]	train-rmse:0.000819
[306]	train-rmse:0.000819
[307]	train-rmse:0.000819
[308]	train-rmse:0.000819
[309]	train-rmse:0.000819
[310]	train-rmse:0.000819
[311]	train-rmse:0.000819
[312]	train-rmse:0.000819
[313]	train-rmse:0.000819
[314]	train-rmse:0.000819
[315]	train-rmse:0.000819
[316]	train-rmse:0.000819
[317]	train-rmse:0.000819
[318]	train-rmse:0.000819
[319]	train-rmse:0.000819
[320]	train-rmse:0.000819
[321]	train-rmse:0.000819
[322]	train-rmse:0.000819
[323]	train-rmse:0.000819
[324]	train-rmse:0.000819
[325]	train-rmse:0.000819
[326]	train-rmse:0.000819
[327]	train-rmse:0.000819
[328]	train-rmse:0.000819
[329]	train-rmse:0.000819
[330]	train-rmse:0.000819
[331]	train-rmse:0.000819
[332]	train-rmse:0.000819
[333]	train-rmse:0.000819
[334]	train-rmse:0.000819
[335]	train-rmse:0.000819
[336]	train-rmse:0.000819
[337]	train-rmse:0.000819
[338]	train-rmse:0.000819
[339]	train-rmse:0.000819
[340]	train-rmse:0.000819
[341]	train-rmse:0.000819
[342]	train-rmse:0.000819
[343]	train-rmse:0.000819
[344]	train-rmse:0.000819
[345]	train-rmse:0.000819
[346]	train-rmse:0.000819
[347]	train-rmse:0.000819
[348]	train-rmse:0.000819
[349]	train-rmse:0.000819
[350]	train-rmse:0.000819
[351]	train-rmse:0.000819
[352]	train-rmse:0.000819
[353]	train-rmse:0.000819
[354]	train-rmse:0.000819
[355]	train-rmse:0.000819
[356]	train-rmse:0.000819
[357]	train-rmse:0.000819
[358]	train-rmse:0.000819
[359]	train-rmse:0.000819
[360]	train-rmse:0.000819
[361]	train-rmse:0.000819
[362]	train-rmse:0.000819
[363]	train-rmse:0.000819
[364]	train-rmse:0.000819
[365]	train-rmse:0.000819
[366]	train-rmse:0.000819
[367]	train-rmse:0.000819
[368]	train-rmse:0.000819
[369]	train-rmse:0.000819
[370]	train-rmse:0.000819
[371]	train-rmse:0.000819
[372]	train-rmse:0.000819
[373]	train-rmse:0.000819
[374]	train-rmse:0.000819
[375]	train-rmse:0.000819
[376]	train-rmse:0.000819
[377]	train-rmse:0.000819
[378]	train-rmse:0.000819
[379]	train-rmse:0.000819
[380]	train-rmse:0.000819
[381]	train-rmse:0.000819
[382]	train-rmse:0.000819
[383]	train-rmse:0.000819
[384]	train-rmse:0.000819
[385]	train-rmse:0.000819
[386]	train-rmse:0.000819
[387]	train-rmse:0.000819
[388]	train-rmse:0.000819
[389]	train-rmse:0.000819
[390]	train-rmse:0.000819
[391]	train-rmse:0.000819
[392]	train-rmse:0.000819
[393]	train-rmse:0.000819
[394]	train-rmse:0.000819
[395]	train-rmse:0.000819
[396]	train-rmse:0.000819
[397]	train-rmse:0.000819
[398]	train-rmse:0.000819
[399]	train-rmse:0.000819
[400]	train-rmse:0.000819
[401]	train-rmse:0.000819
[402]	train-rmse:0.000819
[403]	train-rmse:0.000819
[404]	train-rmse:0.000819
[405]	train-rmse:0.000819
[406]	train-rmse:0.000819
[407]	train-rmse:0.000819
[408]	train-rmse:0.000819
[409]	train-rmse:0.000819
[410]	train-rmse:0.000819
[411]	train-rmse:0.000819
[412]	train-rmse:0.000819
[413]	train-rmse:0.000819
[414]	train-rmse:0.000819
[415]	train-rmse:0.000819
[416]	train-rmse:0.000819
[417]	train-rmse:0.000819
[418]	train-rmse:0.000819
[419]	train-rmse:0.000819
[420]	train-rmse:0.000819
[421]	train-rmse:0.000819
[422]	train-rmse:0.000819
[423]	train-rmse:0.000819
[424]	train-rmse:0.000819
[425]	train-rmse:0.000819
[426]	train-rmse:0.000819
[427]	train-rmse:0.000819
[428]	train-rmse:0.000819
[429]	train-rmse:0.000819
[430]	train-rmse:0.000819
[431]	train-rmse:0.000819
[432]	train-rmse:0.000819
[433]	train-rmse:0.000819
[434]	train-rmse:0.000819
[435]	train-rmse:0.000819
[436]	train-rmse:0.000819
[437]	train-rmse:0.000819
[438]	train-rmse:0.000819
[439]	train-rmse:0.000819
[440]	train-rmse:0.000819
[441]	train-rmse:0.000819
[442]	train-rmse:0.000819
[443]	train-rmse:0.000819
[444]	train-rmse:0.000819
[445]	train-rmse:0.000819
[446]	train-rmse:0.000819
[447]	train-rmse:0.000819
[448]	train-rmse:0.000819
[449]	train-rmse:0.000819
[450]	train-rmse:0.000819
[451]	train-rmse:0.000819
[452]	train-rmse:0.000819
[453]	train-rmse:0.000819
[454]	train-rmse:0.000819
[455]	train-rmse:0.000819
[456]	train-rmse:0.000819
[457]	train-rmse:0.000819
[458]	train-rmse:0.000819
[459]	train-rmse:0.000819
[460]	train-rmse:0.000819
[461]	train-rmse:0.000819
[462]	train-rmse:0.000819
[463]	train-rmse:0.000819
[464]	train-rmse:0.000819
[465]	train-rmse:0.000819
[466]	train-rmse:0.000819
[467]	train-rmse:0.000819
[468]	train-rmse:0.000819
[469]	train-rmse:0.000819
[470]	train-rmse:0.000819
[471]	train-rmse:0.000819
[472]	train-rmse:0.000819
[473]	train-rmse:0.000819
[474]	train-rmse:0.000819
[475]	train-rmse:0.000819
[476]	train-rmse:0.000819
[477]	train-rmse:0.000819
[478]	train-rmse:0.000819
[479]	train-rmse:0.000819
[480]	train-rmse:0.000819
[481]	train-rmse:0.000819
[482]	train-rmse:0.000819
[483]	train-rmse:0.000819
[484]	train-rmse:0.000819
[485]	train-rmse:0.000819
[486]	train-rmse:0.000819
[487]	train-rmse:0.000819
[488]	train-rmse:0.000819
[489]	train-rmse:0.000819
[490]	train-rmse:0.000819
[491]	train-rmse:0.000819
[492]	train-rmse:0.000819
[493]	train-rmse:0.000819
[494]	train-rmse:0.000819
[495]	train-rmse:0.000819
[496]	train-rmse:0.000819
[497]	train-rmse:0.000819
[498]	train-rmse:0.000819
[499]	train-rmse:0.000819
[500]	train-rmse:0.000819

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [30]:
xgb_min_cl <- xgboost(data = dtrain_xg_min_cl, nround=500, objective='multi:softmax',num_class=5)

[1]	train-merror:0.131387
[2]	train-merror:0.051095
[3]	train-merror:0.043796
[4]	train-merror:0.014599
[5]	train-merror:0.000000
[6]	train-merror:0.000000
[7]	train-merror:0.000000
[8]	train-merror:0.000000
[9]	train-merror:0.000000
[10]	train-merror:0.000000
[11]	train-merror:0.000000
[12]	train-merror:0.000000
[13]	train-merror:0.000000
[14]	train-merror:0.000000
[15]	train-merror:0.000000
[16]	train-merror:0.000000
[17]	train-merror:0.000000
[18]	train-merror:0.000000
[19]	train-merror:0.000000
[20]	train-merror:0.000000
[21]	train-merror:0.000000
[22]	train-merror:0.000000
[23]	train-merror:0.000000
[24]	train-merror:0.000000
[25]	train-merror:0.000000
[26]	train-merror:0.000000
[27]	train-merror:0.000000
[28]	train-merror:0.000000
[29]	train-merror:0.000000
[30]	train-merror:0.000000
[31]	train-merror:0.000000
[32]	train-merror:0.000000
[33]	train-merror:0.000000
[34]	train-merror:0.000000
[35]	train-merror:0.000000
[36]	train-merror:0.000000
[37]	train-merror:0.000000
[38]	train-merror:0.000000
[39]	train-merror:0.000000
[40]	train-merror:0.000000
[41]	train-merror:0.000000
[42]	train-merror:0.000000
[43]	train-merror:0.000000
[44]	train-merror:0.000000
[45]	train-merror:0.000000
[46]	train-merror:0.000000
[47]	train-merror:0.000000
[48]	train-merror:0.000000
[49]	train-merror:0.000000
[50]	train-merror:0.000000
[51]	train-merror:0.000000
[52]	train-merror:0.000000
[53]	train-merror:0.000000
[54]	train-merror:0.000000
[55]	train-merror:0.000000
[56]	train-merror:0.000000
[57]	train-merror:0.000000
[58]	train-merror:0.000000
[59]	train-merror:0.000000
[60]	train-merror:0.000000
[61]	train-merror:0.000000
[62]	train-merror:0.000000
[63]	train-merror:0.000000
[64]	train-merror:0.000000
[65]	train-merror:0.000000
[66]	train-merror:0.000000
[67]	train-merror:0.000000
[68]	train-merror:0.000000
[69]	train-merror:0.000000
[70]	train-merror:0.000000
[71]	train-merror:0.000000
[72]	train-merror:0.000000
[73]	train-merror:0.000000
[74]	train-merror:0.000000
[75]	train-merror:0.000000
[76]	train-merror:0.000000
[77]	train-merror:0.000000
[78]	train-merror:0.000000
[79]	train-merror:0.000000
[80]	train-merror:0.000000
[81]	train-merror:0.000000
[82]	train-merror:0.000000
[83]	train-merror:0.000000
[84]	train-merror:0.000000
[85]	train-merror:0.000000
[86]	train-merror:0.000000
[87]	train-merror:0.000000
[88]	train-merror:0.000000
[89]	train-merror:0.000000
[90]	train-merror:0.000000
[91]	train-merror:0.000000
[92]	train-merror:0.000000
[93]	train-merror:0.000000
[94]	train-merror:0.000000
[95]	train-merror:0.000000
[96]	train-merror:0.000000
[97]	train-merror:0.000000
[98]	train-merror:0.000000
[99]	train-merror:0.000000
[100]	train-merror:0.000000
[101]	train-merror:0.000000
[102]	train-merror:0.000000
[103]	train-merror:0.000000
[104]	train-merror:0.000000
[105]	train-merror:0.000000
[106]	train-merror:0.000000
[107]	train-merror:0.000000
[108]	train-merror:0.000000
[109]	train-merror:0.000000
[110]	train-merror:0.000000
[111]	train-merror:0.000000
[112]	train-merror:0.000000
[113]	train-merror:0.000000
[114]	train-merror:0.000000
[115]	train-merror:0.000000
[116]	train-merror:0.000000
[117]	train-merror:0.000000
[118]	train-merror:0.000000
[119]	train-merror:0.000000
[120]	train-merror:0.000000
[121]	train-merror:0.000000
[122]	train-merror:0.000000
[123]	train-merror:0.000000
[124]	train-merror:0.000000
[125]	train-merror:0.000000
[126]	train-merror:0.000000
[127]	train-merror:0.000000
[128]	train-merror:0.000000
[129]	train-merror:0.000000
[130]	train-merror:0.000000
[131]	train-merror:0.000000
[132]	train-merror:0.000000
[133]	train-merror:0.000000
[134]	train-merror:0.000000
[135]	train-merror:0.000000
[136]	train-merror:0.000000
[137]	train-merror:0.000000
[138]	train-merror:0.000000
[139]	train-merror:0.000000
[140]	train-merror:0.000000
[141]	train-merror:0.000000
[142]	train-merror:0.000000
[143]	train-merror:0.000000
[144]	train-merror:0.000000
[145]	train-merror:0.000000
[146]	train-merror:0.000000
[147]	train-merror:0.000000
[148]	train-merror:0.000000
[149]	train-merror:0.000000
[150]	train-merror:0.000000
[151]	train-merror:0.000000
[152]	train-merror:0.000000
[153]	train-merror:0.000000
[154]	train-merror:0.000000
[155]	train-merror:0.000000
[156]	train-merror:0.000000
[157]	train-merror:0.000000
[158]	train-merror:0.000000
[159]	train-merror:0.000000
[160]	train-merror:0.000000
[161]	train-merror:0.000000
[162]	train-merror:0.000000
[163]	train-merror:0.000000
[164]	train-merror:0.000000
[165]	train-merror:0.000000
[166]	train-merror:0.000000
[167]	train-merror:0.000000
[168]	train-merror:0.000000
[169]	train-merror:0.000000
[170]	train-merror:0.000000
[171]	train-merror:0.000000
[172]	train-merror:0.000000
[173]	train-merror:0.000000
[174]	train-merror:0.000000
[175]	train-merror:0.000000
[176]	train-merror:0.000000
[177]	train-merror:0.000000
[178]	train-merror:0.000000
[179]	train-merror:0.000000
[180]	train-merror:0.000000
[181]	train-merror:0.000000
[182]	train-merror:0.000000
[183]	train-merror:0.000000
[184]	train-merror:0.000000
[185]	train-merror:0.000000
[186]	train-merror:0.000000
[187]	train-merror:0.000000
[188]	train-merror:0.000000
[189]	train-merror:0.000000
[190]	train-merror:0.000000
[191]	train-merror:0.000000
[192]	train-merror:0.000000
[193]	train-merror:0.000000
[194]	train-merror:0.000000
[195]	train-merror:0.000000
[196]	train-merror:0.000000
[197]	train-merror:0.000000
[198]	train-merror:0.000000
[199]	train-merror:0.000000
[200]	train-merror:0.000000
[201]	train-merror:0.000000
[202]	train-merror:0.000000
[203]	train-merror:0.000000
[204]	train-merror:0.000000
[205]	train-merror:0.000000
[206]	train-merror:0.000000
[207]	train-merror:0.000000
[208]	train-merror:0.000000
[209]	train-merror:0.000000
[210]	train-merror:0.000000
[211]	train-merror:0.000000
[212]	train-merror:0.000000
[213]	train-merror:0.000000
[214]	train-merror:0.000000
[215]	train-merror:0.000000
[216]	train-merror:0.000000
[217]	train-merror:0.000000
[218]	train-merror:0.000000
[219]	train-merror:0.000000
[220]	train-merror:0.000000
[221]	train-merror:0.000000
[222]	train-merror:0.000000
[223]	train-merror:0.000000
[224]	train-merror:0.000000
[225]	train-merror:0.000000
[226]	train-merror:0.000000
[227]	train-merror:0.000000
[228]	train-merror:0.000000
[229]	train-merror:0.000000
[230]	train-merror:0.000000
[231]	train-merror:0.000000
[232]	train-merror:0.000000
[233]	train-merror:0.000000
[234]	train-merror:0.000000
[235]	train-merror:0.000000
[236]	train-merror:0.000000
[237]	train-merror:0.000000
[238]	train-merror:0.000000
[239]	train-merror:0.000000
[240]	train-merror:0.000000
[241]	train-merror:0.000000
[242]	train-merror:0.000000
[243]	train-merror:0.000000
[244]	train-merror:0.000000
[245]	train-merror:0.000000
[246]	train-merror:0.000000
[247]	train-merror:0.000000
[248]	train-merror:0.000000
[249]	train-merror:0.000000
[250]	train-merror:0.000000
[251]	train-merror:0.000000
[252]	train-merror:0.000000
[253]	train-merror:0.000000
[254]	train-merror:0.000000
[255]	train-merror:0.000000
[256]	train-merror:0.000000
[257]	train-merror:0.000000
[258]	train-merror:0.000000
[259]	train-merror:0.000000
[260]	train-merror:0.000000
[261]	train-merror:0.000000
[262]	train-merror:0.000000
[263]	train-merror:0.000000
[264]	train-merror:0.000000
[265]	train-merror:0.000000
[266]	train-merror:0.000000
[267]	train-merror:0.000000
[268]	train-merror:0.000000
[269]	train-merror:0.000000
[270]	train-merror:0.000000
[271]	train-merror:0.000000
[272]	train-merror:0.000000
[273]	train-merror:0.000000
[274]	train-merror:0.000000
[275]	train-merror:0.000000
[276]	train-merror:0.000000
[277]	train-merror:0.000000
[278]	train-merror:0.000000
[279]	train-merror:0.000000
[280]	train-merror:0.000000
[281]	train-merror:0.000000
[282]	train-merror:0.000000
[283]	train-merror:0.000000
[284]	train-merror:0.000000
[285]	train-merror:0.000000
[286]	train-merror:0.000000
[287]	train-merror:0.000000
[288]	train-merror:0.000000
[289]	train-merror:0.000000
[290]	train-merror:0.000000
[291]	train-merror:0.000000
[292]	train-merror:0.000000
[293]	train-merror:0.000000
[294]	train-merror:0.000000
[295]	train-merror:0.000000
[296]	train-merror:0.000000
[297]	train-merror:0.000000
[298]	train-merror:0.000000
[299]	train-merror:0.000000
[300]	train-merror:0.000000
[301]	train-merror:0.000000
[302]	train-merror:0.000000
[303]	train-merror:0.000000
[304]	train-merror:0.000000
[305]	train-merror:0.000000
[306]	train-merror:0.000000
[307]	train-merror:0.000000
[308]	train-merror:0.000000
[309]	train-merror:0.000000
[310]	train-merror:0.000000
[311]	train-merror:0.000000
[312]	train-merror:0.000000
[313]	train-merror:0.000000
[314]	train-merror:0.000000
[315]	train-merror:0.000000
[316]	train-merror:0.000000
[317]	train-merror:0.000000
[318]	train-merror:0.000000
[319]	train-merror:0.000000
[320]	train-merror:0.000000
[321]	train-merror:0.000000
[322]	train-merror:0.000000
[323]	train-merror:0.000000
[324]	train-merror:0.000000
[325]	train-merror:0.000000
[326]	train-merror:0.000000
[327]	train-merror:0.000000
[328]	train-merror:0.000000
[329]	train-merror:0.000000
[330]	train-merror:0.000000
[331]	train-merror:0.000000
[332]	train-merror:0.000000
[333]	train-merror:0.000000
[334]	train-merror:0.000000
[335]	train-merror:0.000000
[336]	train-merror:0.000000
[337]	train-merror:0.000000
[338]	train-merror:0.000000
[339]	train-merror:0.000000
[340]	train-merror:0.000000
[341]	train-merror:0.000000
[342]	train-merror:0.000000
[343]	train-merror:0.000000
[344]	train-merror:0.000000
[345]	train-merror:0.000000
[346]	train-merror:0.000000
[347]	train-merror:0.000000
[348]	train-merror:0.000000
[349]	train-merror:0.000000
[350]	train-merror:0.000000
[351]	train-merror:0.000000
[352]	train-merror:0.000000
[353]	train-merror:0.000000
[354]	train-merror:0.000000
[355]	train-merror:0.000000
[356]	train-merror:0.000000
[357]	train-merror:0.000000
[358]	train-merror:0.000000
[359]	train-merror:0.000000
[360]	train-merror:0.000000
[361]	train-merror:0.000000
[362]	train-merror:0.000000
[363]	train-merror:0.000000
[364]	train-merror:0.000000
[365]	train-merror:0.000000
[366]	train-merror:0.000000
[367]	train-merror:0.000000
[368]	train-merror:0.000000
[369]	train-merror:0.000000
[370]	train-merror:0.000000
[371]	train-merror:0.000000
[372]	train-merror:0.000000
[373]	train-merror:0.000000
[374]	train-merror:0.000000
[375]	train-merror:0.000000
[376]	train-merror:0.000000
[377]	train-merror:0.000000
[378]	train-merror:0.000000
[379]	train-merror:0.000000
[380]	train-merror:0.000000
[381]	train-merror:0.000000
[382]	train-merror:0.000000
[383]	train-merror:0.000000
[384]	train-merror:0.000000
[385]	train-merror:0.000000
[386]	train-merror:0.000000
[387]	train-merror:0.000000
[388]	train-merror:0.000000
[389]	train-merror:0.000000
[390]	train-merror:0.000000
[391]	train-merror:0.000000
[392]	train-merror:0.000000
[393]	train-merror:0.000000
[394]	train-merror:0.000000
[395]	train-merror:0.000000
[396]	train-merror:0.000000
[397]	train-merror:0.000000
[398]	train-merror:0.000000
[399]	train-merror:0.000000
[400]	train-merror:0.000000
[401]	train-merror:0.000000
[402]	train-merror:0.000000
[403]	train-merror:0.000000
[404]	train-merror:0.000000
[405]	train-merror:0.000000
[406]	train-merror:0.000000
[407]	train-merror:0.000000
[408]	train-merror:0.000000
[409]	train-merror:0.000000
[410]	train-merror:0.000000
[411]	train-merror:0.000000
[412]	train-merror:0.000000
[413]	train-merror:0.000000
[414]	train-merror:0.000000
[415]	train-merror:0.000000
[416]	train-merror:0.000000
[417]	train-merror:0.000000
[418]	train-merror:0.000000
[419]	train-merror:0.000000
[420]	train-merror:0.000000
[421]	train-merror:0.000000
[422]	train-merror:0.000000
[423]	train-merror:0.000000
[424]	train-merror:0.000000
[425]	train-merror:0.000000
[426]	train-merror:0.000000
[427]	train-merror:0.000000
[428]	train-merror:0.000000
[429]	train-merror:0.000000
[430]	train-merror:0.000000
[431]	train-merror:0.000000
[432]	train-merror:0.000000
[433]	train-merror:0.000000
[434]	train-merror:0.000000
[435]	train-merror:0.000000
[436]	train-merror:0.000000
[437]	train-merror:0.000000
[438]	train-merror:0.000000
[439]	train-merror:0.000000
[440]	train-merror:0.000000
[441]	train-merror:0.000000
[442]	train-merror:0.000000
[443]	train-merror:0.000000
[444]	train-merror:0.000000
[445]	train-merror:0.000000
[446]	train-merror:0.000000
[447]	train-merror:0.000000
[448]	train-merror:0.000000
[449]	train-merror:0.000000
[450]	train-merror:0.000000
[451]	train-merror:0.000000
[452]	train-merror:0.000000
[453]	train-merror:0.000000
[454]	train-merror:0.000000
[455]	train-merror:0.000000
[456]	train-merror:0.000000
[457]	train-merror:0.000000
[458]	train-merror:0.000000
[459]	train-merror:0.000000
[460]	train-merror:0.000000
[461]	train-merror:0.000000
[462]	train-merror:0.000000
[463]	train-merror:0.000000
[464]	train-merror:0.000000
[465]	train-merror:0.000000
[466]	train-merror:0.000000
[467]	train-merror:0.000000
[468]	train-merror:0.000000
[469]	train-merror:0.000000
[470]	train-merror:0.000000
[471]	train-merror:0.000000
[472]	train-merror:0.000000
[473]	train-merror:0.000000
[474]	train-merror:0.000000
[475]	train-merror:0.000000
[476]	train-merror:0.000000
[477]	train-merror:0.000000
[478]	train-merror:0.000000
[479]	train-merror:0.000000
[480]	train-merror:0.000000
[481]	train-merror:0.000000
[482]	train-merror:0.000000
[483]	train-merror:0.000000
[484]	train-merror:0.000000
[485]	train-merror:0.000000
[486]	train-merror:0.000000
[487]	train-merror:0.000000
[488]	train-merror:0.000000
[489]	train-merror:0.000000
[490]	train-merror:0.000000
[491]	train-merror:0.000000
[492]	train-merror:0.000000
[493]	train-merror:0.000000
[494]	train-merror:0.000000
[495]	train-merror:0.000000
[496]	train-merror:0.000000
[497]	train-merror:0.000000
[498]	train-merror:0.000000
[499]	train-merror:0.000000
[500]	train-merror:0.000000

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [31]:
lgb_min_reg <- lgb.train(data = dtrain_lg_min_reg, nrounds = 500)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011252 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 775
[LightGBM] [Info] Number of data points in the train set: 137, number of used features: 17
[LightGBM] [Info] Start training from score 2.591241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [32]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_min_cl <- lgb.train(data = dtrain_lg_min_cl,nrounds = 500,params=params)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005863 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 775
[LightGBM] [Info] Number of data points in the train set: 137, number of used features: 17
[LightGBM] [Info] Start training from score -1.924249
[LightGBM] [Info] Start training from score -2.435074
[LightGBM] [Info] Start training from score -1.741927
[LightGBM] [Info] Start training from score -1.552685
[LightGBM] [Info] Start training from score -0.968737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [33]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

## Target the interval where the average error is minimum

In [34]:
start_time = Sys.time()

In [35]:
dtrain_xg_mean_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_mean)) 
dtrain_xg_mean_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)) )

In [36]:
dtrain_lg_mean_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_mean))
dtrain_lg_mean_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)))

In [37]:
xgb_mean_reg <- xgboost(data = dtrain_xg_mean_reg, nround=500)

[1]	train-rmse:1.647725
[2]	train-rmse:1.236831
[3]	train-rmse:0.935826
[4]	train-rmse:0.726921
[5]	train-rmse:0.563737
[6]	train-rmse:0.456652
[7]	train-rmse:0.377894
[8]	train-rmse:0.304184
[9]	train-rmse:0.248975
[10]	train-rmse:0.212769
[11]	train-rmse:0.180223
[12]	train-rmse:0.163760
[13]	train-rmse:0.145025
[14]	train-rmse:0.129368
[15]	train-rmse:0.114375
[16]	train-rmse:0.104106
[17]	train-rmse:0.098625
[18]	train-rmse:0.087833
[19]	train-rmse:0.079775
[20]	train-rmse:0.068843
[21]	train-rmse:0.062069
[22]	train-rmse:0.054200
[23]	train-rmse:0.048360
[24]	train-rmse:0.045409
[25]	train-rmse:0.041516
[26]	train-rmse:0.038648
[27]	train-rmse:0.036573
[28]	train-rmse:0.032836
[29]	train-rmse:0.028873
[30]	train-rmse:0.025230
[31]	train-rmse:0.022089
[32]	train-rmse:0.019084
[33]	train-rmse:0.018169
[34]	train-rmse:0.015413
[35]	train-rmse:0.014058
[36]	train-rmse:0.012803
[37]	train-rmse:0.011779
[38]	train-rmse:0.010662
[39]	train-rmse:0.009960
[40]	train-rmse:0.008959
[41]	train-rmse:0.007936
[42]	train-rmse:0.007341
[43]	train-rmse:0.006886
[44]	train-rmse:0.006182
[45]	train-rmse:0.005821
[46]	train-rmse:0.005218
[47]	train-rmse:0.004789
[48]	train-rmse:0.004337
[49]	train-rmse:0.003714
[50]	train-rmse:0.003273
[51]	train-rmse:0.002849
[52]	train-rmse:0.002688
[53]	train-rmse:0.002293
[54]	train-rmse:0.002143
[55]	train-rmse:0.001985
[56]	train-rmse:0.001774
[57]	train-rmse:0.001660
[58]	train-rmse:0.001547
[59]	train-rmse:0.001440
[60]	train-rmse:0.001213
[61]	train-rmse:0.001063
[62]	train-rmse:0.001023
[63]	train-rmse:0.000938
[64]	train-rmse:0.000854
[65]	train-rmse:0.000744
[66]	train-rmse:0.000744
[67]	train-rmse:0.000744
[68]	train-rmse:0.000744
[69]	train-rmse:0.000744
[70]	train-rmse:0.000744
[71]	train-rmse:0.000744
[72]	train-rmse:0.000744
[73]	train-rmse:0.000744
[74]	train-rmse:0.000744
[75]	train-rmse:0.000744
[76]	train-rmse:0.000744
[77]	train-rmse:0.000744
[78]	train-rmse:0.000744
[79]	train-rmse:0.000744
[80]	train-rmse:0.000744
[81]	train-rmse:0.000744
[82]	train-rmse:0.000744
[83]	train-rmse:0.000744
[84]	train-rmse:0.000744
[85]	train-rmse:0.000744
[86]	train-rmse:0.000744
[87]	train-rmse:0.000744
[88]	train-rmse:0.000744
[89]	train-rmse:0.000744
[90]	train-rmse:0.000744
[91]	train-rmse:0.000744
[92]	train-rmse:0.000744
[93]	train-rmse:0.000744
[94]	train-rmse:0.000744
[95]	train-rmse:0.000744
[96]	train-rmse:0.000744
[97]	train-rmse:0.000744
[98]	train-rmse:0.000744
[99]	train-rmse:0.000744
[100]	train-rmse:0.000744
[101]	train-rmse:0.000744
[102]	train-rmse:0.000744
[103]	train-rmse:0.000744
[104]	train-rmse:0.000744
[105]	train-rmse:0.000744
[106]	train-rmse:0.000744
[107]	train-rmse:0.000744
[108]	train-rmse:0.000744
[109]	train-rmse:0.000744
[110]	train-rmse:0.000744
[111]	train-rmse:0.000744
[112]	train-rmse:0.000744
[113]	train-rmse:0.000744
[114]	train-rmse:0.000744
[115]	train-rmse:0.000744
[116]	train-rmse:0.000744
[117]	train-rmse:0.000744
[118]	train-rmse:0.000744
[119]	train-rmse:0.000744
[120]	train-rmse:0.000744
[121]	train-rmse:0.000744
[122]	train-rmse:0.000744
[123]	train-rmse:0.000744
[124]	train-rmse:0.000744
[125]	train-rmse:0.000744
[126]	train-rmse:0.000744
[127]	train-rmse:0.000744
[128]	train-rmse:0.000744
[129]	train-rmse:0.000744
[130]	train-rmse:0.000744
[131]	train-rmse:0.000744
[132]	train-rmse:0.000744
[133]	train-rmse:0.000744
[134]	train-rmse:0.000744
[135]	train-rmse:0.000744
[136]	train-rmse:0.000744
[137]	train-rmse:0.000744
[138]	train-rmse:0.000744
[139]	train-rmse:0.000744
[140]	train-rmse:0.000744
[141]	train-rmse:0.000744
[142]	train-rmse:0.000744
[143]	train-rmse:0.000744
[144]	train-rmse:0.000744
[145]	train-rmse:0.000744
[146]	train-rmse:0.000744
[147]	train-rmse:0.000744
[148]	train-rmse:0.000744
[149]	train-rmse:0.000744
[150]	train-rmse:0.000744
[151]	train-rmse:0.000744
[152]	train-rmse:0.000744
[153]	train-rmse:0.000744
[154]	train-rmse:0.000744
[155]	train-rmse:0.000744
[156]	train-rmse:0.000744
[157]	train-rmse:0.000744
[158]	train-rmse:0.000744
[159]	train-rmse:0.000744
[160]	train-rmse:0.000744
[161]	train-rmse:0.000744
[162]	train-rmse:0.000744
[163]	train-rmse:0.000744
[164]	train-rmse:0.000744
[165]	train-rmse:0.000744
[166]	train-rmse:0.000744
[167]	train-rmse:0.000744
[168]	train-rmse:0.000744
[169]	train-rmse:0.000744
[170]	train-rmse:0.000744
[171]	train-rmse:0.000744
[172]	train-rmse:0.000744
[173]	train-rmse:0.000744
[174]	train-rmse:0.000744
[175]	train-rmse:0.000744
[176]	train-rmse:0.000744
[177]	train-rmse:0.000744
[178]	train-rmse:0.000744
[179]	train-rmse:0.000744
[180]	train-rmse:0.000744
[181]	train-rmse:0.000744
[182]	train-rmse:0.000744
[183]	train-rmse:0.000744
[184]	train-rmse:0.000744
[185]	train-rmse:0.000744
[186]	train-rmse:0.000744
[187]	train-rmse:0.000744
[188]	train-rmse:0.000744
[189]	train-rmse:0.000744
[190]	train-rmse:0.000744
[191]	train-rmse:0.000744
[192]	train-rmse:0.000744
[193]	train-rmse:0.000744
[194]	train-rmse:0.000744
[195]	train-rmse:0.000744
[196]	train-rmse:0.000744
[197]	train-rmse:0.000744
[198]	train-rmse:0.000744
[199]	train-rmse:0.000744
[200]	train-rmse:0.000744
[201]	train-rmse:0.000744
[202]	train-rmse:0.000744
[203]	train-rmse:0.000744
[204]	train-rmse:0.000744
[205]	train-rmse:0.000744
[206]	train-rmse:0.000744
[207]	train-rmse:0.000744
[208]	train-rmse:0.000744
[209]	train-rmse:0.000744
[210]	train-rmse:0.000744
[211]	train-rmse:0.000744
[212]	train-rmse:0.000744
[213]	train-rmse:0.000744
[214]	train-rmse:0.000744
[215]	train-rmse:0.000744
[216]	train-rmse:0.000744
[217]	train-rmse:0.000744
[218]	train-rmse:0.000744
[219]	train-rmse:0.000744
[220]	train-rmse:0.000744
[221]	train-rmse:0.000744
[222]	train-rmse:0.000744
[223]	train-rmse:0.000744
[224]	train-rmse:0.000744
[225]	train-rmse:0.000744
[226]	train-rmse:0.000744
[227]	train-rmse:0.000744
[228]	train-rmse:0.000744
[229]	train-rmse:0.000744
[230]	train-rmse:0.000744
[231]	train-rmse:0.000744
[232]	train-rmse:0.000744
[233]	train-rmse:0.000744
[234]	train-rmse:0.000744
[235]	train-rmse:0.000744
[236]	train-rmse:0.000744
[237]	train-rmse:0.000744
[238]	train-rmse:0.000744
[239]	train-rmse:0.000744
[240]	train-rmse:0.000744
[241]	train-rmse:0.000744
[242]	train-rmse:0.000744
[243]	train-rmse:0.000744
[244]	train-rmse:0.000744
[245]	train-rmse:0.000744
[246]	train-rmse:0.000744
[247]	train-rmse:0.000744
[248]	train-rmse:0.000744
[249]	train-rmse:0.000744
[250]	train-rmse:0.000744
[251]	train-rmse:0.000744
[252]	train-rmse:0.000744
[253]	train-rmse:0.000744
[254]	train-rmse:0.000744
[255]	train-rmse:0.000744
[256]	train-rmse:0.000744
[257]	train-rmse:0.000744
[258]	train-rmse:0.000744
[259]	train-rmse:0.000744
[260]	train-rmse:0.000744
[261]	train-rmse:0.000744
[262]	train-rmse:0.000744
[263]	train-rmse:0.000744
[264]	train-rmse:0.000744
[265]	train-rmse:0.000744
[266]	train-rmse:0.000744
[267]	train-rmse:0.000744
[268]	train-rmse:0.000744
[269]	train-rmse:0.000744
[270]	train-rmse:0.000744
[271]	train-rmse:0.000744
[272]	train-rmse:0.000744
[273]	train-rmse:0.000744
[274]	train-rmse:0.000744
[275]	train-rmse:0.000744
[276]	train-rmse:0.000744
[277]	train-rmse:0.000744
[278]	train-rmse:0.000744
[279]	train-rmse:0.000744
[280]	train-rmse:0.000744
[281]	train-rmse:0.000744
[282]	train-rmse:0.000744
[283]	train-rmse:0.000744
[284]	train-rmse:0.000744
[285]	train-rmse:0.000744
[286]	train-rmse:0.000744
[287]	train-rmse:0.000744
[288]	train-rmse:0.000744
[289]	train-rmse:0.000744
[290]	train-rmse:0.000744
[291]	train-rmse:0.000744
[292]	train-rmse:0.000744
[293]	train-rmse:0.000744
[294]	train-rmse:0.000744
[295]	train-rmse:0.000744
[296]	train-rmse:0.000744
[297]	train-rmse:0.000744
[298]	train-rmse:0.000744
[299]	train-rmse:0.000744
[300]	train-rmse:0.000744
[301]	train-rmse:0.000744
[302]	train-rmse:0.000744
[303]	train-rmse:0.000744
[304]	train-rmse:0.000744
[305]	train-rmse:0.000744
[306]	train-rmse:0.000744
[307]	train-rmse:0.000744
[308]	train-rmse:0.000744
[309]	train-rmse:0.000744
[310]	train-rmse:0.000744
[311]	train-rmse:0.000744
[312]	train-rmse:0.000744
[313]	train-rmse:0.000744
[314]	train-rmse:0.000744
[315]	train-rmse:0.000744
[316]	train-rmse:0.000744
[317]	train-rmse:0.000744
[318]	train-rmse:0.000744
[319]	train-rmse:0.000744
[320]	train-rmse:0.000744
[321]	train-rmse:0.000744
[322]	train-rmse:0.000744
[323]	train-rmse:0.000744
[324]	train-rmse:0.000744
[325]	train-rmse:0.000744
[326]	train-rmse:0.000744
[327]	train-rmse:0.000744
[328]	train-rmse:0.000744
[329]	train-rmse:0.000744
[330]	train-rmse:0.000744
[331]	train-rmse:0.000744
[332]	train-rmse:0.000744
[333]	train-rmse:0.000744
[334]	train-rmse:0.000744
[335]	train-rmse:0.000744
[336]	train-rmse:0.000744
[337]	train-rmse:0.000744
[338]	train-rmse:0.000744
[339]	train-rmse:0.000744
[340]	train-rmse:0.000744
[341]	train-rmse:0.000744
[342]	train-rmse:0.000744
[343]	train-rmse:0.000744
[344]	train-rmse:0.000744
[345]	train-rmse:0.000744
[346]	train-rmse:0.000744
[347]	train-rmse:0.000744
[348]	train-rmse:0.000744
[349]	train-rmse:0.000744
[350]	train-rmse:0.000744
[351]	train-rmse:0.000744
[352]	train-rmse:0.000744
[353]	train-rmse:0.000744
[354]	train-rmse:0.000744
[355]	train-rmse:0.000744
[356]	train-rmse:0.000744
[357]	train-rmse:0.000744
[358]	train-rmse:0.000744
[359]	train-rmse:0.000744
[360]	train-rmse:0.000744
[361]	train-rmse:0.000744
[362]	train-rmse:0.000744
[363]	train-rmse:0.000744
[364]	train-rmse:0.000744
[365]	train-rmse:0.000744
[366]	train-rmse:0.000744
[367]	train-rmse:0.000744
[368]	train-rmse:0.000744
[369]	train-rmse:0.000744
[370]	train-rmse:0.000744
[371]	train-rmse:0.000744
[372]	train-rmse:0.000744
[373]	train-rmse:0.000744
[374]	train-rmse:0.000744
[375]	train-rmse:0.000744
[376]	train-rmse:0.000744
[377]	train-rmse:0.000744
[378]	train-rmse:0.000744
[379]	train-rmse:0.000744
[380]	train-rmse:0.000744
[381]	train-rmse:0.000744
[382]	train-rmse:0.000744
[383]	train-rmse:0.000744
[384]	train-rmse:0.000744
[385]	train-rmse:0.000744
[386]	train-rmse:0.000744
[387]	train-rmse:0.000744
[388]	train-rmse:0.000744
[389]	train-rmse:0.000744
[390]	train-rmse:0.000744
[391]	train-rmse:0.000744
[392]	train-rmse:0.000744
[393]	train-rmse:0.000744
[394]	train-rmse:0.000744
[395]	train-rmse:0.000744
[396]	train-rmse:0.000744
[397]	train-rmse:0.000744
[398]	train-rmse:0.000744
[399]	train-rmse:0.000744
[400]	train-rmse:0.000744
[401]	train-rmse:0.000744
[402]	train-rmse:0.000744
[403]	train-rmse:0.000744
[404]	train-rmse:0.000744
[405]	train-rmse:0.000744
[406]	train-rmse:0.000744
[407]	train-rmse:0.000744
[408]	train-rmse:0.000744
[409]	train-rmse:0.000744
[410]	train-rmse:0.000744
[411]	train-rmse:0.000744
[412]	train-rmse:0.000744
[413]	train-rmse:0.000744
[414]	train-rmse:0.000744
[415]	train-rmse:0.000744
[416]	train-rmse:0.000744
[417]	train-rmse:0.000744
[418]	train-rmse:0.000744
[419]	train-rmse:0.000744
[420]	train-rmse:0.000744
[421]	train-rmse:0.000744
[422]	train-rmse:0.000744
[423]	train-rmse:0.000744
[424]	train-rmse:0.000744
[425]	train-rmse:0.000744
[426]	train-rmse:0.000744
[427]	train-rmse:0.000744
[428]	train-rmse:0.000744
[429]	train-rmse:0.000744
[430]	train-rmse:0.000744
[431]	train-rmse:0.000744
[432]	train-rmse:0.000744
[433]	train-rmse:0.000744
[434]	train-rmse:0.000744
[435]	train-rmse:0.000744
[436]	train-rmse:0.000744
[437]	train-rmse:0.000744
[438]	train-rmse:0.000744
[439]	train-rmse:0.000744
[440]	train-rmse:0.000744
[441]	train-rmse:0.000744
[442]	train-rmse:0.000744
[443]	train-rmse:0.000744
[444]	train-rmse:0.000744
[445]	train-rmse:0.000744
[446]	train-rmse:0.000744
[447]	train-rmse:0.000744
[448]	train-rmse:0.000744
[449]	train-rmse:0.000744
[450]	train-rmse:0.000744
[451]	train-rmse:0.000744
[452]	train-rmse:0.000744
[453]	train-rmse:0.000744
[454]	train-rmse:0.000744
[455]	train-rmse:0.000744
[456]	train-rmse:0.000744
[457]	train-rmse:0.000744
[458]	train-rmse:0.000744
[459]	train-rmse:0.000744
[460]	train-rmse:0.000744
[461]	train-rmse:0.000744
[462]	train-rmse:0.000744
[463]	train-rmse:0.000744
[464]	train-rmse:0.000744
[465]	train-rmse:0.000744
[466]	train-rmse:0.000744
[467]	train-rmse:0.000744
[468]	train-rmse:0.000744
[469]	train-rmse:0.000744
[470]	train-rmse:0.000744
[471]	train-rmse:0.000744
[472]	train-rmse:0.000744
[473]	train-rmse:0.000744
[474]	train-rmse:0.000744
[475]	train-rmse:0.000744
[476]	train-rmse:0.000744
[477]	train-rmse:0.000744
[478]	train-rmse:0.000744
[479]	train-rmse:0.000744
[480]	train-rmse:0.000744
[481]	train-rmse:0.000744
[482]	train-rmse:0.000744
[483]	train-rmse:0.000744
[484]	train-rmse:0.000744
[485]	train-rmse:0.000744
[486]	train-rmse:0.000744
[487]	train-rmse:0.000744
[488]	train-rmse:0.000744
[489]	train-rmse:0.000744
[490]	train-rmse:0.000744
[491]	train-rmse:0.000744
[492]	train-rmse:0.000744
[493]	train-rmse:0.000744
[494]	train-rmse:0.000744
[495]	train-rmse:0.000744
[496]	train-rmse:0.000744
[497]	train-rmse:0.000744
[498]	train-rmse:0.000744
[499]	train-rmse:0.000744
[500]	train-rmse:0.000744

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [38]:
xgb_mean_cl <- xgboost(data = dtrain_xg_mean_cl, nround=500, objective='multi:softmax',num_class=5)

[1]	train-merror:0.138686
[2]	train-merror:0.051095
[3]	train-merror:0.029197
[4]	train-merror:0.014599
[5]	train-merror:0.000000
[6]	train-merror:0.000000
[7]	train-merror:0.000000
[8]	train-merror:0.000000
[9]	train-merror:0.000000
[10]	train-merror:0.000000
[11]	train-merror:0.000000
[12]	train-merror:0.000000
[13]	train-merror:0.000000
[14]	train-merror:0.000000
[15]	train-merror:0.000000
[16]	train-merror:0.000000
[17]	train-merror:0.000000
[18]	train-merror:0.000000
[19]	train-merror:0.000000
[20]	train-merror:0.000000
[21]	train-merror:0.000000
[22]	train-merror:0.000000
[23]	train-merror:0.000000
[24]	train-merror:0.000000
[25]	train-merror:0.000000
[26]	train-merror:0.000000
[27]	train-merror:0.000000
[28]	train-merror:0.000000
[29]	train-merror:0.000000
[30]	train-merror:0.000000
[31]	train-merror:0.000000
[32]	train-merror:0.000000
[33]	train-merror:0.000000
[34]	train-merror:0.000000
[35]	train-merror:0.000000
[36]	train-merror:0.000000
[37]	train-merror:0.000000
[38]	train-merror:0.000000
[39]	train-merror:0.000000
[40]	train-merror:0.000000
[41]	train-merror:0.000000
[42]	train-merror:0.000000
[43]	train-merror:0.000000
[44]	train-merror:0.000000
[45]	train-merror:0.000000
[46]	train-merror:0.000000
[47]	train-merror:0.000000
[48]	train-merror:0.000000
[49]	train-merror:0.000000
[50]	train-merror:0.000000
[51]	train-merror:0.000000
[52]	train-merror:0.000000
[53]	train-merror:0.000000
[54]	train-merror:0.000000
[55]	train-merror:0.000000
[56]	train-merror:0.000000
[57]	train-merror:0.000000
[58]	train-merror:0.000000
[59]	train-merror:0.000000
[60]	train-merror:0.000000
[61]	train-merror:0.000000
[62]	train-merror:0.000000
[63]	train-merror:0.000000
[64]	train-merror:0.000000
[65]	train-merror:0.000000
[66]	train-merror:0.000000
[67]	train-merror:0.000000
[68]	train-merror:0.000000
[69]	train-merror:0.000000
[70]	train-merror:0.000000
[71]	train-merror:0.000000
[72]	train-merror:0.000000
[73]	train-merror:0.000000
[74]	train-merror:0.000000
[75]	train-merror:0.000000
[76]	train-merror:0.000000
[77]	train-merror:0.000000
[78]	train-merror:0.000000
[79]	train-merror:0.000000
[80]	train-merror:0.000000
[81]	train-merror:0.000000
[82]	train-merror:0.000000
[83]	train-merror:0.000000
[84]	train-merror:0.000000
[85]	train-merror:0.000000
[86]	train-merror:0.000000
[87]	train-merror:0.000000
[88]	train-merror:0.000000
[89]	train-merror:0.000000
[90]	train-merror:0.000000
[91]	train-merror:0.000000
[92]	train-merror:0.000000
[93]	train-merror:0.000000
[94]	train-merror:0.000000
[95]	train-merror:0.000000
[96]	train-merror:0.000000
[97]	train-merror:0.000000
[98]	train-merror:0.000000
[99]	train-merror:0.000000
[100]	train-merror:0.000000
[101]	train-merror:0.000000
[102]	train-merror:0.000000
[103]	train-merror:0.000000
[104]	train-merror:0.000000
[105]	train-merror:0.000000
[106]	train-merror:0.000000
[107]	train-merror:0.000000
[108]	train-merror:0.000000
[109]	train-merror:0.000000
[110]	train-merror:0.000000
[111]	train-merror:0.000000
[112]	train-merror:0.000000
[113]	train-merror:0.000000
[114]	train-merror:0.000000
[115]	train-merror:0.000000
[116]	train-merror:0.000000
[117]	train-merror:0.000000
[118]	train-merror:0.000000
[119]	train-merror:0.000000
[120]	train-merror:0.000000
[121]	train-merror:0.000000
[122]	train-merror:0.000000
[123]	train-merror:0.000000
[124]	train-merror:0.000000
[125]	train-merror:0.000000
[126]	train-merror:0.000000
[127]	train-merror:0.000000
[128]	train-merror:0.000000
[129]	train-merror:0.000000
[130]	train-merror:0.000000
[131]	train-merror:0.000000
[132]	train-merror:0.000000
[133]	train-merror:0.000000
[134]	train-merror:0.000000
[135]	train-merror:0.000000
[136]	train-merror:0.000000
[137]	train-merror:0.000000
[138]	train-merror:0.000000
[139]	train-merror:0.000000
[140]	train-merror:0.000000
[141]	train-merror:0.000000
[142]	train-merror:0.000000
[143]	train-merror:0.000000
[144]	train-merror:0.000000
[145]	train-merror:0.000000
[146]	train-merror:0.000000
[147]	train-merror:0.000000
[148]	train-merror:0.000000
[149]	train-merror:0.000000
[150]	train-merror:0.000000
[151]	train-merror:0.000000
[152]	train-merror:0.000000
[153]	train-merror:0.000000
[154]	train-merror:0.000000
[155]	train-merror:0.000000
[156]	train-merror:0.000000
[157]	train-merror:0.000000
[158]	train-merror:0.000000
[159]	train-merror:0.000000
[160]	train-merror:0.000000
[161]	train-merror:0.000000
[162]	train-merror:0.000000
[163]	train-merror:0.000000
[164]	train-merror:0.000000
[165]	train-merror:0.000000
[166]	train-merror:0.000000
[167]	train-merror:0.000000
[168]	train-merror:0.000000
[169]	train-merror:0.000000
[170]	train-merror:0.000000
[171]	train-merror:0.000000
[172]	train-merror:0.000000
[173]	train-merror:0.000000
[174]	train-merror:0.000000
[175]	train-merror:0.000000
[176]	train-merror:0.000000
[177]	train-merror:0.000000
[178]	train-merror:0.000000
[179]	train-merror:0.000000
[180]	train-merror:0.000000
[181]	train-merror:0.000000
[182]	train-merror:0.000000
[183]	train-merror:0.000000
[184]	train-merror:0.000000
[185]	train-merror:0.000000
[186]	train-merror:0.000000
[187]	train-merror:0.000000
[188]	train-merror:0.000000
[189]	train-merror:0.000000
[190]	train-merror:0.000000
[191]	train-merror:0.000000
[192]	train-merror:0.000000
[193]	train-merror:0.000000
[194]	train-merror:0.000000
[195]	train-merror:0.000000
[196]	train-merror:0.000000
[197]	train-merror:0.000000
[198]	train-merror:0.000000
[199]	train-merror:0.000000
[200]	train-merror:0.000000
[201]	train-merror:0.000000
[202]	train-merror:0.000000
[203]	train-merror:0.000000
[204]	train-merror:0.000000
[205]	train-merror:0.000000
[206]	train-merror:0.000000
[207]	train-merror:0.000000
[208]	train-merror:0.000000
[209]	train-merror:0.000000
[210]	train-merror:0.000000
[211]	train-merror:0.000000
[212]	train-merror:0.000000
[213]	train-merror:0.000000
[214]	train-merror:0.000000
[215]	train-merror:0.000000
[216]	train-merror:0.000000
[217]	train-merror:0.000000
[218]	train-merror:0.000000
[219]	train-merror:0.000000
[220]	train-merror:0.000000
[221]	train-merror:0.000000
[222]	train-merror:0.000000
[223]	train-merror:0.000000
[224]	train-merror:0.000000
[225]	train-merror:0.000000
[226]	train-merror:0.000000
[227]	train-merror:0.000000
[228]	train-merror:0.000000
[229]	train-merror:0.000000
[230]	train-merror:0.000000
[231]	train-merror:0.000000
[232]	train-merror:0.000000
[233]	train-merror:0.000000
[234]	train-merror:0.000000
[235]	train-merror:0.000000
[236]	train-merror:0.000000
[237]	train-merror:0.000000
[238]	train-merror:0.000000
[239]	train-merror:0.000000
[240]	train-merror:0.000000
[241]	train-merror:0.000000
[242]	train-merror:0.000000
[243]	train-merror:0.000000
[244]	train-merror:0.000000
[245]	train-merror:0.000000
[246]	train-merror:0.000000
[247]	train-merror:0.000000
[248]	train-merror:0.000000
[249]	train-merror:0.000000
[250]	train-merror:0.000000
[251]	train-merror:0.000000
[252]	train-merror:0.000000
[253]	train-merror:0.000000
[254]	train-merror:0.000000
[255]	train-merror:0.000000
[256]	train-merror:0.000000
[257]	train-merror:0.000000
[258]	train-merror:0.000000
[259]	train-merror:0.000000
[260]	train-merror:0.000000
[261]	train-merror:0.000000
[262]	train-merror:0.000000
[263]	train-merror:0.000000
[264]	train-merror:0.000000
[265]	train-merror:0.000000
[266]	train-merror:0.000000
[267]	train-merror:0.000000
[268]	train-merror:0.000000
[269]	train-merror:0.000000
[270]	train-merror:0.000000
[271]	train-merror:0.000000
[272]	train-merror:0.000000
[273]	train-merror:0.000000
[274]	train-merror:0.000000
[275]	train-merror:0.000000
[276]	train-merror:0.000000
[277]	train-merror:0.000000
[278]	train-merror:0.000000
[279]	train-merror:0.000000
[280]	train-merror:0.000000
[281]	train-merror:0.000000
[282]	train-merror:0.000000
[283]	train-merror:0.000000
[284]	train-merror:0.000000
[285]	train-merror:0.000000
[286]	train-merror:0.000000
[287]	train-merror:0.000000
[288]	train-merror:0.000000
[289]	train-merror:0.000000
[290]	train-merror:0.000000
[291]	train-merror:0.000000
[292]	train-merror:0.000000
[293]	train-merror:0.000000
[294]	train-merror:0.000000
[295]	train-merror:0.000000
[296]	train-merror:0.000000
[297]	train-merror:0.000000
[298]	train-merror:0.000000
[299]	train-merror:0.000000
[300]	train-merror:0.000000
[301]	train-merror:0.000000
[302]	train-merror:0.000000
[303]	train-merror:0.000000
[304]	train-merror:0.000000
[305]	train-merror:0.000000
[306]	train-merror:0.000000
[307]	train-merror:0.000000
[308]	train-merror:0.000000
[309]	train-merror:0.000000
[310]	train-merror:0.000000
[311]	train-merror:0.000000
[312]	train-merror:0.000000
[313]	train-merror:0.000000
[314]	train-merror:0.000000
[315]	train-merror:0.000000
[316]	train-merror:0.000000
[317]	train-merror:0.000000
[318]	train-merror:0.000000
[319]	train-merror:0.000000
[320]	train-merror:0.000000
[321]	train-merror:0.000000
[322]	train-merror:0.000000
[323]	train-merror:0.000000
[324]	train-merror:0.000000
[325]	train-merror:0.000000
[326]	train-merror:0.000000
[327]	train-merror:0.000000
[328]	train-merror:0.000000
[329]	train-merror:0.000000
[330]	train-merror:0.000000
[331]	train-merror:0.000000
[332]	train-merror:0.000000
[333]	train-merror:0.000000
[334]	train-merror:0.000000
[335]	train-merror:0.000000
[336]	train-merror:0.000000
[337]	train-merror:0.000000
[338]	train-merror:0.000000
[339]	train-merror:0.000000
[340]	train-merror:0.000000
[341]	train-merror:0.000000
[342]	train-merror:0.000000
[343]	train-merror:0.000000
[344]	train-merror:0.000000
[345]	train-merror:0.000000
[346]	train-merror:0.000000
[347]	train-merror:0.000000
[348]	train-merror:0.000000
[349]	train-merror:0.000000
[350]	train-merror:0.000000
[351]	train-merror:0.000000
[352]	train-merror:0.000000
[353]	train-merror:0.000000
[354]	train-merror:0.000000
[355]	train-merror:0.000000
[356]	train-merror:0.000000
[357]	train-merror:0.000000
[358]	train-merror:0.000000
[359]	train-merror:0.000000
[360]	train-merror:0.000000
[361]	train-merror:0.000000
[362]	train-merror:0.000000
[363]	train-merror:0.000000
[364]	train-merror:0.000000
[365]	train-merror:0.000000
[366]	train-merror:0.000000
[367]	train-merror:0.000000
[368]	train-merror:0.000000
[369]	train-merror:0.000000
[370]	train-merror:0.000000
[371]	train-merror:0.000000
[372]	train-merror:0.000000
[373]	train-merror:0.000000
[374]	train-merror:0.000000
[375]	train-merror:0.000000
[376]	train-merror:0.000000
[377]	train-merror:0.000000
[378]	train-merror:0.000000
[379]	train-merror:0.000000
[380]	train-merror:0.000000
[381]	train-merror:0.000000
[382]	train-merror:0.000000
[383]	train-merror:0.000000
[384]	train-merror:0.000000
[385]	train-merror:0.000000
[386]	train-merror:0.000000
[387]	train-merror:0.000000
[388]	train-merror:0.000000
[389]	train-merror:0.000000
[390]	train-merror:0.000000
[391]	train-merror:0.000000
[392]	train-merror:0.000000
[393]	train-merror:0.000000
[394]	train-merror:0.000000
[395]	train-merror:0.000000
[396]	train-merror:0.000000
[397]	train-merror:0.000000
[398]	train-merror:0.000000
[399]	train-merror:0.000000
[400]	train-merror:0.000000
[401]	train-merror:0.000000
[402]	train-merror:0.000000
[403]	train-merror:0.000000
[404]	train-merror:0.000000
[405]	train-merror:0.000000
[406]	train-merror:0.000000
[407]	train-merror:0.000000
[408]	train-merror:0.000000
[409]	train-merror:0.000000
[410]	train-merror:0.000000
[411]	train-merror:0.000000
[412]	train-merror:0.000000
[413]	train-merror:0.000000
[414]	train-merror:0.000000
[415]	train-merror:0.000000
[416]	train-merror:0.000000
[417]	train-merror:0.000000
[418]	train-merror:0.000000
[419]	train-merror:0.000000
[420]	train-merror:0.000000
[421]	train-merror:0.000000
[422]	train-merror:0.000000
[423]	train-merror:0.000000
[424]	train-merror:0.000000
[425]	train-merror:0.000000
[426]	train-merror:0.000000
[427]	train-merror:0.000000
[428]	train-merror:0.000000
[429]	train-merror:0.000000
[430]	train-merror:0.000000
[431]	train-merror:0.000000
[432]	train-merror:0.000000
[433]	train-merror:0.000000
[434]	train-merror:0.000000
[435]	train-merror:0.000000
[436]	train-merror:0.000000
[437]	train-merror:0.000000
[438]	train-merror:0.000000
[439]	train-merror:0.000000
[440]	train-merror:0.000000
[441]	train-merror:0.000000
[442]	train-merror:0.000000
[443]	train-merror:0.000000
[444]	train-merror:0.000000
[445]	train-merror:0.000000
[446]	train-merror:0.000000
[447]	train-merror:0.000000
[448]	train-merror:0.000000
[449]	train-merror:0.000000
[450]	train-merror:0.000000
[451]	train-merror:0.000000
[452]	train-merror:0.000000
[453]	train-merror:0.000000
[454]	train-merror:0.000000
[455]	train-merror:0.000000
[456]	train-merror:0.000000
[457]	train-merror:0.000000
[458]	train-merror:0.000000
[459]	train-merror:0.000000
[460]	train-merror:0.000000
[461]	train-merror:0.000000
[462]	train-merror:0.000000
[463]	train-merror:0.000000
[464]	train-merror:0.000000
[465]	train-merror:0.000000
[466]	train-merror:0.000000
[467]	train-merror:0.000000
[468]	train-merror:0.000000
[469]	train-merror:0.000000
[470]	train-merror:0.000000
[471]	train-merror:0.000000
[472]	train-merror:0.000000
[473]	train-merror:0.000000
[474]	train-merror:0.000000
[475]	train-merror:0.000000
[476]	train-merror:0.000000
[477]	train-merror:0.000000
[478]	train-merror:0.000000
[479]	train-merror:0.000000
[480]	train-merror:0.000000
[481]	train-merror:0.000000
[482]	train-merror:0.000000
[483]	train-merror:0.000000
[484]	train-merror:0.000000
[485]	train-merror:0.000000
[486]	train-merror:0.000000
[487]	train-merror:0.000000
[488]	train-merror:0.000000
[489]	train-merror:0.000000
[490]	train-merror:0.000000
[491]	train-merror:0.000000
[492]	train-merror:0.000000
[493]	train-merror:0.000000
[494]	train-merror:0.000000
[495]	train-merror:0.000000
[496]	train-merror:0.000000
[497]	train-merror:0.000000
[498]	train-merror:0.000000
[499]	train-merror:0.000000
[500]	train-merror:0.000000

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [39]:
lgb_mean_reg <- lgb.train(data = dtrain_lg_mean_reg,nrounds = 500)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004887 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 775
[LightGBM] [Info] Number of data points in the train set: 137, number of used features: 17
[LightGBM] [Info] Start training from score 2.094891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [40]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_mean_cl <- lgb.train(data = dtrain_lg_mean_cl,params=params,nrounds = 500)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005512 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 775
[LightGBM] [Info] Number of data points in the train set: 137, number of used features: 17
[LightGBM] [Info] Start training from score -1.423473
[LightGBM] [Info] Start training from score -1.924249
[LightGBM] [Info] Start training from score -1.828938
[LightGBM] [Info] Start training from score -1.701105
[LightGBM] [Info] Start training from score -1.309063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [41]:
end_time = Sys.time()
time_matrix[3,]=end_time-start_time

In [42]:
end_time-start_time

Time difference of 1.993198 mins

## predict

In [43]:
start_time = Sys.time()

In [44]:
alldatalgb <- lgb.Dataset(data = as.matrix(data))
alldataxgb <- xgb.DMatrix(data = as.matrix(data))

In [45]:
xgbregmin=predict(xgb_min_reg,alldataxgb)
xgbclsmin=predict(xgb_min_cl,alldataxgb)
lgbregmin=predict(lgb_min_reg,as.matrix(data))
lgbclsmin=predict(lgb_min_cl,as.matrix(data))

In [46]:
xgbregmin

  [1]  3.999790e+00  4.000044e+00  2.461423e+00  1.000031e+00  1.517344e+00
  [6]  1.038698e+00  8.636927e-01  1.000020e+00  8.026880e-01  2.003150e+00
 [11]  2.412664e+00  8.743667e-01  3.998688e+00  4.001712e+00  3.191036e+00
 [16]  4.325136e+00  3.001709e+00  3.999686e+00  1.999669e+00  2.096856e+00
 [21]  1.360732e+00  1.452837e+00  2.229420e+00  9.932319e-01  9.046938e-01
 [26] -6.973743e-06  1.813601e+00  1.975116e+00  1.566831e+00  9.122193e-04
 [31]  1.096935e+00  9.855031e-01  1.000154e+00  3.150064e-01  3.844066e-01
 [36]  6.858784e-01  3.999741e+00  4.273013e+00  2.427876e+00  2.999032e+00
 [41]  3.000411e+00  3.032185e+00  3.030865e+00  2.495029e+00  2.377814e+00
 [46]  4.009754e+00  3.078099e+00  2.744858e+00  4.000101e+00  4.000101e+00
 [51]  4.000012e+00  3.999837e+00  2.999696e+00  1.000818e+00  3.335005e+00
 [56]  3.999849e+00  2.000757e+00  7.906258e-04  1.553507e-01  9.998122e-01
 [61]  2.756338e+00  2.333839e+00  2.013849e+00  3.996022e+00  3.938352e+00
 [66]  3.000802e+00  2.809384e+00  2.188851e+00  1.999489e+00  3.050325e-01
 [71]  2.440184e-02  2.939105e-04 -1.010931e-02  3.374770e+00  3.275003e+00
 [76]  2.405354e+00  1.478758e+00  2.028962e+00  1.426172e+00  2.999947e+00
 [81]  3.708298e+00  3.255411e+00  3.182873e+00  3.227401e+00  2.999059e+00
 [86]  3.857224e+00  1.599663e+00  4.000022e+00  1.000228e+00  2.699595e+00
 [91]  3.805874e+00  3.999697e+00  3.000498e+00  2.229929e+00  1.646646e+00
 [96]  3.998850e+00  1.007130e+00  1.999260e+00  3.999871e+00  2.825104e+00
[101] -1.087189e-03  4.000979e+00  3.000358e+00  5.956888e-04  3.696776e+00
[106]  3.041350e+00  3.111183e+00  3.747866e+00  3.999725e+00  3.963427e+00
[111]  1.599663e+00  3.775877e+00  3.000482e+00  2.000179e+00  3.755990e+00
[116]  3.999479e+00  3.604801e+00  2.748360e+00  1.874238e-03  1.011245e+00
[121]  2.000731e+00  7.493496e-04  1.052424e+00  4.243595e+00  2.999122e+00
[126]  1.379758e-03  3.668120e+00  3.945959e+00 -2.841055e-03  1.000531e+00
[131]  2.999820e+00  3.334704e+00  2.876829e+00  2.760663e+00  3.669433e+00
[136]  3.999785e+00  3.866132e+00  2.999290e+00  2.617820e+00  2.899951e+00
[141]  3.841743e+00  3.999851e+00  3.000275e+00  3.424150e+00  3.000455e+00
[146]  3.392110e+00  6.326160e-01  1.800358e-04  4.000108e+00  2.999924e+00
[151]  3.779698e+00  3.866991e+00  3.998500e+00  2.000254e+00  2.733846e+00
[156]  2.401229e+00  2.240493e+00  3.308062e+00  3.999508e+00  3.930691e+00
[161]  3.011366e+00  3.454726e+00  1.841725e+00  3.998498e+00 -3.064275e-04
[166]  2.291203e-04  9.295046e-04  3.892838e+00  3.667532e+00  3.538883e+00
[171]  3.552156e+00  2.198707e+00  6.222549e-01  3.413951e+00  2.901889e+00
[176]  4.001660e+00  2.245202e+00  3.389700e+00  2.911957e+00  3.486036e+00
[181]  2.001121e+00  1.817104e+00  2.871500e+00  3.691007e+00  2.999985e+00
[186]  3.998400e+00  2.000769e+00  2.000220e+00  3.999608e+00  2.039845e+00
[191]  1.886918e+00  2.467196e+00  3.000140e+00  1.737398e+00  2.714002e+00
[196]  3.998864e+00  2.000431e+00  3.858430e+00  2.999908e+00  2.282202e+00
[201]  3.000121e+00  2.965866e+00  3.084669e+00  2.601964e+00  3.999404e+00
[206]  3.018279e+00  2.970860e+00  3.296680e+00  4.000641e+00  3.369107e+00
[211]  3.999064e+00  2.940515e+00  1.999711e+00  2.999687e+00  3.999139e+00
[216]  3.920789e+00  1.825840e+00  1.966160e+00  1.636472e+00  4.000229e+00
[221]  3.362664e+00  3.291262e+00  3.394128e+00  1.766617e+00  6.790161e-04
[226]  2.062305e+00  9.993039e-01  1.653403e-03 -6.459951e-04  1.999389e+00
[231]  1.457929e+00  2.000788e+00  2.526332e+00  9.464124e-01  9.999598e-01
[236]  1.999829e+00  3.998960e+00  1.899347e+00  1.744686e+00  1.856166e+00
[241]  9.998187e-01  1.553252e+00  1.460041e+00  5.357876e-01  1.000640e+00
[246]  4.718533e-01  1.846090e+00  3.999677e+00  4.000442e+00  3.999295e+00
[251]  2.999949e+00  3.054992e+00  3.999641e+00  3.999992e+00  2.214751e+00
[256]  3.221290e+00  2.000184e+00  1.999730e+00  3.598310e+00  2.038478e-01
[261]  3.999747e+00  3.324853e+00  3.997460e+00  8.807114e-02  1.488182e+00
[266]  2.012387e+00  3.474355e-04  3.998506e+00  6.820314e-01  2.555743e+00
[271]  2.883621e+00  3.754941e+00  3.234668e+00  4.000177e+00  2.452768e+00
[276]  2.238858e+00  1.664716e+00  4.000214e+00  2.778678e+00  2.001741e+00
[281]  3.997687e+00  1.999159e+00  5.442202e-04  2.999469e+00  2.686506e+00
[286]  4.227228e+00  3.307478e+00  3.839328e+00  4.000173e+00  4.000522e+00
[291]  3.999692e+00  4.041597e+00  1.999376e+00  1.635806e+00  1.485795e-03
[296]  3.999930e+00  3.096635e+00  3.254509e+00  2.874543e+00  2.954255e+00
[301]  2.237666e+00  3.497233e+00  2.454446e+00  2.628014e+00  3.176026e+00
[306]  2.329841e+00  3.178082e+00  2.415243e+00  3.180906e+00  7.633083e-01
[311]  2.999668e+00  2.727372e+00  3.455955e+00  2.920433e+00  2.217935e+00
[316]  2.607052e+00  9.459090e-01  1.316890e+00  2.920453e+00  2.824794e+00
[321]  2.514793e+00  3.017505e+00  2.363758e+00  2.603565e+00  3.595047e+00
[326]  2.481920e+00  2.789027e+00  2.575571e+00  3.716956e+00  3.566556e+00
[331]  3.999894e+00  2.999225e+00  3.142969e+00  3.872638e+00  3.000312e+00
[336]  2.001049e+00  2.504937e+00  2.999906e+00  2.825764e+00  2.647871e+00
[341]  3.217008e+00  2.795091e+00  3.241595e+00  1.999887e+00  1.550894e+00
[346]  3.998928e+00  2.986189e+00  2.237756e+00  1.280989e+00  1.307568e+00
[351]  2.000942e+00  2.433658e-04  3.378119e+00  2.999614e+00  1.000611e+00
[356]  2.999875e+00  3.365415e+00  3.998277e+00  2.383744e+00

In [47]:
xgbclsmin

  [1] 4 4 3 1 4 4 2 1 1 2 3 0 4 4 4 4 3 4 2 4 2 4 4 2 1 0 2 3 0 0 0 1 1 3 0 0 4
 [38] 4 3 3 3 3 3 3 2 4 3 2 4 4 4 4 3 1 3 4 2 0 0 1 4 2 4 4 4 3 4 2 2 2 0 0 0 4
 [75] 4 3 3 4 3 3 4 4 3 4 3 3 4 4 1 3 4 4 3 0 0 4 3 2 4 3 0 4 3 0 4 3 4 4 4 4 4
[112] 4 3 2 4 4 4 3 0 0 2 0 2 4 3 0 4 4 0 1 3 4 4 4 4 4 4 3 2 2 4 4 3 3 3 4 0 0
[149] 4 3 4 4 4 2 2 1 3 4 4 4 3 4 4 4 0 0 0 4 4 4 4 4 0 4 4 4 1 4 4 4 2 4 4 4 3
[186] 4 2 2 4 3 3 3 3 3 3 4 2 4 3 3 3 3 3 3 4 3 3 4 4 4 4 2 2 3 4 4 2 2 1 4 3 4
[223] 4 3 0 4 1 0 0 2 0 2 4 2 1 2 4 2 4 3 1 3 2 0 1 1 0 4 4 4 3 3 4 4 2 4 2 2 3
[260] 0 4 3 4 4 0 0 0 4 4 3 3 4 4 4 4 4 2 4 3 2 4 2 0 3 4 4 3 4 4 4 4 4 2 1 0 4
[297] 3 4 2 3 4 4 4 3 3 4 3 4 4 2 3 3 3 3 3 4 3 3 3 4 3 3 3 4 4 3 4 2 4 4 4 3 4
[334] 4 3 2 3 3 2 3 4 4 4 2 4 4 3 3 4 3 2 0 3 3 1 3 4 4 4

In [48]:
lgbregmin

  [1]  4.08094042  3.98200270  3.17526746  0.94374156  1.31342575  2.42129688
  [7]  1.55393031  0.93843847  0.56528517  2.05334350  3.03517603  1.65287101
 [13]  3.97311659  4.07254470  2.17644718  4.65518960  3.11412940  3.96185422
 [19]  1.91161425  2.57916842  1.63618343  1.62582650  2.47829296  1.73251001
 [25]  1.17284525  0.09056126  0.79999392  1.47973572  1.62069237  0.16247369
 [31]  0.03216223 -0.16642604  0.99580685  1.33276918  1.07571072  1.01364820
 [37]  3.97426974  4.44652117  3.06012361  2.83471454  3.09390695  3.05277065
 [43]  3.07471368  2.93761912  1.76972211  4.11398541  2.17128176  2.24540342
 [49]  4.00358675  4.00057959  4.00092523  3.98232580  2.95144556  1.12823473
 [55]  2.57611958  3.91734628  2.05854902  0.07404203  1.75876389  0.98660346
 [61]  2.36973961  2.13499915  3.10397347  3.35781261  3.62934991  3.03458051
 [67]  2.71211234  2.61416244  1.90274862  1.09173687  0.23411965  0.03135112
 [73] -0.05854094  1.82065132  3.29720517  2.92093196  1.22293112  2.58696468
 [79]  1.49155504  2.92851243  3.57234821  3.20509948  3.11091470  3.54987760
 [85]  2.93074441  4.11831202  3.27690758  3.99467254  0.99961601  3.05441193
 [91]  3.21463865  4.06543968  3.04586435  1.17564057  2.28037276  3.91746548
 [97]  0.71416836  1.85481215  3.71892826  3.08331374  0.05646766  4.02444957
[103]  3.01829066  0.07695276  2.36523537  3.01060856  2.59939109  3.95111437
[109]  3.88744095  4.80754843  3.27690758  2.99747559  3.02919327  1.85580871
[115]  3.25666735  3.91092968  3.91755881  2.78237171  0.21950904  2.84967060
[121]  2.10412470  0.13186591  1.41953899  3.91021018  2.93759921 -0.02020734
[127]  3.23730335  4.30352135  0.16900602  1.26317907  2.96670109  2.97263048
[133]  2.38968465  2.37064814  4.43522582  3.97600188  2.96933055  3.02449552
[139]  3.13441922  1.50128569  3.30885400  4.02747701  3.01947347  3.90951769
[145]  3.02878254  3.06252208  0.98191648 -0.01303285  3.99459331  3.05360695
[151]  3.83062359  3.46787190  3.92391882  2.11430888  2.38307772  1.41024873
[157]  2.68532777  2.56381832  4.11865741  3.86166926  2.98477000  3.67345513
[163]  2.34204101  3.92516560  0.06899996  0.02243592  0.22047066  3.45851030
[169]  3.64422433  3.54784113  3.39397093  3.47596711  1.01493353  3.29852625
[175]  2.15509107  4.04674344  2.25484967  1.08230790  2.62470758  3.21367336
[181]  2.13551938  3.15913366  2.16081115  2.77161055  2.84427166  3.97873270
[187]  2.08548978  1.98874215  3.99418229  2.45547970  2.56886606  3.22111085
[193]  2.98778392  0.58296824  2.86869043  3.98901317  2.06364406  3.19102436
[199]  2.92425263  1.34658939  2.97388789  3.08794970  2.76259703  2.89783390
[205]  3.95153104  2.55531619  3.95454278  2.65068306  4.04426660  2.35492990
[211]  3.97645408  2.58491426  2.06198880  3.00689482  3.89349868  3.77680314
[217]  1.48481384  1.87275177  3.00375490  4.04414324  3.75628521  2.72643529
[223]  3.89115315  1.57853641  0.12384252  2.27823350  1.00021656  0.14811583
[229] -0.04137028  1.98294609  1.09518691  2.10302478  2.75415000  0.89639610
[235]  0.95334618  1.94506025  3.94152971  2.82068462  1.81541368  2.42330089
[241]  0.86341815  2.40843462  1.34786914  0.20419780  1.04530579  0.02144835
[247]  0.37720299  4.03334426  3.95512443  3.96321929  2.94983007  2.68436567
[253]  3.96322447  3.98163968  2.63699963  3.90374485  2.02604447  1.99539545
[259]  2.57725095  0.82395237  3.93205421  2.32303916  3.70957348  1.02009117
[265]  1.49916295  1.51448237  0.10375053  3.79082812  1.76942732  2.80972987
[271]  2.91315716  3.38099570  3.69945221  3.89924648  3.30577186  2.33422941
[277]  1.38628197  4.03217602  2.86862270  2.02691212  3.89157037  1.88108978
[283]  0.10586786  2.99836838  4.05320657  3.07022398  3.44608341  3.71159750
[289]  3.95350109  4.00608000  3.99851552  3.90901208  1.95159454  1.48839077
[295]  0.28950894  3.96610401  3.46594086  3.58513200  2.30623862  2.56266117
[301]  2.41612565  3.95669024  3.04387676  2.80975150  2.95181256  2.42964984
[307]  3.03044746  2.68676047  3.42436733  1.38758341  2.91024840  2.36658060
[313]  3.38939233  2.37194903  2.41915701  2.81963889  1.27206379  3.89488844
[319]  2.73204759  3.31605987  2.87610612  2.60875059  1.57935433  3.34230617
[325]  3.04290625  2.56020173  3.24895624  2.35468503  4.11473759  3.90781018
[331]  3.90375389  2.95492572  3.36011953  3.25407500  3.08876411  2.26368093
[337]  2.16966680  2.84025563  3.13428003  2.17857716  3.96699378  3.54201823
[343]  3.40372843  2.18015704  2.29605619  3.95704374  3.06073725  2.50410436
[349]  1.78502630  2.10366822  2.10334931  0.02828100  3.05663901  2.66322603
[355]  0.94046252  3.12987144  3.36643217  3.89544786  2.00964774

In [49]:
lgbclsmin

      [,1]         [,2]         [,3]         [,4]         [,5]
 [1,] 2.451516e-07 1.122478e-08 7.671836e-07 1.130175e-06 9.999978e-01
 [2,] 1.976005e-07 4.757265e-08 1.079353e-07 2.640691e-05 9.999732e-01
 [3,] 9.573086e-04 1.964570e-05 1.971077e-05 9.813689e-01 1.763444e-02
 [4,] 1.981848e-05 9.999791e-01 1.064182e-06 2.597846e-08 3.196668e-08
 [5,] 3.384949e-01 4.624901e-01 4.548924e-04 2.242255e-09 1.985601e-01
 [6,] 2.469650e-02 4.074564e-06 3.157445e-04 2.156642e-10 9.749837e-01
 [7,] 1.487031e-03 5.339253e-02 9.340553e-01 3.070061e-03 7.995083e-03
 [8,] 8.971598e-06 9.999734e-01 1.742311e-05 2.337754e-07 5.226801e-11
 [9,] 2.084093e-03 9.978432e-01 9.099267e-09 7.274493e-05 6.147425e-10
[10,] 6.337980e-11 1.327372e-10 9.999593e-01 2.140961e-08 4.071347e-05
[11,] 5.789156e-04 8.875320e-02 5.449030e-07 9.102283e-01 4.390041e-04
[12,] 9.942599e-01 1.293677e-05 3.338225e-07 5.592947e-03 1.338757e-04
[13,] 4.947759e-08 2.345864e-10 3.804207e-07 1.864971e-05 9.999809e-01
[14,] 8.034171e-10 6.061400e-13 4.221106e-10 1.303626e-08 1.000000e+00
[15,] 1.565686e-03 1.795043e-06 3.199376e-05 2.121288e-05 9.983793e-01
[16,] 1.705154e-09 5.237883e-11 2.565966e-08 3.642219e-12 1.000000e+00
[17,] 4.455120e-10 4.781545e-10 3.294725e-06 9.999153e-01 8.138039e-05
[18,] 2.278064e-06 2.328832e-06 2.363512e-05 3.096398e-05 9.999408e-01
[19,] 3.242447e-05 1.308118e-05 9.999342e-01 9.469930e-07 1.931852e-05
[20,] 8.789207e-06 9.026639e-06 6.498851e-01 8.920719e-09 3.500970e-01
[21,] 5.060689e-05 5.554624e-05 9.997047e-01 4.380941e-09 1.891044e-04
[22,] 1.571870e-02 7.840988e-01 3.259973e-03 1.521456e-01 4.477692e-02
[23,] 2.094624e-06 6.477284e-06 5.565851e-01 1.981285e-09 4.434063e-01
[24,] 1.991398e-05 4.932687e-04 9.930449e-01 1.977828e-03 4.464049e-03
[25,] 4.865854e-02 9.506672e-01 6.390037e-04 1.811847e-07 3.511373e-05
[26,] 9.999629e-01 3.469612e-06 3.364576e-05 1.955839e-10 3.335057e-08
[27,] 2.870069e-01 2.319147e-04 6.054630e-02 6.301699e-01 2.204505e-02
[28,] 3.756855e-03 1.798645e-05 6.012096e-03 9.857931e-01 4.419973e-03
[29,] 7.980999e-01 1.807107e-01 6.825590e-04 1.568873e-08 2.050676e-02
[30,] 9.999556e-01 9.851813e-08 1.567133e-07 2.200594e-07 4.394173e-05
[31,] ⋮            ⋮            ⋮            ⋮            ⋮
[32,] 1.447501e-06 1.076223e-06 1.011213e-05 6.734241e-06 9.999806e-01
[33,] 6.879676e-06 2.615042e-06 1.748244e-05 1.406538e-05 9.999590e-01
[34,] 8.880490e-07 8.272656e-08 5.526243e-06 9.999928e-01 7.125507e-07
[35,] 2.411836e-04 5.000706e-04 6.035238e-05 2.396561e-03 9.968018e-01
[36,] 6.751742e-06 5.205707e-05 2.496070e-05 1.104967e-05 9.999052e-01
[37,] 2.322500e-07 2.386891e-06 1.405796e-06 9.999926e-01 3.372168e-06
[38,] 1.327919e-05 4.889930e-06 9.999089e-01 1.178139e-05 6.116022e-05
[39,] 2.929237e-03 7.625599e-03 6.564942e-01 3.104664e-01 2.248459e-02
[40,] 8.094918e-07 5.370299e-06 3.510979e-05 9.999172e-01 4.155879e-05
[41,] 3.521854e-04 7.249725e-03 7.795185e-01 2.236321e-02 1.905164e-01
[42,] 4.134207e-06 1.639044e-04 6.161764e-03 9.936365e-01 3.374616e-05
[43,] 2.174735e-06 2.528914e-05 5.244816e-06 2.649455e-03 9.973178e-01
[44,] 5.068268e-05 4.610630e-05 2.102276e-06 1.971883e-04 9.997039e-01
[45,] 1.461985e-03 1.705454e-04 1.670114e-04 6.376087e-04 9.975628e-01
[46,] 9.160071e-07 2.626035e-06 9.999541e-01 3.074933e-05 1.162101e-05
[47,] 1.606943e-04 3.896369e-04 4.834165e-01 3.927947e-01 1.232384e-01
[48,] 1.543641e-06 7.977099e-06 1.155423e-05 4.534653e-11 9.999789e-01
[49,] 5.110707e-04 1.891959e-05 1.416714e-05 9.985474e-01 9.084540e-04
[50,] 2.008151e-04 9.552374e-06 3.272601e-06 9.997785e-01 7.850842e-06
[51,] 1.748541e-01 9.582974e-03 2.526507e-05 2.947150e-03 8.125905e-01
[52,] 9.346414e-02 1.139920e-04 2.871343e-06 9.062222e-01 1.967692e-04
[53,] 1.748692e-06 1.475786e-05 9.999120e-01 5.544074e-05 1.603327e-05
[54,] 9.999718e-01 8.357387e-07 7.959306e-10 5.480469e-10 2.736927e-05
[55,] 4.394387e-05 1.433756e-04 7.479815e-06 9.149235e-04 9.988903e-01
[56,] 3.079569e-05 3.661548e-07 1.843812e-05 9.999420e-01 8.402975e-06
[57,] 4.127898e-05 9.999266e-01 4.712691e-07 2.494112e-08 3.160846e-05
[58,] 1.447859e-07 2.888253e-06 1.846216e-05 9.999199e-01 5.857178e-05
[59,] 1.068271e-04 1.497825e-04 1.018491e-04 2.643587e-05 9.996151e-01
[60,] 2.435458e-06 3.649260e-06 6.595443e-06 8.013023e-05 9.999072e-01
[61,] 3.103571e-03 2.037505e-03 3.937032e-01 6.229532e-04 6.005328e-01

In [50]:
datalength=dim(data)[1]
lgbclsm=matrix(lgbclsmin,m,datalength)
lgbclsminr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsminr[i,]=which.max(lgbclsm[,i])
}
lgbclsminr=lgbclsminr-1

In [51]:
lgbclsminr

      [,1]
 [1,] 4
 [2,] 0
 [3,] 1
 [4,] 3
 [5,] 4
 [6,] 0
 [7,] 0
 [8,] 0
 [9,] 1
[10,] 1
[11,] 4
[12,] 2
[13,] 2
[14,] 4
[15,] 2
[16,] 1
[17,] 2
[18,] 1
[19,] 4
[20,] 1
[21,] 0
[22,] 1
[23,] 0
[24,] 3
[25,] 1
[26,] 0
[27,] 2
[28,] 4
[29,] 3
[30,] 2
[31,] ⋮
[32,] 1
[33,] 0
[34,] 3
[35,] 1
[36,] 3
[37,] 2
[38,] 3
[39,] 3
[40,] 0
[41,] 1
[42,] 1
[43,] 3
[44,] 4
[45,] 3
[46,] 1
[47,] 1
[48,] 2
[49,] 1
[50,] 2
[51,] 4
[52,] 2
[53,] 3
[54,] 0
[55,] 0
[56,] 0
[57,] 4
[58,] 2
[59,] 1
[60,] 3
[61,] 3

In [52]:
xgbregmean=predict(xgb_mean_reg,alldataxgb)
xgbclsmean=predict(xgb_mean_cl,alldataxgb)
lgbregmean=predict(lgb_mean_reg,as.matrix(data))
lgbclsmean=predict(lgb_mean_cl,as.matrix(data))

In [53]:
lgbclsm=matrix(lgbclsmean,m,datalength)
lgbclsmeanr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsmeanr[i,]=which.max(lgbclsm[,i])
}
lgbclsmeanr=lgbclsmeanr-1

In [54]:
preallmin=cbind(xgbclsmin,xgbregmin)
preallmin=cbind(preallmin,lgbclsminr)
preallmin=cbind(preallmin,lgbregmin)

In [55]:
colnames(preallmin)=c('xgbclsmin','xgbregmin','lgbclsmin','lgbregmin')
head(preallmin)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 4         3.999790  4         4.0809404
[2,] 4         4.000044  0         3.9820027
[3,] 3         2.461423  1         3.1752675
[4,] 1         1.000031  3         0.9437416
[5,] 4         1.517344  4         1.3134258
[6,] 4         1.038698  0         2.4212969

In [56]:
preallmean=cbind(xgbclsmean,xgbregmean)
preallmean=cbind(preallmean,lgbclsmeanr)
preallmean=cbind(preallmean,lgbregmean)

In [57]:
head(preallmean)

     xgbclsmean xgbregmean   lgbregmean
[1,] 4          3.9992321  4  4.0544632
[2,] 4          3.9998746  0  4.0330911
[3,] 4          1.4142292  1  3.3061475
[4,] 1          0.9998934  3  1.0050613
[5,] 0          0.3454669  0 -0.1948324
[6,] 0          1.4086787  4  1.5244908

In [58]:
colnames(preallmean)=c('xgbclsmean','xgbregmean','lgbclsmean','lgbregmean')
head(preallmean)

     xgbclsmean xgbregmean lgbclsmean lgbregmean
[1,] 4          3.9992321  4           4.0544632
[2,] 4          3.9998746  0           4.0330911
[3,] 4          1.4142292  1           3.3061475
[4,] 1          0.9998934  3           1.0050613
[5,] 0          0.3454669  0          -0.1948324
[6,] 0          1.4086787  4           1.5244908

In [59]:
end_time = Sys.time()
time_matrix[4,]=end_time-start_time

In [60]:
result_list=list(preallmin,preallmean,time_matrix)

In [66]:
save(result_list, file = "Weekly_FForma_opt_pre_result.RData")

In [58]:
time_matrix

     user_time system_time elapsed_time
[1,] 4.6199644 4.6199644   4.6199644
[2,] 3.5019691 3.5019691   3.5019691
[3,] 2.8674052 2.8674052   2.8674052
[4,] 0.8890216 0.8890216   0.8890216

In [61]:
nnetarl=load('Weekly_FForma_datatestlist.RData')
nnetar_datalist <- eval(parse(text = nnetarl))

In [62]:
nnetar_predh=nnetar_datalist[[2]]
nnetar_pred_res=nnetar_datalist[[1]]

In [63]:
MASE=nnetar_pred_res[,,,6]
m=5

In [64]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [65]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [66]:
sum(lgbclsmeanr[index==3]==realbestmean)/length(realbestmean)

[1] 0.2280702

In [67]:
mean(abs(lgbclsmeanr[index==3] -realbestmean))

[1] 1.508772