In [1]:
library("xgboost")
library("Matrix")
library('Ckmeans.1d.dp')
library('lightgbm')

载入程辑包：‘lightgbm’


The following object is masked from ‘package:xgboost’:

    slice

## Read data and process data labels

In [2]:
time_matrix <- matrix(0,ncol = 3, nrow =4)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [3]:
data=read.csv('Hourly_features_matrix.csv')
data=data[,2:dim(data)[2]]

In [4]:
dim(data)

[1] 414  27

In [5]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 24        1        24              0.8512223 4.041507e-09  5.3506983
2 24        1        24              0.9194922 2.449422e-09  8.2809591
3 24        1        24              0.9079559 3.241234e-09 -9.0028041
4 24        1        24              0.8712692 2.010702e-09  0.7677543
5 24        1        24              0.8801393 3.844576e-09 -0.0186239
6 24        1        24              0.8551463 3.051179e-09 -2.8143809
  curvature e_acf1    e_acf10  seasonal_strength ⋯ diff2_acf1 diff2_acf10
1 -3.435885 0.8957711 2.150024 0.9766084         ⋯ 0.09813614 0.1914053
2 -1.146953 0.9141691 2.554141 0.9728383         ⋯ 0.08323323 0.1945535
3  1.658264 0.9086270 2.440903 0.9656292         ⋯ 0.05203444 0.1276246
4  2.701202 0.9187827 2.040658 0.9830436         ⋯ 0.44839902 0.7087884
5  5.952095 0.9412170 2.951870 0.9634139         ⋯ 0.45128188 0.6560024
6  2.642106 0.8964147 2.388106 0.9742814         ⋯ 0.18178351 0.2069934
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.8944637 700    0.02403760 0.02403760  0.02403760   0
2 0.9155878 700    0.02337670 0.02337670  0.02337670   0
3 0.8720262 700    0.02334857 0.02334857  0.02334857   0
4 0.9048109 700    0.02348685 0.02348685  0.02348685   0
5 0.8393581 700    0.02346539 0.02346539  0.02346539   0
6 0.8804445 700    0.06628799 0.06628799  0.06628799   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [6]:
dlist= load('Hourly_nnetar_datalist.RData')
datalist=eval(parse(text = dlist ))
res=datalist[[1]]
MASE=res[,,,6]
m=5

In [7]:
dim(MASE)

[1] 414   5   4

In [8]:
whichmin<-function(x){
    minx=min(x[x>0])
    loc=which(x==minx)[1]-1
    loc
}

meanunique=function(x)
    {
    mean(unique(x))
}

In [9]:
nanum=c()
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    a=apply(count,1,min)
    if(sum(is.na(a))>0)
        {
        nanum=append(nanum,i)
    }
    }

In [10]:
nanum

NULL

In [11]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [12]:
table(realbestmin)

realbestmin
  0   1   2   3   4
100  66  59  70 119

In [13]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [14]:
realbestmean

      [,1]
 [1,] 2
 [2,] 1
 [3,] 1
 [4,] 4
 [5,] 1
 [6,] 0
 [7,] 4
 [8,] 1
 [9,] 1
[10,] 0
[11,] 4
[12,] 1
[13,] 4
[14,] 0
[15,] 1
[16,] 4
[17,] 3
[18,] 1
[19,] 0
[20,] 1
[21,] 2
[22,] 4
[23,] 0
[24,] 3
[25,] 0
[26,] 4
[27,] 0
[28,] 3
[29,] 2
[30,] 2
[31,] ⋮
[32,] 2
[33,] 0
[34,] 1
[35,] 0
[36,] 0
[37,] 2
[38,] 2
[39,] 0
[40,] 0
[41,] 0
[42,] 2
[43,] 0
[44,] 0
[45,] 0
[46,] 3
[47,] 4
[48,] 1
[49,] 0
[50,] 4
[51,] 1
[52,] 1
[53,] 1
[54,] 3
[55,] 3
[56,] 1
[57,] 3
[58,] 0
[59,] 2
[60,] 0
[61,] 1

In [15]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 24        1        24              0.8512223 4.041507e-09  5.3506983
2 24        1        24              0.9194922 2.449422e-09  8.2809591
3 24        1        24              0.9079559 3.241234e-09 -9.0028041
4 24        1        24              0.8712692 2.010702e-09  0.7677543
5 24        1        24              0.8801393 3.844576e-09 -0.0186239
6 24        1        24              0.8551463 3.051179e-09 -2.8143809
  curvature e_acf1    e_acf10  seasonal_strength ⋯ diff2_acf1 diff2_acf10
1 -3.435885 0.8957711 2.150024 0.9766084         ⋯ 0.09813614 0.1914053
2 -1.146953 0.9141691 2.554141 0.9728383         ⋯ 0.08323323 0.1945535
3  1.658264 0.9086270 2.440903 0.9656292         ⋯ 0.05203444 0.1276246
4  2.701202 0.9187827 2.040658 0.9830436         ⋯ 0.44839902 0.7087884
5  5.952095 0.9412170 2.951870 0.9634139         ⋯ 0.45128188 0.6560024
6  2.642106 0.8964147 2.388106 0.9742814         ⋯ 0.18178351 0.2069934
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.8944637 700    0.02403760 0.02403760  0.02403760   0
2 0.9155878 700    0.02337670 0.02337670  0.02337670   0
3 0.8720262 700    0.02334857 0.02334857  0.02334857   0
4 0.9048109 700    0.02348685 0.02348685  0.02348685   0
5 0.8393581 700    0.02346539 0.02346539  0.02346539   0
6 0.8804445 700    0.06628799 0.06628799  0.06628799   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [16]:
set.seed(100)
index = sample(2,nrow(data),replace = TRUE,prob=c(0.7,0.3))

In [17]:
train_data=data[index==1,]
test_data=data[index==2,]
train_label_min=realbestmin[index==1,]
test_label_min=realbestmin[index==2,]
train_label_mean=realbestmean[index==1,]
test_label_mean=realbestmean[index==2,]

In [18]:
head(train_data)

  frequency nperiods seasonal_period trend     spike        linearity
1 24        1        24              0.8512223 4.041507e-09  5.3506983
2 24        1        24              0.9194922 2.449422e-09  8.2809591
3 24        1        24              0.9079559 3.241234e-09 -9.0028041
4 24        1        24              0.8712692 2.010702e-09  0.7677543
5 24        1        24              0.8801393 3.844576e-09 -0.0186239
6 24        1        24              0.8551463 3.051179e-09 -2.8143809
  curvature e_acf1    e_acf10  seasonal_strength ⋯ diff2_acf1 diff2_acf10
1 -3.435885 0.8957711 2.150024 0.9766084         ⋯ 0.09813614 0.1914053
2 -1.146953 0.9141691 2.554141 0.9728383         ⋯ 0.08323323 0.1945535
3  1.658264 0.9086270 2.440903 0.9656292         ⋯ 0.05203444 0.1276246
4  2.701202 0.9187827 2.040658 0.9830436         ⋯ 0.44839902 0.7087884
5  5.952095 0.9412170 2.951870 0.9634139         ⋯ 0.45128188 0.6560024
6  2.642106 0.8964147 2.388106 0.9742814         ⋯ 0.18178351 0.2069934
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.8944637 700    0.02403760 0.02403760  0.02403760   0
2 0.9155878 700    0.02337670 0.02337670  0.02337670   0
3 0.8720262 700    0.02334857 0.02334857  0.02334857   0
4 0.9048109 700    0.02348685 0.02348685  0.02348685   0
5 0.8393581 700    0.02346539 0.02346539  0.02346539   0
6 0.8804445 700    0.06628799 0.06628799  0.06628799   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [19]:
end_time = Sys.time()

In [20]:
time_matrix[1,]=end_time-start_time

In [21]:
end_time-start_time

Time difference of 7.430921 secs

## Target the interval where the actual error is minimum

In [22]:
start_time = Sys.time()

In [23]:
dtrain_xg_min_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_min)) 
dtrain_xg_min_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)) )

In [24]:
dtrain_lg_min_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_min))
dtrain_lg_min_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)))

In [25]:
xgb_min_reg <- xgboost(data = dtrain_xg_min_reg, nround=100)

[1]	train-rmse:1.754079
[2]	train-rmse:1.426518
[3]	train-rmse:1.189110
[4]	train-rmse:1.028226
[5]	train-rmse:0.915751
[6]	train-rmse:0.836870
[7]	train-rmse:0.759872
[8]	train-rmse:0.694982
[9]	train-rmse:0.640896
[10]	train-rmse:0.599680
[11]	train-rmse:0.537154
[12]	train-rmse:0.475537
[13]	train-rmse:0.427245
[14]	train-rmse:0.394142
[15]	train-rmse:0.365099
[16]	train-rmse:0.328297
[17]	train-rmse:0.309963
[18]	train-rmse:0.299233
[19]	train-rmse:0.266722
[20]	train-rmse:0.253993
[21]	train-rmse:0.241670
[22]	train-rmse:0.220850
[23]	train-rmse:0.209880
[24]	train-rmse:0.201576
[25]	train-rmse:0.190691
[26]	train-rmse:0.182536
[27]	train-rmse:0.172621
[28]	train-rmse:0.162848
[29]	train-rmse:0.149969
[30]	train-rmse:0.143698
[31]	train-rmse:0.126855
[32]	train-rmse:0.118047
[33]	train-rmse:0.114683
[34]	train-rmse:0.110180
[35]	train-rmse:0.101690
[36]	train-rmse:0.096500
[37]	train-rmse:0.090840
[38]	train-rmse:0.085306
[39]	train-rmse:0.079276
[40]	train-rmse:0.071910
[41]	train-rmse:0.067004
[42]	train-rmse:0.063394
[43]	train-rmse:0.061536
[44]	train-rmse:0.057165
[45]	train-rmse:0.053233
[46]	train-rmse:0.050160
[47]	train-rmse:0.046823
[48]	train-rmse:0.042827
[49]	train-rmse:0.041601
[50]	train-rmse:0.038212
[51]	train-rmse:0.034181
[52]	train-rmse:0.032009
[53]	train-rmse:0.030421
[54]	train-rmse:0.028150
[55]	train-rmse:0.026741
[56]	train-rmse:0.025184
[57]	train-rmse:0.024086
[58]	train-rmse:0.021679
[59]	train-rmse:0.020933
[60]	train-rmse:0.019627
[61]	train-rmse:0.018661
[62]	train-rmse:0.017074
[63]	train-rmse:0.015751
[64]	train-rmse:0.014641
[65]	train-rmse:0.013626
[66]	train-rmse:0.013070
[67]	train-rmse:0.012063
[68]	train-rmse:0.011563
[69]	train-rmse:0.011055
[70]	train-rmse:0.010423
[71]	train-rmse:0.009919
[72]	train-rmse:0.008801
[73]	train-rmse:0.008403
[74]	train-rmse:0.007984
[75]	train-rmse:0.006986
[76]	train-rmse:0.006749
[77]	train-rmse:0.006512
[78]	train-rmse:0.006096
[79]	train-rmse:0.005661
[80]	train-rmse:0.005424
[81]	train-rmse:0.004876
[82]	train-rmse:0.004506
[83]	train-rmse:0.004431
[84]	train-rmse:0.004115
[85]	train-rmse:0.004054
[86]	train-rmse:0.003892
[87]	train-rmse:0.003524
[88]	train-rmse:0.003281
[89]	train-rmse:0.003094
[90]	train-rmse:0.003026
[91]	train-rmse:0.002798
[92]	train-rmse:0.002666
[93]	train-rmse:0.002539
[94]	train-rmse:0.002277
[95]	train-rmse:0.002082
[96]	train-rmse:0.002014
[97]	train-rmse:0.001826
[98]	train-rmse:0.001784
[99]	train-rmse:0.001723
[100]	train-rmse:0.001622

In [26]:
xgb_min_cl <- xgboost(data = dtrain_xg_min_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.336927
[2]	train-mlogloss:1.108247
[3]	train-mlogloss:0.945720
[4]	train-mlogloss:0.800212
[5]	train-mlogloss:0.695897
[6]	train-mlogloss:0.610626
[7]	train-mlogloss:0.539893
[8]	train-mlogloss:0.477578
[9]	train-mlogloss:0.422898
[10]	train-mlogloss:0.379453
[11]	train-mlogloss:0.347821
[12]	train-mlogloss:0.318073
[13]	train-mlogloss:0.291677
[14]	train-mlogloss:0.269218
[15]	train-mlogloss:0.246646
[16]	train-mlogloss:0.232475
[17]	train-mlogloss:0.216141
[18]	train-mlogloss:0.201310
[19]	train-mlogloss:0.186213
[20]	train-mlogloss:0.173002
[21]	train-mlogloss:0.162077
[22]	train-mlogloss:0.151775
[23]	train-mlogloss:0.142280
[24]	train-mlogloss:0.132913
[25]	train-mlogloss:0.124454
[26]	train-mlogloss:0.117341
[27]	train-mlogloss:0.111062
[28]	train-mlogloss:0.105443
[29]	train-mlogloss:0.100259
[30]	train-mlogloss:0.094415
[31]	train-mlogloss:0.089462
[32]	train-mlogloss:0.085561
[33]	train-mlogloss:0.081516
[34]	train-mlogloss:0.078135
[35]	train-mlogloss:0.074596
[36]	train-mlogloss:0.071639
[37]	train-mlogloss:0.068756
[38]	train-mlogloss:0.066263
[39]	train-mlogloss:0.064269
[40]	train-mlogloss:0.061860
[41]	train-mlogloss:0.059791
[42]	train-mlogloss:0.058088
[43]	train-mlogloss:0.056424
[44]	train-mlogloss:0.054796
[45]	train-mlogloss:0.053211
[46]	train-mlogloss:0.051826
[47]	train-mlogloss:0.050375
[48]	train-mlogloss:0.049295
[49]	train-mlogloss:0.048095
[50]	train-mlogloss:0.046968
[51]	train-mlogloss:0.045830
[52]	train-mlogloss:0.044890
[53]	train-mlogloss:0.043932
[54]	train-mlogloss:0.043069
[55]	train-mlogloss:0.042260
[56]	train-mlogloss:0.041426
[57]	train-mlogloss:0.040565
[58]	train-mlogloss:0.039851
[59]	train-mlogloss:0.039198
[60]	train-mlogloss:0.038544
[61]	train-mlogloss:0.037954
[62]	train-mlogloss:0.037326
[63]	train-mlogloss:0.036777
[64]	train-mlogloss:0.036232
[65]	train-mlogloss:0.035688
[66]	train-mlogloss:0.035181
[67]	train-mlogloss:0.034743
[68]	train-mlogloss:0.034290
[69]	train-mlogloss:0.033851
[70]	train-mlogloss:0.033349
[71]	train-mlogloss:0.032960
[72]	train-mlogloss:0.032502
[73]	train-mlogloss:0.032162
[74]	train-mlogloss:0.031762
[75]	train-mlogloss:0.031485
[76]	train-mlogloss:0.031163
[77]	train-mlogloss:0.030818
[78]	train-mlogloss:0.030519
[79]	train-mlogloss:0.030180
[80]	train-mlogloss:0.029892
[81]	train-mlogloss:0.029583
[82]	train-mlogloss:0.029313
[83]	train-mlogloss:0.029035
[84]	train-mlogloss:0.028825
[85]	train-mlogloss:0.028557
[86]	train-mlogloss:0.028303
[87]	train-mlogloss:0.028067
[88]	train-mlogloss:0.027845
[89]	train-mlogloss:0.027586
[90]	train-mlogloss:0.027346
[91]	train-mlogloss:0.027153
[92]	train-mlogloss:0.026963
[93]	train-mlogloss:0.026769
[94]	train-mlogloss:0.026583
[95]	train-mlogloss:0.026389
[96]	train-mlogloss:0.026195
[97]	train-mlogloss:0.026032
[98]	train-mlogloss:0.025861
[99]	train-mlogloss:0.025693
[100]	train-mlogloss:0.025518

In [27]:
lgb_min_reg <- lgb.train(data = dtrain_lg_min_reg, nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006112 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1809
[LightGBM] [Info] Number of data points in the train set: 293, number of used features: 21
[LightGBM] [Info] Start training from score 2.109215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [28]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_min_cl <- lgb.train(data = dtrain_lg_min_cl,nrounds = 100,params=params)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000592 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1809
[LightGBM] [Info] Number of data points in the train set: 293, number of used features: 21
[LightGBM] [Info] Start training from score -1.431677
[LightGBM] [Info] Start training from score -1.851531
[LightGBM] [Info] Start training from score -1.895983
[LightGBM] [Info] Start training from score -1.808972
[LightGBM] [Info] Start training from score -1.237521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [29]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

## Target the interval where the average error is minimum

In [30]:
start_time = Sys.time()

In [31]:
dtrain_xg_mean_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_mean)) 
dtrain_xg_mean_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)) )

In [32]:
dtrain_lg_mean_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_mean))
dtrain_lg_mean_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)))

In [33]:
xgb_mean_reg <- xgboost(data = dtrain_xg_mean_reg, nround=100)

[1]	train-rmse:1.549655
[2]	train-rmse:1.249129
[3]	train-rmse:1.061063
[4]	train-rmse:0.933098
[5]	train-rmse:0.813894
[6]	train-rmse:0.762802
[7]	train-rmse:0.674252
[8]	train-rmse:0.622831
[9]	train-rmse:0.572754
[10]	train-rmse:0.552619
[11]	train-rmse:0.503704
[12]	train-rmse:0.472615
[13]	train-rmse:0.430372
[14]	train-rmse:0.386408
[15]	train-rmse:0.341767
[16]	train-rmse:0.331640
[17]	train-rmse:0.317406
[18]	train-rmse:0.285973
[19]	train-rmse:0.265783
[20]	train-rmse:0.233876
[21]	train-rmse:0.210831
[22]	train-rmse:0.195281
[23]	train-rmse:0.181433
[24]	train-rmse:0.175499
[25]	train-rmse:0.166980
[26]	train-rmse:0.154792
[27]	train-rmse:0.145108
[28]	train-rmse:0.136190
[29]	train-rmse:0.130952
[30]	train-rmse:0.119489
[31]	train-rmse:0.112317
[32]	train-rmse:0.107099
[33]	train-rmse:0.095624
[34]	train-rmse:0.092639
[35]	train-rmse:0.083314
[36]	train-rmse:0.076193
[37]	train-rmse:0.073675
[38]	train-rmse:0.070546
[39]	train-rmse:0.065493
[40]	train-rmse:0.060497
[41]	train-rmse:0.059167
[42]	train-rmse:0.055292
[43]	train-rmse:0.053036
[44]	train-rmse:0.051191
[45]	train-rmse:0.047083
[46]	train-rmse:0.045513
[47]	train-rmse:0.043418
[48]	train-rmse:0.040579
[49]	train-rmse:0.039195
[50]	train-rmse:0.037917
[51]	train-rmse:0.035211
[52]	train-rmse:0.031617
[53]	train-rmse:0.029626
[54]	train-rmse:0.026111
[55]	train-rmse:0.024844
[56]	train-rmse:0.024272
[57]	train-rmse:0.022675
[58]	train-rmse:0.021348
[59]	train-rmse:0.020313
[60]	train-rmse:0.018323
[61]	train-rmse:0.017198
[62]	train-rmse:0.015708
[63]	train-rmse:0.014881
[64]	train-rmse:0.013515
[65]	train-rmse:0.012027
[66]	train-rmse:0.011285
[67]	train-rmse:0.011056
[68]	train-rmse:0.010728
[69]	train-rmse:0.010195
[70]	train-rmse:0.009836
[71]	train-rmse:0.009413
[72]	train-rmse:0.008607
[73]	train-rmse:0.007696
[74]	train-rmse:0.007016
[75]	train-rmse:0.006831
[76]	train-rmse:0.006524
[77]	train-rmse:0.006175
[78]	train-rmse:0.005781
[79]	train-rmse:0.005240
[80]	train-rmse:0.004895
[81]	train-rmse:0.004533
[82]	train-rmse:0.004097
[83]	train-rmse:0.003755
[84]	train-rmse:0.003494
[85]	train-rmse:0.003299
[86]	train-rmse:0.003192
[87]	train-rmse:0.003003
[88]	train-rmse:0.002842
[89]	train-rmse:0.002698
[90]	train-rmse:0.002575
[91]	train-rmse:0.002413
[92]	train-rmse:0.002325
[93]	train-rmse:0.002202
[94]	train-rmse:0.002064
[95]	train-rmse:0.001873
[96]	train-rmse:0.001762
[97]	train-rmse:0.001667
[98]	train-rmse:0.001607
[99]	train-rmse:0.001493
[100]	train-rmse:0.001434

In [34]:
xgb_mean_cl <- xgboost(data = dtrain_xg_mean_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.293444
[2]	train-mlogloss:1.065831
[3]	train-mlogloss:0.904407
[4]	train-mlogloss:0.776237
[5]	train-mlogloss:0.674723
[6]	train-mlogloss:0.577363
[7]	train-mlogloss:0.515430
[8]	train-mlogloss:0.448781
[9]	train-mlogloss:0.410910
[10]	train-mlogloss:0.363751
[11]	train-mlogloss:0.322460
[12]	train-mlogloss:0.294463
[13]	train-mlogloss:0.266970
[14]	train-mlogloss:0.244399
[15]	train-mlogloss:0.225562
[16]	train-mlogloss:0.210434
[17]	train-mlogloss:0.196210
[18]	train-mlogloss:0.179992
[19]	train-mlogloss:0.170812
[20]	train-mlogloss:0.160558
[21]	train-mlogloss:0.150853
[22]	train-mlogloss:0.139821
[23]	train-mlogloss:0.130379
[24]	train-mlogloss:0.121582
[25]	train-mlogloss:0.114451
[26]	train-mlogloss:0.107585
[27]	train-mlogloss:0.101813
[28]	train-mlogloss:0.095875
[29]	train-mlogloss:0.091049
[30]	train-mlogloss:0.086486
[31]	train-mlogloss:0.082573
[32]	train-mlogloss:0.079254
[33]	train-mlogloss:0.075730
[34]	train-mlogloss:0.072516
[35]	train-mlogloss:0.069560
[36]	train-mlogloss:0.067010
[37]	train-mlogloss:0.064653
[38]	train-mlogloss:0.062475
[39]	train-mlogloss:0.060328
[40]	train-mlogloss:0.058470
[41]	train-mlogloss:0.056744
[42]	train-mlogloss:0.055135
[43]	train-mlogloss:0.053735
[44]	train-mlogloss:0.052192
[45]	train-mlogloss:0.050867
[46]	train-mlogloss:0.049432
[47]	train-mlogloss:0.048068
[48]	train-mlogloss:0.047000
[49]	train-mlogloss:0.045856
[50]	train-mlogloss:0.044945
[51]	train-mlogloss:0.044037
[52]	train-mlogloss:0.043148
[53]	train-mlogloss:0.042369
[54]	train-mlogloss:0.041486
[55]	train-mlogloss:0.040702
[56]	train-mlogloss:0.039991
[57]	train-mlogloss:0.039323
[58]	train-mlogloss:0.038748
[59]	train-mlogloss:0.038140
[60]	train-mlogloss:0.037606
[61]	train-mlogloss:0.037043
[62]	train-mlogloss:0.036466
[63]	train-mlogloss:0.035920
[64]	train-mlogloss:0.035422
[65]	train-mlogloss:0.034892
[66]	train-mlogloss:0.034428
[67]	train-mlogloss:0.033952
[68]	train-mlogloss:0.033537
[69]	train-mlogloss:0.033155
[70]	train-mlogloss:0.032703
[71]	train-mlogloss:0.032365
[72]	train-mlogloss:0.032001
[73]	train-mlogloss:0.031626
[74]	train-mlogloss:0.031285
[75]	train-mlogloss:0.030973
[76]	train-mlogloss:0.030700
[77]	train-mlogloss:0.030349
[78]	train-mlogloss:0.030059
[79]	train-mlogloss:0.029755
[80]	train-mlogloss:0.029425
[81]	train-mlogloss:0.029178
[82]	train-mlogloss:0.028976
[83]	train-mlogloss:0.028767
[84]	train-mlogloss:0.028512
[85]	train-mlogloss:0.028260
[86]	train-mlogloss:0.028030
[87]	train-mlogloss:0.027791
[88]	train-mlogloss:0.027588
[89]	train-mlogloss:0.027377
[90]	train-mlogloss:0.027171
[91]	train-mlogloss:0.026986
[92]	train-mlogloss:0.026807
[93]	train-mlogloss:0.026612
[94]	train-mlogloss:0.026445
[95]	train-mlogloss:0.026257
[96]	train-mlogloss:0.026063
[97]	train-mlogloss:0.025902
[98]	train-mlogloss:0.025764
[99]	train-mlogloss:0.025598
[100]	train-mlogloss:0.025430

In [35]:
lgb_mean_reg <- lgb.train(data = dtrain_lg_mean_reg,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005573 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1809
[LightGBM] [Info] Number of data points in the train set: 293, number of used features: 21
[LightGBM] [Info] Start training from score 1.767918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [36]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_mean_cl <- lgb.train(data = dtrain_lg_mean_cl,params=params,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000485 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1809
[LightGBM] [Info] Number of data points in the train set: 293, number of used features: 21
[LightGBM] [Info] Start training from score -1.202836
[LightGBM] [Info] Start training from score -1.709881
[LightGBM] [Info] Start training from score -1.873510
[LightGBM] [Info] Start training from score -1.709881
[LightGBM] [Info] Start training from score -1.691189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [37]:
end_time = Sys.time()
time_matrix[3,]=end_time-start_time

In [38]:
end_time-start_time

Time difference of 33.32866 secs

## predict

In [39]:
start_time = Sys.time()

In [40]:
alldatalgb <- lgb.Dataset(data = as.matrix(data))
alldataxgb <- xgb.DMatrix(data = as.matrix(data))

In [41]:
xgbregmin=predict(xgb_min_reg,alldataxgb)
xgbclsmin=predict(xgb_min_cl,alldataxgb)
lgbregmin=predict(lgb_min_reg,as.matrix(data))
lgbclsmin=predict(lgb_min_cl,as.matrix(data))

In [42]:
xgbregmin

  [1]  1.998953e+00  2.999349e+00  1.000835e+00  1.476962e-04  1.001425e+00
  [6]  2.142525e-04  3.801980e+00  3.998814e+00  2.633948e-04  3.999939e+00
 [11]  4.000394e+00  2.646631e+00  3.999354e+00 -1.501857e-04  2.602381e+00
 [16]  4.311104e-03  1.002409e+00  1.001480e+00 -4.136703e-04  9.995874e-01
 [21]  1.997759e+00  8.213826e-01  1.286534e-03  1.027591e+00  3.999042e+00
 [26]  1.471940e-03  2.569144e+00  3.937135e+00  1.999449e+00  3.996399e+00
 [31]  2.996437e+00  1.788467e+00  1.002579e+00  1.691461e+00  1.000002e+00
 [36]  2.471199e+00  3.999868e+00  4.000184e+00  2.817363e+00  2.183351e-03
 [41]  4.000184e+00  1.999930e+00  1.329466e+00  2.204340e+00  1.115220e-03
 [46] -6.183041e-04 -1.712011e-01  1.537667e+00  3.998386e+00  9.998744e-01
 [51]  2.000315e+00  6.219127e-04  1.000221e+00  3.998654e+00  3.999416e+00
 [56]  1.718793e-03  4.001326e+00 -5.729318e-04  1.226709e-03  2.995728e+00
 [61]  2.000329e+00  1.000388e+00  2.176264e+00  3.001295e+00  1.999948e+00
 [66]  3.998907e+00  4.000719e+00  1.741615e-03  2.999228e+00  3.999164e+00
 [71]  3.998935e+00  1.006065e+00  4.000143e+00  2.782937e-01  1.000560e+00
 [76]  4.678030e-04  2.017277e+00  9.674459e-01  1.234645e+00  1.998316e+00
 [81]  7.448808e-04  1.999819e+00  2.552356e+00  1.724539e+00  9.998212e-01
 [86]  3.998655e+00  2.386220e+00  2.052605e-05 -3.617051e-04  3.649397e+00
 [91]  2.801048e+00  4.000034e+00  3.667758e-04  4.111812e-05  1.081294e+00
 [96]  3.999906e+00  3.999214e+00  2.000227e+00  3.998159e+00  2.696720e+00
[101]  8.948586e-04  4.000310e+00  7.635558e-04  1.999672e+00  9.996099e-01
[106]  2.999702e+00  2.102261e+00  2.318580e+00  2.001211e+00  2.995038e+00
[111]  1.460030e+00  2.461166e+00  2.000387e+00  8.908738e-05  3.484048e+00
[116]  2.000407e+00  9.771343e-01  2.730732e+00  3.997576e+00  7.275441e-01
[121]  3.998194e+00  3.999424e+00  2.800769e-03  2.002748e+00  2.994889e+00
[126]  3.000400e+00  1.915647e+00  7.053884e-01  1.999557e+00  9.984160e-05
[131] -7.093707e-05  3.442372e-01  9.842417e-01  3.999830e+00  9.532446e-04
[136]  9.999562e-01 -1.436000e-04  2.996813e+00  2.001467e+00  1.001444e+00
[141]  1.000024e+00  3.866310e-03  3.997362e+00  2.556392e+00  1.000199e+00
[146]  2.959180e+00  2.548652e+00  2.997536e+00  1.000708e+00  4.189939e-04
[151]  4.000589e+00  2.286939e+00  6.254422e-04  4.000319e+00  9.968333e-01
[156]  2.411686e+00 -2.411197e-02  1.978404e+00  1.999962e+00  3.999954e+00
[161]  9.283929e-01  3.999030e+00  1.000297e+00  1.001132e+00  2.999061e+00
[166]  1.001498e+00  9.997318e-01  2.781759e+00  2.416405e+00  3.854815e+00
[171]  3.000483e+00  2.000311e+00  2.000109e+00  2.451133e+00  2.580112e+00
[176]  1.000450e+00  3.339030e+00  3.999590e+00  1.003090e+00  3.999189e+00
[181]  3.995978e+00  2.290852e+00  3.253838e+00  3.001688e+00  3.999504e+00
[186]  2.000325e+00  2.040403e-03  3.997955e+00  2.000402e+00  6.215892e-01
[191]  2.819391e+00  3.000044e+00  1.248154e-03  1.283756e+00  3.000309e+00
[196]  3.994802e+00  3.000912e+00  1.258876e-03  2.999655e+00  1.765737e+00
[201]  3.999521e+00  2.756090e+00  8.299021e-01  2.757907e+00  2.000922e+00
[206]  8.488621e-01  2.033750e+00  3.997979e+00  2.999764e+00  2.002242e+00
[211]  1.999928e+00  2.819696e+00  1.280841e-03  3.000302e+00  2.999138e+00
[216]  3.998133e+00  2.692478e+00  1.916916e+00  4.000061e+00  1.999247e+00
[221]  3.377972e-03  3.999620e+00  2.000426e+00  1.638760e+00  2.785912e-03
[226]  3.998649e+00  3.999435e+00  3.999521e+00  2.000147e+00  2.999754e+00
[231]  4.000305e+00  3.998685e+00  1.685941e+00  2.999717e+00  2.003718e+00
[236]  4.000456e+00  3.999589e+00  6.383260e-01  2.179715e+00  1.294742e+00
[241]  3.000242e+00  2.319597e+00  2.999777e+00  3.082466e+00  1.999232e+00
[246]  2.443276e+00  3.000026e+00  2.819781e-03  3.000189e+00  2.000051e+00
[251]  2.999789e+00  2.542407e+00  2.999390e+00 -6.680128e-04  2.583658e+00
[256]  1.421138e+00  3.996334e+00 -6.364976e-05  5.788520e-03  2.239192e+00
[261]  3.999755e+00  8.542349e-01  1.000522e+00  1.780033e+00  2.744923e-01
[266]  3.141185e+00  1.999644e+00  3.994408e+00  1.865345e+00  3.475282e+00
[271]  4.000026e+00  3.115621e+00  3.000847e+00  3.000632e+00  3.001154e+00
[276]  1.750754e+00  3.999746e+00  3.996344e+00  3.000044e+00  3.000343e+00
[281]  2.001316e+00  4.000194e+00  3.001278e+00  2.106170e-03  2.000587e+00
[286]  2.001064e+00  2.567295e+00  1.211236e+00  2.000606e+00  2.000288e+00
[291]  1.000688e+00  2.999579e+00  3.999895e+00  2.999133e+00  1.999524e+00
[296]  4.000063e+00  3.999517e+00  2.015526e+00  3.000955e+00  3.995609e+00
[301]  2.432488e+00  4.001125e+00  1.686011e+00  2.044508e-04  3.998901e+00
[306]  2.225098e+00  4.000439e+00  3.993872e+00  4.001044e+00  3.366368e+00
[311]  4.000079e+00  2.899191e+00 -3.440764e-04  1.000196e+00  3.998109e+00
[316]  9.277556e-04  3.923324e-04  1.650418e+00  3.000321e+00  3.266857e+00
[321]  4.000047e+00 -1.205292e-03  1.001973e+00  9.149793e-01  1.000502e+00
[326]  1.025512e+00  2.701619e+00  4.000593e+00  5.136576e-04  9.956720e-01
[331]  8.299503e-04  9.997414e-01  3.998293e+00 -1.107726e-03  9.863374e-04
[336]  1.000062e+00  3.999844e+00  8.131853e-04  2.793837e+00  2.607064e-03
[341]  2.375706e+00  1.031753e-03  3.998519e+00  9.997309e-01  2.995460e+00
[346]  2.999846e+00  1.000381e+00  1.442595e+00  3.997235e+00  9.165604e-01
[351]  2.998801e+00  1.044824e-03  3.998671e+00  9.985999e-01  1.001246e+00
[356]  4.000490e+00  1.350551e+00  1.997946e+00  2.451121e+00  2.000314e+00
[361]  1.176842e-04  1.003873e+00  2.619683e+00  1.298434e-04  2.998493e+00
[366]  4.000029e+00  2.000005e+00  1.997426e+00  1.661095e+00  3.246378e+00
[371]  1.437193e+00  1.002815e+00  8.505069e-04  3.998636e+00  1.000267e+00
[376]  1.001177e+00  1.000482e+00  3.000396e+00  9.999228e-01  1.392119e+00
[381]  1.596772e-04  3.999632e+00  2.999853e+00 -9.967793e-05  1.394972e+00
[386]  9.988024e-01  3.225588e-03  4.008630e-03  2.164265e+00  2.997839e+00
[391]  1.001028e+00  3.187842e-03  8.868780e-01  1.945738e-03  1.999013e+00
[396]  2.999290e+00  4.000381e+00  9.143669e-04  2.283509e+00  3.999206e+00
[401]  3.999313e+00  2.000394e+00  3.999022e+00  4.133522e-05  1.792234e+00
[406]  3.998928e+00  1.999861e+00  1.817182e+00  1.687345e+00  2.999873e+00
[411] -4.400151e-04  1.004586e-03  9.990815e-01  3.307760e+00

In [43]:
xgbclsmin

  [1] 2 3 1 0 1 0 4 4 0 4 4 0 4 0 0 0 1 1 0 1 2 0 0 0 4 0 2 4 2 4 3 0 1 2 1 4 4
 [38] 4 4 0 4 3 0 4 0 0 0 0 4 1 2 0 1 4 4 0 4 0 0 3 2 1 4 3 2 4 4 0 3 4 4 1 4 0
 [75] 1 0 0 0 1 2 0 2 4 4 1 4 1 0 0 4 2 4 0 0 0 4 4 2 4 4 0 4 0 2 1 3 0 4 2 3 4
[112] 2 2 0 4 2 1 4 4 0 4 4 0 2 3 3 3 4 2 0 0 1 1 4 0 1 0 3 2 1 1 0 4 0 1 1 1 3
[149] 1 0 4 1 0 4 1 4 0 4 2 4 0 4 1 1 3 1 1 1 1 4 3 2 2 3 4 1 4 4 1 4 4 3 2 3 4
[186] 2 0 4 2 0 4 3 0 0 3 4 3 0 3 4 4 4 1 4 2 4 4 4 3 2 2 4 0 3 3 4 4 0 4 2 0 4
[223] 2 0 0 4 4 4 2 3 4 4 4 3 2 4 4 4 4 2 3 4 3 2 2 4 3 0 3 2 3 4 3 0 4 0 4 0 0
[260] 4 4 4 1 3 0 3 2 4 0 4 4 4 3 3 3 3 4 4 3 3 2 4 3 0 2 2 4 2 2 2 1 3 4 3 2 4
[297] 4 4 3 4 2 4 0 0 4 4 4 4 4 4 4 2 0 1 4 0 0 0 3 4 4 0 1 2 1 4 4 4 0 1 0 1 4
[334] 0 0 1 4 0 1 0 0 0 4 1 3 3 1 2 4 0 3 0 4 1 1 4 0 2 1 2 0 1 4 0 3 4 2 2 4 1
[371] 3 1 0 4 1 1 1 3 1 1 0 4 3 0 1 1 0 0 4 3 1 0 0 0 2 3 4 0 1 4 4 2 4 0 2 4 2
[408] 0 0 3 0 0 1 1

In [44]:
lgbregmin

  [1]  1.63809744  2.32771357  1.36400478  1.00543851  1.94706120  0.15343105
  [7]  2.82095115  3.24705965  0.27475332  3.90180095  3.64539181  1.99009424
 [13]  3.77994744  0.17416126  1.94063290  0.17705145  1.76388750  1.21227029
 [19]  0.37598153  1.11120381  1.76038995  0.38101898  0.72627740  0.99338596
 [25]  3.50923313  0.53321066  1.92925696  3.19130971  1.99803927  3.36882198
 [31]  2.65394967  1.80536537  1.67904903  1.91151736  1.54713811  2.13753990
 [37]  3.77891334  3.70135348  2.82612771  0.29989378  3.67056980  3.26788821
 [43]  1.77081089  2.74669508  0.46341255  0.04857068  0.85106445  1.21028066
 [49]  3.23069355  0.25517152  1.77241726  0.15762195  1.37532392  3.62482177
 [55]  3.72987647  1.42900968  3.67605729 -0.01812686  0.48463232  2.61257266
 [61]  2.05966082  1.50138851  3.08390658  3.06371277  2.43780078  3.31374168
 [67]  3.32184840 -0.02660186  2.65035991  3.60411778  3.68573594  1.02593404
 [73]  3.96322313  1.31085908  1.51743409  1.04521068  2.87086013  1.20032505
 [79]  1.77727622  1.56731297 -0.30745294  2.15041605  1.85347133  1.50214888
 [85]  1.35621147  3.36652811  1.85193880  0.92761770  0.34087308  3.39681529
 [91]  1.95409143  3.48388371  0.59557756  0.87085713  0.84719197  3.57496784
 [97]  3.75125328  1.65271790  3.93977471  2.13665518  0.63805263  3.63588084
[103]  0.60544911  2.06869427  0.78934136  2.97947765  1.21007570  3.10452407
[109]  1.96042773  2.33452497  1.38904457  2.10911399  1.56749937 -0.16399295
[115]  2.44714864  2.00879635  0.97243320  3.16495118  3.65109624  1.49530172
[121]  4.06074646  3.86429298  0.64382073  2.07080665  2.35977616  2.71878509
[127]  2.09309482  2.06503374  1.48870510  0.22032960  0.28978425  0.95053314
[133]  1.52582279  3.17348096  1.25692170  1.25756503  0.40156553  2.66734826
[139]  2.01028776  1.50103035  1.38494692  0.24506347  2.79618958  1.52307829
[145]  0.92252520  2.05419620  1.65149652  3.01977972  1.12488588  0.53232125
[151]  3.87555580  2.00087789  0.48649261  3.75890275  0.74382306  1.82167203
[157]  1.05731492  1.20837093  1.67467043  3.44827860  0.95414339  3.37881157
[163]  1.63717813  1.62531117  2.36637464  1.44297893  1.39629902  2.34655013
[169]  2.24419905  3.64154872  3.00751045  1.97471638  2.25764786  1.84977606
[175]  2.34232098  1.68167851  3.83392921  3.37494255  1.31514205  3.00013212
[181]  3.19454880  2.70429567  2.66466873  2.78433986  3.46090099  1.72884389
[187]  0.93412066  3.66785796  1.54381825  0.47693521  2.31198778  3.24753149
[193]  0.71498382  0.55670448  2.86385113  3.27093427  3.04025243  0.92129485
[199]  3.23795077  1.55291354  4.07552430  2.25354002  1.54557312  3.42703437
[205]  2.06989721  2.17627955  1.96394343  3.75225326  2.48555299  2.78328092
[211]  2.17018612  3.30928990  0.40461239  3.05439444  2.57419803  3.13366270
[217]  2.66285555  2.02346091  3.92895048  2.05543812  0.78974612  3.66053229
[223]  2.45505093  0.95252746  0.63314831  3.92473770  3.61648372  3.55128325
[229]  2.22277724  2.79702770  3.78370899  3.28425023  2.31899655  3.09909115
[235]  2.36613559  3.82911883  3.90007433  2.44606505  3.01061634  2.26950548
[241]  2.49783412  3.03994384  3.03597410  2.64443597  1.54228803  3.61686701
[247]  2.97502916  0.96971690  2.66891915  2.35275645  3.02048807  3.29437752
[253]  2.70361802  0.52365888  2.13038877  2.32534676  3.31456620  0.22832062
[259]  1.27385188  2.94899853  3.35275935  1.96244772  1.53600848  2.38109867
[265]  0.15008163  2.93274147  2.01565065  3.24910612  1.85484839  3.19661246
[271]  3.81917714  2.47198421  3.48339290  3.05327032  3.42955104  2.46055837
[277]  4.09880486  3.39967620  2.83944237  2.99071678  1.94596954  3.91005929
[283]  3.18185838  1.08302036  2.05556498  2.40358507  2.51913834  1.29890895
[289]  2.20687916  1.88331843  1.26699138  3.18996910  3.58958414  2.96961049
[295]  1.40251690  3.79507693  3.42441818  2.02994172  2.58455484  3.71453972
[301]  2.00022762  3.58543450  1.05426659  0.78766007  3.55023650  3.62860513
[307]  3.88028797  3.80185108  4.10124881  3.06831158  3.82880047  1.83426677
[313]  0.04072771  1.11937955  3.76072015  0.49320267  0.88913716  1.99062993
[319]  2.77347918  3.32268146  3.39360463  0.10579354  1.73324085  1.92704835
[325]  1.34396922  1.73258465  3.26356068  3.59090388  0.58243230  0.80884231
[331]  0.76693234  0.93256923  3.50403311  0.53057035  0.31389663  1.29133223
[337]  3.28999599  0.50729644  1.59366980  0.52478542  1.63853821  0.73188965
[343]  2.70096862  0.93470759  2.23306952  2.45095710  1.38133798  1.66803607
[349]  3.46883643  0.68482441  2.29458303  0.54676893  4.04201227  1.16905357
[355]  1.31708590  3.60772859  0.56635124  1.30506285  2.11270167  1.82932873
[361]  0.68855863  1.40443529  2.02422955  0.54503396  2.37149159  3.74341666
[367]  2.31221935  1.75541562  2.19162105  1.94950500  2.72499011  1.26588872
[373]  0.13279814  3.50100316  1.20133311  1.12447411  1.26733024  2.91894497
[379]  0.79696769  2.29028294  0.22997955  2.79857767  2.36530049  0.29678262
[385]  1.86008036  1.06419413  0.61721536  0.18198087  1.32317857  2.46694160
[391]  1.79155710  0.54085434  1.26404012  1.09805339  1.95670284  1.62604260
[397]  3.30765818  0.25405725  2.05325439  3.62913780  3.16656092  1.91085066
[403]  3.31720707  0.69476526  1.31458121  3.07873724  2.05210937  2.10939315
[409]  0.66963304  2.31176536  0.28810106  0.41976243  1.33953169  2.28717203

In [45]:
lgbclsmin

      [,1]        [,2]        [,3]         [,4]         [,5]
 [1,] 0.014380798 0.007974292 9.755254e-01 1.057739e-03 0.001061818
 [2,] 0.016073760 0.009727942 7.785087e-03 9.636115e-01 0.002801716
 [3,] 0.010025921 0.968030854 4.056379e-04 1.286385e-03 0.020251203
 [4,] 0.898859719 0.038971530 2.838747e-03 6.755433e-03 0.052574572
 [5,] 0.008423550 0.937124017 7.374554e-04 2.184170e-03 0.051530807
 [6,] 0.971987189 0.013720894 6.462716e-04 4.117012e-03 0.009528633
 [7,] 0.005780626 0.001005591 1.630048e-04 2.679546e-04 0.992782823
 [8,] 0.011550861 0.015445538 7.315176e-04 4.603927e-03 0.967668157
 [9,] 0.951609803 0.029819191 2.393692e-04 1.640656e-03 0.016690981
[10,] 0.005697552 0.007757414 2.387594e-03 2.055974e-03 0.982101466
[11,] 0.014335447 0.002936571 7.177054e-04 6.137923e-04 0.981396483
[12,] 0.772028277 0.021225021 8.307727e-03 3.362527e-03 0.195076448
[13,] 0.005372108 0.018301435 3.803461e-03 4.425176e-03 0.968097819
[14,] 0.981012857 0.007566705 1.991972e-03 2.044712e-04 0.009223994
[15,] 0.860596443 0.008143625 1.035020e-02 1.087682e-02 0.110032909
[16,] 0.973427066 0.007932738 1.270961e-02 3.667798e-03 0.002262789
[17,] 0.002768149 0.965269907 7.136363e-03 1.156418e-02 0.013261399
[18,] 0.011549978 0.979303894 6.025019e-03 1.793861e-03 0.001327248
[19,] 0.981511680 0.008389841 9.772116e-03 7.918816e-05 0.000247174
[20,] 0.011669030 0.973559259 3.445370e-04 1.778436e-03 0.012648739
[21,] 0.002438611 0.007998523 9.853814e-01 1.452983e-03 0.002728470
[22,] 0.324815229 0.010432446 6.595839e-01 2.515618e-04 0.004916881
[23,] 0.941124192 0.011271124 1.542582e-02 3.115130e-03 0.029063730
[24,] 0.755976874 0.034545051 4.696224e-03 7.464274e-03 0.197317577
[25,] 0.011372360 0.018268989 8.990351e-05 9.968031e-05 0.970169067
[26,] 0.955732700 0.019752571 5.530541e-03 9.559222e-04 0.018028266
[27,] 0.200159838 0.045480304 6.596660e-01 1.759496e-03 0.092934397
[28,] 0.044338375 0.001412416 4.116301e-04 4.694983e-04 0.953368080
[29,] 0.012972439 0.001278406 9.767443e-01 7.528541e-04 0.008252015
[30,] 0.029640921 0.015689401 5.029137e-04 9.493390e-03 0.944673373
[31,] ⋮           ⋮           ⋮            ⋮            ⋮
[32,] 0.100518032 0.274169383 0.1922278271 0.0120798914 0.421004866
[33,] 0.011168071 0.979615932 0.0012611945 0.0063358557 0.001618947
[34,] 0.948327342 0.030521789 0.0007112941 0.0036871400 0.016752435
[35,] 0.967511221 0.007409687 0.0018855288 0.0116641883 0.011529375
[36,] 0.800065286 0.021000536 0.0234185087 0.0114748393 0.144040829
[37,] 0.015865629 0.002327185 0.0005626552 0.9573824899 0.023862041
[38,] 0.004219052 0.964161343 0.0010424581 0.0004669768 0.030110170
[39,] 0.964337158 0.010502329 0.0072030764 0.0074232032 0.010534234
[40,] 0.780556725 0.033386717 0.0006463305 0.1094308007 0.075979427
[41,] 0.932329544 0.013516135 0.0054342684 0.0038589414 0.044861111
[42,] 0.012976515 0.006673194 0.9762336286 0.0003015998 0.003815063
[43,] 0.040374944 0.003155055 0.0010701668 0.9537336328 0.001666201
[44,] 0.014260790 0.012588547 0.0016347180 0.0065781633 0.964937783
[45,] 0.976344306 0.003115527 0.0028138240 0.0027470628 0.014979280
[46,] 0.229447674 0.321126008 0.0026882798 0.0051858515 0.441552186
[47,] 0.012869055 0.006993675 0.0004545163 0.0086881410 0.970994613
[48,] 0.034839216 0.005247676 0.0071900302 0.0019030350 0.950820042
[49,] 0.013640850 0.004044622 0.9672720310 0.0038881953 0.011154301
[50,] 0.019596355 0.006192444 0.0028605045 0.0031693112 0.968181385
[51,] 0.969193496 0.003860640 0.0011875522 0.0173522442 0.008406068
[52,] 0.405806463 0.075552429 0.3270720957 0.0070938089 0.184475204
[53,] 0.017767314 0.018993050 0.0039323444 0.0036932213 0.955614070
[54,] 0.005678480 0.006415391 0.9831119550 0.0004468956 0.004347278
[55,] 0.372653325 0.065319931 0.2636213632 0.0078585851 0.290546796
[56,] 0.926402420 0.027660102 0.0046540302 0.0067016116 0.034581836
[57,] 0.028033582 0.006653811 0.0006762364 0.9588463017 0.005790070
[58,] 0.963616629 0.012025343 0.0003538200 0.0034643623 0.020539846
[59,] 0.975947109 0.003742732 0.0041334865 0.0006265431 0.015550129
[60,] 0.013692395 0.962885172 0.0007216957 0.0138474471 0.008853290
[61,] 0.293558850 0.224960591 0.1070966511 0.0430606123 0.331323296

In [46]:
datalength=dim(data)[1]
lgbclsm=matrix(lgbclsmin,m,datalength)
lgbclsminr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsminr[i,]=which.max(lgbclsm[,i])
}
lgbclsminr=lgbclsminr-1

In [47]:
lgbclsminr

      [,1]
 [1,] 3
 [2,] 0
 [3,] 3
 [4,] 3
 [5,] 2
 [6,] 0
 [7,] 1
 [8,] 4
 [9,] 2
[10,] 0
[11,] 1
[12,] 2
[13,] 2
[14,] 2
[15,] 3
[16,] 0
[17,] 0
[18,] 3
[19,] 3
[20,] 4
[21,] 2
[22,] 1
[23,] 3
[24,] 4
[25,] 2
[26,] 4
[27,] 0
[28,] 1
[29,] 1
[30,] 4
[31,] ⋮
[32,] 3
[33,] 1
[34,] 2
[35,] 2
[36,] 2
[37,] 3
[38,] 1
[39,] 2
[40,] 2
[41,] 1
[42,] 0
[43,] 1
[44,] 3
[45,] 3
[46,] 2
[47,] 3
[48,] 4
[49,] 3
[50,] 1
[51,] 3
[52,] 1
[53,] 4
[54,] 1
[55,] 2
[56,] 0
[57,] 3
[58,] 2
[59,] 0
[60,] 1
[61,] 4

In [48]:
xgbregmean=predict(xgb_mean_reg,alldataxgb)
xgbclsmean=predict(xgb_mean_cl,alldataxgb)
lgbregmean=predict(lgb_mean_reg,as.matrix(data))
lgbclsmean=predict(lgb_mean_cl,as.matrix(data))

In [49]:
lgbclsm=matrix(lgbclsmean,m,datalength)
lgbclsmeanr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsmeanr[i,]=which.max(lgbclsm[,i])
}
lgbclsmeanr=lgbclsmeanr-1

In [50]:
preallmin=cbind(xgbclsmin,xgbregmin)
preallmin=cbind(preallmin,lgbclsminr)
preallmin=cbind(preallmin,lgbregmin)

In [51]:
colnames(preallmin)=c('xgbclsmin','xgbregmin','lgbclsmin','lgbregmin')
head(preallmin)

     xgbclsmin xgbregmin    lgbclsmin lgbregmin
[1,] 2         1.9989531040 3         1.638097
[2,] 3         2.9993493557 0         2.327714
[3,] 1         1.0008352995 3         1.364005
[4,] 0         0.0001476962 3         1.005439
[5,] 1         1.0014251471 2         1.947061
[6,] 0         0.0002142525 0         0.153431

In [52]:
preallmean=cbind(xgbclsmean,xgbregmean)
preallmean=cbind(preallmean,lgbclsmeanr)
preallmean=cbind(preallmean,lgbregmean)

In [53]:
head(preallmean)

     xgbclsmean xgbregmean      lgbregmean
[1,] 2           1.9998954535 2 1.6659382
[2,] 1           1.0003926754 4 1.2679726
[3,] 1           0.9987677336 3 1.2723569
[4,] 4           3.9979720116 3 3.5055921
[5,] 1           1.0018657446 4 2.5799506
[6,] 0          -0.0006571151 2 0.1683413

In [54]:
colnames(preallmean)=c('xgbclsmean','xgbregmean','lgbclsmean','lgbregmean')
head(preallmean)

     xgbclsmean xgbregmean    lgbclsmean lgbregmean
[1,] 2           1.9998954535 2          1.6659382
[2,] 1           1.0003926754 4          1.2679726
[3,] 1           0.9987677336 3          1.2723569
[4,] 4           3.9979720116 3          3.5055921
[5,] 1           1.0018657446 4          2.5799506
[6,] 0          -0.0006571151 2          0.1683413

In [55]:
end_time = Sys.time()
time_matrix[4,]=end_time-start_time

In [56]:
result_list=list(preallmin,preallmean,time_matrix)

In [60]:
save(result_list, file = "Hourly_nnetar_opt_pre_result.RData")

In [58]:
time_matrix

     user_time system_time elapsed_time
[1,]  7.430921  7.430921    7.430921
[2,]  4.603225  4.603225    4.603225
[3,] 33.328655 33.328655   33.328655
[4,]  9.284281  9.284281    9.284281

In [59]:
importance_matrix1 <- xgb.importance(model = xgb_mean_cl)
importance_matrix2 <- xgb.importance(model = xgb_mean_reg)
importance_matrix3 <- lgb.importance(lgb_mean_cl)
importance_matrix4 <- lgb.importance(lgb_mean_reg)

importance_matrix1=importance_matrix1[order(importance_matrix1$Feature),]
importance_matrix2=importance_matrix2[order(importance_matrix2$Feature),]
importance_matrix3=importance_matrix3[order(importance_matrix3$Feature),]
importance_matrix4=importance_matrix4[order(importance_matrix4$Feature),]

importance_matrix_mean=(importance_matrix1[,2:4]+importance_matrix2[,2:4]+importance_matrix3[,2:4]+importance_matrix4[,2:4])/4

importance=cbind(importance_matrix1[,1],importance_matrix_mean)

write.csv(importance,'d_ets_imp_mean.csv')

ERROR: Error in Ops.data.frame(importance_matrix1[, 2:4] + importance_matrix2[, : ‘+’ only defined for equally-sized data frames