In [1]:
library("xgboost")
library("Matrix")
library('Ckmeans.1d.dp')
library('lightgbm')

载入程辑包：‘lightgbm’


The following object is masked from ‘package:xgboost’:

    slice

## Read data and process data labels

In [2]:
time_matrix <- matrix(0,ncol = 3, nrow =4)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [3]:
data=read.csv('Weekly_features_matrix.csv')
data=data[,2:dim(data)[2]]

In [4]:
dim(data)

[1] 359  23

In [5]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9939369 6.320946e-11  36.725978
2 1         0        1               0.9946734 6.529056e-11  34.006351
3 1         0        1               0.9991252 8.840224e-13  44.955510
4 1         0        1               0.4159002 3.556671e-07   5.567640
5 1         0        1               0.2103179 9.307235e-06 -12.975059
6 1         0        1               0.4338204 1.481087e-06   6.188379
  curvature   e_acf1    e_acf10   entropy    ⋯ diff1_acf10 diff2_acf1
1  23.3448845 0.9600554 6.8563381 0.12476627 ⋯ 0.06449135  -0.45466261
2  19.8560557 0.9377499 5.8511863 0.09129043 ⋯ 0.16413331  -0.36322842
3  11.0485829 0.6469218 2.6893773 0.02284238 ⋯ 2.84368811  -0.07717025
4 -13.7061999 0.8181018 2.1703527 0.72989048 ⋯ 0.09272949  -0.55370413
5  -1.0188984 0.6064015 0.7164726 0.87229229 ⋯ 0.10934385  -0.57273878
6   0.3520556 0.5692734 0.6017905 0.78743719 ⋯ 0.11337659  -0.56140364
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.2879798   2179   0.13012409 0.13012409  0.13012409   0
2 0.3123634   1710   0.11726213 0.11726213  0.11726213   0
3 2.4288344   2178   0.11671782 0.11671782  0.11671782   0
4 0.3546872   2597   0.09217238 0.09217238  0.09217238   0
5 0.3857296   1603   0.07539105 0.07539105  0.07539105   0
6 0.3372221   1602   0.13123631 0.13123631  0.13123631   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [6]:
dlist= load('Weekly_nnetar_datalist.RData')
datalist=eval(parse(text = dlist ))
res=datalist[[1]]
MASE=res[,,,6]
m=5

In [7]:
dim(MASE)

[1] 359   5   4

In [8]:
whichmin<-function(x){
    minx=min(x[x>0])
    loc=which(x==minx)[1]-1
    loc
}

meanunique=function(x)
    {
    mean(unique(x))
}

In [9]:
nanum=c()
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    a=apply(count,1,min)
    if(sum(is.na(a))>0)
        {
        nanum=append(nanum,i)
    }
    }

In [10]:
nanum

NULL

In [11]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [12]:
table(realbestmin)

realbestmin
  0   1   2   3   4
 61  49  65  62 122

In [13]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [14]:
realbestmean

      [,1]
 [1,] 3
 [2,] 3
 [3,] 3
 [4,] 1
 [5,] 0
 [6,] 2
 [7,] 0
 [8,] 0
 [9,] 1
[10,] 2
[11,] 3
[12,] 2
[13,] 3
[14,] 4
[15,] 3
[16,] 3
[17,] 2
[18,] 2
[19,] 0
[20,] 1
[21,] 1
[22,] 0
[23,] 3
[24,] 2
[25,] 1
[26,] 0
[27,] 0
[28,] 2
[29,] 0
[30,] 2
[31,] ⋮
[32,] 1
[33,] 1
[34,] 0
[35,] 2
[36,] 2
[37,] 1
[38,] 1
[39,] 1
[40,] 1
[41,] 0
[42,] 1
[43,] 1
[44,] 1
[45,] 3
[46,] 3
[47,] 2
[48,] 1
[49,] 1
[50,] 1
[51,] 3
[52,] 0
[53,] 0
[54,] 0
[55,] 4
[56,] 2
[57,] 0
[58,] 2
[59,] 0
[60,] 4
[61,] 2

In [15]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9939369 6.320946e-11  36.725978
2 1         0        1               0.9946734 6.529056e-11  34.006351
3 1         0        1               0.9991252 8.840224e-13  44.955510
4 1         0        1               0.4159002 3.556671e-07   5.567640
5 1         0        1               0.2103179 9.307235e-06 -12.975059
6 1         0        1               0.4338204 1.481087e-06   6.188379
  curvature   e_acf1    e_acf10   entropy    ⋯ diff1_acf10 diff2_acf1
1  23.3448845 0.9600554 6.8563381 0.12476627 ⋯ 0.06449135  -0.45466261
2  19.8560557 0.9377499 5.8511863 0.09129043 ⋯ 0.16413331  -0.36322842
3  11.0485829 0.6469218 2.6893773 0.02284238 ⋯ 2.84368811  -0.07717025
4 -13.7061999 0.8181018 2.1703527 0.72989048 ⋯ 0.09272949  -0.55370413
5  -1.0188984 0.6064015 0.7164726 0.87229229 ⋯ 0.10934385  -0.57273878
6   0.3520556 0.5692734 0.6017905 0.78743719 ⋯ 0.11337659  -0.56140364
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.2879798   2179   0.13012409 0.13012409  0.13012409   0
2 0.3123634   1710   0.11726213 0.11726213  0.11726213   0
3 2.4288344   2178   0.11671782 0.11671782  0.11671782   0
4 0.3546872   2597   0.09217238 0.09217238  0.09217238   0
5 0.3857296   1603   0.07539105 0.07539105  0.07539105   0
6 0.3372221   1602   0.13123631 0.13123631  0.13123631   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [16]:
set.seed(100)
index = sample(2,nrow(data),replace = TRUE,prob=c(0.7,0.3))

In [17]:
train_data=data[index==1,]
test_data=data[index==2,]
train_label_min=realbestmin[index==1,]
test_label_min=realbestmin[index==2,]
train_label_mean=realbestmean[index==1,]
test_label_mean=realbestmean[index==2,]

In [18]:
head(train_data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9939369 6.320946e-11  36.725978
2 1         0        1               0.9946734 6.529056e-11  34.006351
3 1         0        1               0.9991252 8.840224e-13  44.955510
4 1         0        1               0.4159002 3.556671e-07   5.567640
5 1         0        1               0.2103179 9.307235e-06 -12.975059
6 1         0        1               0.4338204 1.481087e-06   6.188379
  curvature   e_acf1    e_acf10   entropy    ⋯ diff1_acf10 diff2_acf1
1  23.3448845 0.9600554 6.8563381 0.12476627 ⋯ 0.06449135  -0.45466261
2  19.8560557 0.9377499 5.8511863 0.09129043 ⋯ 0.16413331  -0.36322842
3  11.0485829 0.6469218 2.6893773 0.02284238 ⋯ 2.84368811  -0.07717025
4 -13.7061999 0.8181018 2.1703527 0.72989048 ⋯ 0.09272949  -0.55370413
5  -1.0188984 0.6064015 0.7164726 0.87229229 ⋯ 0.10934385  -0.57273878
6   0.3520556 0.5692734 0.6017905 0.78743719 ⋯ 0.11337659  -0.56140364
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.2879798   2179   0.13012409 0.13012409  0.13012409   0
2 0.3123634   1710   0.11726213 0.11726213  0.11726213   0
3 2.4288344   2178   0.11671782 0.11671782  0.11671782   0
4 0.3546872   2597   0.09217238 0.09217238  0.09217238   0
5 0.3857296   1603   0.07539105 0.07539105  0.07539105   0
6 0.3372221   1602   0.13123631 0.13123631  0.13123631   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [19]:
end_time = Sys.time()

In [20]:
time_matrix[1,]=end_time-start_time

In [21]:
end_time-start_time

Time difference of 4.619964 secs

## Target the interval where the actual error is minimum

In [22]:
start_time = Sys.time()

In [23]:
dtrain_xg_min_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_min)) 
dtrain_xg_min_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)) )

In [24]:
dtrain_lg_min_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_min))
dtrain_lg_min_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)))

In [25]:
xgb_min_reg <- xgboost(data = dtrain_xg_min_reg, nround=100)

[1]	train-rmse:1.801338
[2]	train-rmse:1.376370
[3]	train-rmse:1.066040
[4]	train-rmse:0.852996
[5]	train-rmse:0.708030
[6]	train-rmse:0.583787
[7]	train-rmse:0.500062
[8]	train-rmse:0.432501
[9]	train-rmse:0.371072
[10]	train-rmse:0.345954
[11]	train-rmse:0.308510
[12]	train-rmse:0.293285
[13]	train-rmse:0.271292
[14]	train-rmse:0.247508
[15]	train-rmse:0.225288
[16]	train-rmse:0.207217
[17]	train-rmse:0.187841
[18]	train-rmse:0.171220
[19]	train-rmse:0.160158
[20]	train-rmse:0.152671
[21]	train-rmse:0.138036
[22]	train-rmse:0.132322
[23]	train-rmse:0.120514
[24]	train-rmse:0.108668
[25]	train-rmse:0.100724
[26]	train-rmse:0.094609
[27]	train-rmse:0.090038
[28]	train-rmse:0.081033
[29]	train-rmse:0.073721
[30]	train-rmse:0.063680
[31]	train-rmse:0.057833
[32]	train-rmse:0.053831
[33]	train-rmse:0.050820
[34]	train-rmse:0.046570
[35]	train-rmse:0.043913
[36]	train-rmse:0.041049
[37]	train-rmse:0.038882
[38]	train-rmse:0.038020
[39]	train-rmse:0.036469
[40]	train-rmse:0.035896
[41]	train-rmse:0.033168
[42]	train-rmse:0.031622
[43]	train-rmse:0.027718
[44]	train-rmse:0.024804
[45]	train-rmse:0.022558
[46]	train-rmse:0.021384
[47]	train-rmse:0.020011
[48]	train-rmse:0.018197
[49]	train-rmse:0.016529
[50]	train-rmse:0.016076
[51]	train-rmse:0.014774
[52]	train-rmse:0.014128
[53]	train-rmse:0.013718
[54]	train-rmse:0.013210
[55]	train-rmse:0.012365
[56]	train-rmse:0.011585
[57]	train-rmse:0.011173
[58]	train-rmse:0.009798
[59]	train-rmse:0.009330
[60]	train-rmse:0.008612
[61]	train-rmse:0.008254
[62]	train-rmse:0.008078
[63]	train-rmse:0.007516
[64]	train-rmse:0.007254
[65]	train-rmse:0.006837
[66]	train-rmse:0.006277
[67]	train-rmse:0.005589
[68]	train-rmse:0.005430
[69]	train-rmse:0.005257
[70]	train-rmse:0.005121
[71]	train-rmse:0.004975
[72]	train-rmse:0.004831
[73]	train-rmse:0.004509
[74]	train-rmse:0.004110
[75]	train-rmse:0.003867
[76]	train-rmse:0.003717
[77]	train-rmse:0.003324
[78]	train-rmse:0.003265
[79]	train-rmse:0.003113
[80]	train-rmse:0.002976
[81]	train-rmse:0.002921
[82]	train-rmse:0.002649
[83]	train-rmse:0.002451
[84]	train-rmse:0.002275
[85]	train-rmse:0.002180
[86]	train-rmse:0.002032
[87]	train-rmse:0.001930
[88]	train-rmse:0.001853
[89]	train-rmse:0.001690
[90]	train-rmse:0.001622
[91]	train-rmse:0.001577
[92]	train-rmse:0.001535
[93]	train-rmse:0.001475
[94]	train-rmse:0.001412
[95]	train-rmse:0.001244
[96]	train-rmse:0.001157
[97]	train-rmse:0.001093
[98]	train-rmse:0.001037
[99]	train-rmse:0.001018
[100]	train-rmse:0.000975

In [26]:
xgb_min_cl <- xgboost(data = dtrain_xg_min_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.272969
[2]	train-mlogloss:1.051435
[3]	train-mlogloss:0.873565
[4]	train-mlogloss:0.742060
[5]	train-mlogloss:0.631480
[6]	train-mlogloss:0.548022
[7]	train-mlogloss:0.475614
[8]	train-mlogloss:0.417913
[9]	train-mlogloss:0.372475
[10]	train-mlogloss:0.324058
[11]	train-mlogloss:0.289273
[12]	train-mlogloss:0.255491
[13]	train-mlogloss:0.233622
[14]	train-mlogloss:0.211260
[15]	train-mlogloss:0.192128
[16]	train-mlogloss:0.177318
[17]	train-mlogloss:0.162446
[18]	train-mlogloss:0.150395
[19]	train-mlogloss:0.138476
[20]	train-mlogloss:0.128387
[21]	train-mlogloss:0.118903
[22]	train-mlogloss:0.111482
[23]	train-mlogloss:0.104773
[24]	train-mlogloss:0.098776
[25]	train-mlogloss:0.093607
[26]	train-mlogloss:0.088866
[27]	train-mlogloss:0.084129
[28]	train-mlogloss:0.080140
[29]	train-mlogloss:0.076622
[30]	train-mlogloss:0.073266
[31]	train-mlogloss:0.070352
[32]	train-mlogloss:0.067665
[33]	train-mlogloss:0.065116
[34]	train-mlogloss:0.062860
[35]	train-mlogloss:0.060831
[36]	train-mlogloss:0.058731
[37]	train-mlogloss:0.057068
[38]	train-mlogloss:0.055485
[39]	train-mlogloss:0.054216
[40]	train-mlogloss:0.052783
[41]	train-mlogloss:0.051455
[42]	train-mlogloss:0.050146
[43]	train-mlogloss:0.048955
[44]	train-mlogloss:0.047911
[45]	train-mlogloss:0.046971
[46]	train-mlogloss:0.045956
[47]	train-mlogloss:0.045048
[48]	train-mlogloss:0.044221
[49]	train-mlogloss:0.043424
[50]	train-mlogloss:0.042619
[51]	train-mlogloss:0.041885
[52]	train-mlogloss:0.041119
[53]	train-mlogloss:0.040511
[54]	train-mlogloss:0.039903
[55]	train-mlogloss:0.039250
[56]	train-mlogloss:0.038592
[57]	train-mlogloss:0.038069
[58]	train-mlogloss:0.037482
[59]	train-mlogloss:0.036944
[60]	train-mlogloss:0.036509
[61]	train-mlogloss:0.036057
[62]	train-mlogloss:0.035631
[63]	train-mlogloss:0.035217
[64]	train-mlogloss:0.034811
[65]	train-mlogloss:0.034404
[66]	train-mlogloss:0.034015
[67]	train-mlogloss:0.033650
[68]	train-mlogloss:0.033268
[69]	train-mlogloss:0.032921
[70]	train-mlogloss:0.032591
[71]	train-mlogloss:0.032235
[72]	train-mlogloss:0.031907
[73]	train-mlogloss:0.031558
[74]	train-mlogloss:0.031267
[75]	train-mlogloss:0.031010
[76]	train-mlogloss:0.030759
[77]	train-mlogloss:0.030518
[78]	train-mlogloss:0.030322
[79]	train-mlogloss:0.030030
[80]	train-mlogloss:0.029779
[81]	train-mlogloss:0.029532
[82]	train-mlogloss:0.029290
[83]	train-mlogloss:0.029084
[84]	train-mlogloss:0.028871
[85]	train-mlogloss:0.028677
[86]	train-mlogloss:0.028431
[87]	train-mlogloss:0.028229
[88]	train-mlogloss:0.028025
[89]	train-mlogloss:0.027809
[90]	train-mlogloss:0.027613
[91]	train-mlogloss:0.027413
[92]	train-mlogloss:0.027212
[93]	train-mlogloss:0.027045
[94]	train-mlogloss:0.026859
[95]	train-mlogloss:0.026691
[96]	train-mlogloss:0.026519
[97]	train-mlogloss:0.026352
[98]	train-mlogloss:0.026226
[99]	train-mlogloss:0.026073
[100]	train-mlogloss:0.025913

In [27]:
lgb_min_reg <- lgb.train(data = dtrain_lg_min_reg, nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.037192 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1387
[LightGBM] [Info] Number of data points in the train set: 251, number of used features: 17
[LightGBM] [Info] Start training from score 2.398406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [28]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_min_cl <- lgb.train(data = dtrain_lg_min_cl,nrounds = 100,params=params)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.062783 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1387
[LightGBM] [Info] Number of data points in the train set: 251, number of used features: 17
[LightGBM] [Info] Start training from score -1.787783
[LightGBM] [Info] Start training from score -1.999092
[LightGBM] [Info] Start training from score -1.741263
[LightGBM] [Info] Start training from score -1.741263
[LightGBM] [Info] Start training from score -1.059545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [29]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

## Target the interval where the average error is minimum

In [30]:
start_time = Sys.time()

In [31]:
dtrain_xg_mean_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_mean)) 
dtrain_xg_mean_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)) )

In [32]:
dtrain_lg_mean_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_mean))
dtrain_lg_mean_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)))

In [33]:
xgb_mean_reg <- xgboost(data = dtrain_xg_mean_reg, nround=100)

[1]	train-rmse:1.681358
[2]	train-rmse:1.292995
[3]	train-rmse:1.023624
[4]	train-rmse:0.819568
[5]	train-rmse:0.669116
[6]	train-rmse:0.554530
[7]	train-rmse:0.487585
[8]	train-rmse:0.414383
[9]	train-rmse:0.351848
[10]	train-rmse:0.310430
[11]	train-rmse:0.270111
[12]	train-rmse:0.254027
[13]	train-rmse:0.237262
[14]	train-rmse:0.212992
[15]	train-rmse:0.198777
[16]	train-rmse:0.193888
[17]	train-rmse:0.180304
[18]	train-rmse:0.166247
[19]	train-rmse:0.153720
[20]	train-rmse:0.147507
[21]	train-rmse:0.138325
[22]	train-rmse:0.128320
[23]	train-rmse:0.126331
[24]	train-rmse:0.117958
[25]	train-rmse:0.106584
[26]	train-rmse:0.095923
[27]	train-rmse:0.090142
[28]	train-rmse:0.087553
[29]	train-rmse:0.079783
[30]	train-rmse:0.073474
[31]	train-rmse:0.067964
[32]	train-rmse:0.063773
[33]	train-rmse:0.056907
[34]	train-rmse:0.054316
[35]	train-rmse:0.052001
[36]	train-rmse:0.050183
[37]	train-rmse:0.047359
[38]	train-rmse:0.042987
[39]	train-rmse:0.039209
[40]	train-rmse:0.035872
[41]	train-rmse:0.032693
[42]	train-rmse:0.030813
[43]	train-rmse:0.026844
[44]	train-rmse:0.025473
[45]	train-rmse:0.022094
[46]	train-rmse:0.019476
[47]	train-rmse:0.018589
[48]	train-rmse:0.017381
[49]	train-rmse:0.016296
[50]	train-rmse:0.015105
[51]	train-rmse:0.013711
[52]	train-rmse:0.012719
[53]	train-rmse:0.012234
[54]	train-rmse:0.011321
[55]	train-rmse:0.010106
[56]	train-rmse:0.009492
[57]	train-rmse:0.008659
[58]	train-rmse:0.007887
[59]	train-rmse:0.007332
[60]	train-rmse:0.007007
[61]	train-rmse:0.006516
[62]	train-rmse:0.006007
[63]	train-rmse:0.005500
[64]	train-rmse:0.005195
[65]	train-rmse:0.004845
[66]	train-rmse:0.004391
[67]	train-rmse:0.004126
[68]	train-rmse:0.004028
[69]	train-rmse:0.003656
[70]	train-rmse:0.003302
[71]	train-rmse:0.003189
[72]	train-rmse:0.003035
[73]	train-rmse:0.002772
[74]	train-rmse:0.002600
[75]	train-rmse:0.002247
[76]	train-rmse:0.002022
[77]	train-rmse:0.001863
[78]	train-rmse:0.001734
[79]	train-rmse:0.001651
[80]	train-rmse:0.001508
[81]	train-rmse:0.001456
[82]	train-rmse:0.001322
[83]	train-rmse:0.001215
[84]	train-rmse:0.001154
[85]	train-rmse:0.001092
[86]	train-rmse:0.001029
[87]	train-rmse:0.000914
[88]	train-rmse:0.000881
[89]	train-rmse:0.000802
[90]	train-rmse:0.000802
[91]	train-rmse:0.000802
[92]	train-rmse:0.000802
[93]	train-rmse:0.000802
[94]	train-rmse:0.000802
[95]	train-rmse:0.000802
[96]	train-rmse:0.000802
[97]	train-rmse:0.000802
[98]	train-rmse:0.000802
[99]	train-rmse:0.000802
[100]	train-rmse:0.000802

In [34]:
xgb_mean_cl <- xgboost(data = dtrain_xg_mean_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.282108
[2]	train-mlogloss:1.040983
[3]	train-mlogloss:0.867327
[4]	train-mlogloss:0.728274
[5]	train-mlogloss:0.614076
[6]	train-mlogloss:0.531801
[7]	train-mlogloss:0.456971
[8]	train-mlogloss:0.406140
[9]	train-mlogloss:0.365428
[10]	train-mlogloss:0.322680
[11]	train-mlogloss:0.288885
[12]	train-mlogloss:0.256119
[13]	train-mlogloss:0.233574
[14]	train-mlogloss:0.210801
[15]	train-mlogloss:0.193264
[16]	train-mlogloss:0.179074
[17]	train-mlogloss:0.163474
[18]	train-mlogloss:0.152401
[19]	train-mlogloss:0.141476
[20]	train-mlogloss:0.132111
[21]	train-mlogloss:0.123562
[22]	train-mlogloss:0.116538
[23]	train-mlogloss:0.109200
[24]	train-mlogloss:0.103138
[25]	train-mlogloss:0.097464
[26]	train-mlogloss:0.091873
[27]	train-mlogloss:0.087326
[28]	train-mlogloss:0.083084
[29]	train-mlogloss:0.079143
[30]	train-mlogloss:0.076239
[31]	train-mlogloss:0.073048
[32]	train-mlogloss:0.070167
[33]	train-mlogloss:0.067342
[34]	train-mlogloss:0.064865
[35]	train-mlogloss:0.062978
[36]	train-mlogloss:0.060998
[37]	train-mlogloss:0.059159
[38]	train-mlogloss:0.057521
[39]	train-mlogloss:0.055674
[40]	train-mlogloss:0.054122
[41]	train-mlogloss:0.052819
[42]	train-mlogloss:0.051416
[43]	train-mlogloss:0.050188
[44]	train-mlogloss:0.049027
[45]	train-mlogloss:0.047859
[46]	train-mlogloss:0.046817
[47]	train-mlogloss:0.045885
[48]	train-mlogloss:0.044885
[49]	train-mlogloss:0.044026
[50]	train-mlogloss:0.043312
[51]	train-mlogloss:0.042517
[52]	train-mlogloss:0.041764
[53]	train-mlogloss:0.041077
[54]	train-mlogloss:0.040419
[55]	train-mlogloss:0.039731
[56]	train-mlogloss:0.039106
[57]	train-mlogloss:0.038424
[58]	train-mlogloss:0.037934
[59]	train-mlogloss:0.037326
[60]	train-mlogloss:0.036758
[61]	train-mlogloss:0.036336
[62]	train-mlogloss:0.035932
[63]	train-mlogloss:0.035562
[64]	train-mlogloss:0.035102
[65]	train-mlogloss:0.034721
[66]	train-mlogloss:0.034342
[67]	train-mlogloss:0.033939
[68]	train-mlogloss:0.033586
[69]	train-mlogloss:0.033233
[70]	train-mlogloss:0.032866
[71]	train-mlogloss:0.032555
[72]	train-mlogloss:0.032193
[73]	train-mlogloss:0.031909
[74]	train-mlogloss:0.031604
[75]	train-mlogloss:0.031323
[76]	train-mlogloss:0.031027
[77]	train-mlogloss:0.030789
[78]	train-mlogloss:0.030519
[79]	train-mlogloss:0.030277
[80]	train-mlogloss:0.030025
[81]	train-mlogloss:0.029763
[82]	train-mlogloss:0.029497
[83]	train-mlogloss:0.029228
[84]	train-mlogloss:0.028999
[85]	train-mlogloss:0.028806
[86]	train-mlogloss:0.028609
[87]	train-mlogloss:0.028393
[88]	train-mlogloss:0.028175
[89]	train-mlogloss:0.027992
[90]	train-mlogloss:0.027807
[91]	train-mlogloss:0.027625
[92]	train-mlogloss:0.027427
[93]	train-mlogloss:0.027220
[94]	train-mlogloss:0.027058
[95]	train-mlogloss:0.026912
[96]	train-mlogloss:0.026754
[97]	train-mlogloss:0.026590
[98]	train-mlogloss:0.026408
[99]	train-mlogloss:0.026234
[100]	train-mlogloss:0.026087

In [35]:
lgb_mean_reg <- lgb.train(data = dtrain_lg_mean_reg,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012293 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1387
[LightGBM] [Info] Number of data points in the train set: 251, number of used features: 17
[LightGBM] [Info] Start training from score 2.167331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [36]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_mean_cl <- lgb.train(data = dtrain_lg_mean_cl,params=params,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.026316 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1387
[LightGBM] [Info] Number of data points in the train set: 251, number of used features: 17
[LightGBM] [Info] Start training from score -1.675305
[LightGBM] [Info] Start training from score -1.654252
[LightGBM] [Info] Start training from score -1.836573
[LightGBM] [Info] Start training from score -1.654252
[LightGBM] [Info] Start training from score -1.305945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [37]:
end_time = Sys.time()
time_matrix[3,]=end_time-start_time

In [38]:
end_time-start_time

Time difference of 2.867405 mins

## predict

In [39]:
start_time = Sys.time()

In [40]:
alldatalgb <- lgb.Dataset(data = as.matrix(data))
alldataxgb <- xgb.DMatrix(data = as.matrix(data))

In [41]:
xgbregmin=predict(xgb_min_reg,alldataxgb)
xgbclsmin=predict(xgb_min_cl,alldataxgb)
lgbregmin=predict(lgb_min_reg,as.matrix(data))
lgbclsmin=predict(lgb_min_cl,as.matrix(data))

In [42]:
xgbregmin

  [1]  3.999884e+00  3.002302e+00  3.000010e+00  1.001373e+00  9.992362e-01
  [6]  9.997280e-01  1.073479e+00  5.426715e-04  1.000169e+00  1.999688e+00
 [11]  2.999311e+00  2.517390e+00  3.999368e+00  3.998664e+00  3.960714e+00
 [16]  4.000673e+00  1.999841e+00  1.999704e+00  3.159106e-04  3.001650e+00
 [21]  1.999152e+00  1.260651e+00  2.998791e+00  2.020399e+00  9.991089e-01
 [26]  1.002946e-03  6.641597e-01  1.503920e+00  5.597891e-04  1.999310e+00
 [31]  1.000608e+00  9.028302e-01  2.997860e+00  2.530322e+00  1.566401e-03
 [36]  3.256366e+00  3.998935e+00  3.001152e+00  2.985602e+00  3.000610e+00
 [41]  1.000565e+00  1.807689e+00  1.749685e+00  3.051802e+00  3.998056e+00
 [46]  2.001420e+00  3.116096e+00  3.093980e+00  3.999841e+00  3.999841e+00
 [51]  1.000260e+00  3.999137e+00  3.001034e+00  2.999346e+00  2.999120e+00
 [56]  2.271630e-04  3.999693e+00  2.000273e+00  3.999843e+00  3.999531e+00
 [61]  3.998873e+00  1.000179e+00  3.613404e+00  3.999999e+00  3.999651e+00
 [66]  3.000392e+00  3.998976e+00  1.999279e+00  2.000552e+00  3.000116e+00
 [71]  3.999208e+00  4.001198e+00  3.999662e+00  2.452519e+00  3.999565e+00
 [76]  1.315174e-03  3.160090e+00  2.785669e+00  3.447983e+00  3.999567e+00
 [81]  4.000319e+00  2.999832e+00  2.435906e+00  2.650826e+00  4.000534e+00
 [86]  3.999548e+00  3.866367e+00  3.999143e+00  3.206093e-04  2.478753e+00
 [91]  3.414821e+00  3.999604e+00  7.123504e-04 -1.281552e-04  4.220302e-01
 [96]  3.999800e+00  4.490076e-04  4.378999e-04  3.998672e+00  2.917850e+00
[101]  4.000861e+00  3.001335e+00  3.999963e+00  3.997794e+00  2.001517e+00
[106]  4.000124e+00  3.545399e+00  3.859775e+00  4.000145e+00  3.000949e+00
[111]  3.868610e+00  3.286178e+00  1.537099e-03  2.003050e+00  3.618569e+00
[116]  3.999650e+00  3.299544e+00  8.431365e-01 -1.185908e-04  5.751455e-01
[121]  4.000149e+00  2.999838e+00  1.998894e+00  2.999897e+00  2.999706e+00
[126]  3.999782e+00  3.249804e+00  3.650477e+00  1.001896e+00  3.999191e+00
[131]  3.997447e+00  3.374211e+00  3.942679e+00  4.000030e+00  3.999823e+00
[136]  3.999703e+00  2.002818e+00  9.987466e-01  3.998710e+00  3.998527e+00
[141]  4.000298e+00  3.999905e+00  1.999364e+00  3.031379e+00  2.999452e+00
[146]  3.772595e+00  2.363923e+00  2.000275e+00  1.001592e+00  2.999773e+00
[151]  4.000282e+00  3.806103e+00  3.998731e+00  2.999701e+00  3.000551e+00
[156]  3.589944e+00  1.886183e+00  3.220935e+00  4.000686e+00  3.999140e+00
[161]  3.138090e+00  3.999124e+00  3.999204e+00  3.999353e+00  1.530132e-04
[166]  1.000064e+00 -9.964823e-05  3.747327e+00  2.672758e+00  3.587151e+00
[171]  1.821487e-03  3.999884e+00  2.765324e-04  2.334591e+00  3.460278e+00
[176]  3.999629e+00  1.280204e+00  3.999065e+00  3.999196e+00  1.999456e+00
[181]  2.000885e+00  3.332506e+00  2.481558e+00  3.999366e+00  3.999704e+00
[186]  2.999200e+00  4.000015e+00  3.215880e-05  2.000763e+00  3.133166e+00
[191]  2.576529e+00  3.998250e+00  2.000169e+00  3.288097e+00  2.000246e+00
[196]  4.000741e+00  5.629336e-04  3.998044e+00  5.169321e-04  2.756405e+00
[201]  2.999952e+00  1.464033e+00  3.735987e+00  2.712509e+00  2.002761e+00
[206]  2.725779e+00  2.861295e+00  3.999291e+00  4.000415e+00  2.000886e+00
[211]  4.000569e+00  1.321276e+00  9.997835e-01  1.999467e+00  1.452412e-03
[216]  3.999620e+00  1.641809e+00  8.370652e-01  3.999317e+00  3.999959e+00
[221]  1.999911e+00  3.999387e+00  3.999000e+00  2.834448e+00  1.313034e-03
[226]  2.000297e+00  9.980147e-01  1.999555e+00  8.429735e-05  2.999026e+00
[231]  3.998768e+00  1.999557e+00  1.918396e+00  9.998425e-01  3.000297e+00
[236]  8.705306e-04  2.999925e+00  2.388122e+00  3.042769e+00  3.061625e+00
[241]  4.967215e-04  2.342023e+00  1.020247e-03  1.948368e+00  2.370769e-03
[246]  1.819116e+00  3.000083e+00  4.000438e+00  3.999792e+00  4.000180e+00
[251]  4.000081e+00  3.177875e+00  3.999374e+00  3.999908e+00  1.788442e+00
[256]  3.722167e+00  3.999227e+00  3.000314e+00  2.001224e+00  2.732204e+00
[261]  2.001777e+00  3.396245e+00  1.645945e-03  2.956621e+00  9.932734e-01
[266]  1.395179e+00  2.997580e+00  3.000242e+00  2.225456e+00  2.835934e+00
[271]  3.001081e+00  2.032398e+00  4.000134e+00  4.879227e-05  2.000080e+00
[276]  3.162466e+00  2.000394e+00  7.852226e-04  2.000416e+00  3.001904e+00
[281]  9.987047e-01  8.225313e-04  2.999413e+00  9.996761e-01  3.999842e+00
[286]  2.999541e+00  2.310311e+00  3.038159e+00  4.000494e+00  3.997250e+00
[291]  4.000820e+00  3.002619e+00  1.999719e+00  3.997116e+00  9.980460e-01
[296]  9.998294e-01  1.000396e+00  6.095597e-01  1.000353e+00  1.999905e+00
[301]  1.097500e-02  3.000139e+00  1.163619e+00  1.999088e+00  2.999205e+00
[306]  2.760633e+00  1.000231e+00  2.000213e+00  9.604373e-04  2.782749e+00
[311]  1.000532e+00  5.278645e-01  1.234307e-03  2.999954e+00  1.267990e-03
[316]  2.997834e+00 -4.797692e-04  4.660015e-01  9.995432e-01  2.801696e+00
[321]  2.000273e+00  1.000095e+00  1.000268e+00  3.056097e+00  2.999068e+00
[326]  1.296131e+00  1.323840e-01  8.930669e-04  9.997145e-01  2.486405e+00
[331]  1.000219e+00  1.000069e+00  1.999997e+00  1.002355e+00  4.129838e-04
[336]  1.000040e+00  9.995107e-01  2.527255e-03  1.160453e+00  1.999472e+00
[341]  2.132261e+00  1.000232e+00  3.000321e+00  1.999974e+00  3.999725e+00
[346]  1.999968e+00  1.999619e+00  4.338645e-01  2.999938e+00  2.388805e+00
[351] -3.563960e-05 -5.157577e-06  3.999570e+00  1.999875e+00  8.754741e-04
[356]  1.999948e+00  6.506137e-01  3.997548e+00  3.042847e+00

In [43]:
xgbclsmin

  [1] 4 3 3 1 1 1 2 0 1 2 3 1 4 4 4 4 2 2 0 3 2 0 3 1 1 0 2 2 0 2 1 1 3 3 0 4 4
 [38] 3 3 3 1 1 1 3 4 2 4 4 4 4 1 4 3 3 3 0 4 2 4 4 4 1 4 4 4 3 4 2 2 3 4 4 4 2
 [75] 4 0 2 4 4 4 4 3 4 4 4 4 4 4 0 4 4 4 0 0 0 4 0 0 4 3 4 3 4 4 2 4 2 4 4 3 4
[112] 4 0 2 4 4 4 0 0 0 4 3 2 3 3 4 4 4 1 4 4 4 4 4 4 4 2 1 4 4 4 4 2 4 3 4 2 2
[149] 1 3 4 4 4 3 3 4 2 4 4 4 2 4 4 4 0 1 0 4 4 4 0 4 0 4 4 4 2 4 4 2 2 4 2 4 4
[186] 3 4 0 2 4 3 4 2 4 2 4 0 4 0 1 3 4 4 3 2 3 2 4 4 2 4 2 1 2 0 4 2 2 4 4 2 4
[223] 4 3 0 2 1 2 0 3 4 2 3 1 3 0 3 0 3 4 0 3 0 3 0 4 3 4 4 4 4 3 4 4 3 4 4 3 2
[260] 0 2 4 0 3 0 3 3 3 3 3 3 4 4 0 2 3 2 0 2 3 1 0 3 1 4 3 4 4 4 4 4 3 2 4 1 1
[297] 1 1 1 2 0 3 4 2 3 1 1 2 0 4 1 1 0 3 0 3 0 0 1 4 2 1 1 2 3 1 0 0 1 1 1 1 2
[334] 1 0 1 1 0 2 2 1 1 3 2 4 2 2 0 3 1 0 0 4 2 0 2 1 4 4

In [44]:
lgbregmin

  [1]  3.872904176  3.390902168  3.313215482  1.236160844  0.772607370
  [6]  1.025834256  1.439350197  0.394724674  1.292227078  1.825897359
 [11]  2.579099042  2.059289784  3.584239271  3.770357989  3.857470652
 [16]  4.071361016  2.348137595  2.111051007  0.256175078  2.971431289
 [21]  1.321833967  1.708147201  2.991519847  1.743129429  0.898828898
 [26] -0.005014704  1.641502403  1.128513866  0.834463855  1.826415869
 [31]  0.997276414  1.282563113  2.686383890  2.985649673  1.057262672
 [36]  2.621405742  3.727586590  3.280297496  3.118606510  3.275203385
 [41]  1.736746997  2.432835227  1.907808291  3.082960700  3.452236015
 [46]  2.661692349  2.957912717  2.770509554  3.660189875  3.689832220
 [51]  1.561018682  3.661225387  3.075190954  2.406753755  3.241238116
 [56]  0.596749613  3.264928588  2.706710525  3.252124762  2.853130948
 [61]  3.650779433  1.263799469  3.469122191  3.872016903  4.200759115
 [66]  3.111279893  3.730039182  1.863383231  2.247749438  3.109922020
 [71]  3.693397036  3.842253619  3.800187953  2.727358712  3.675031196
 [76]  0.521591839  2.817603980  3.245570674  3.746668304  3.832939068
 [81]  4.033212858  2.921201807  3.346419898  3.584892890  3.923457460
 [86]  4.036515723  3.175506270  3.682378211  0.106244693  2.551533477
 [91]  3.489281777  4.020467004  1.084046090 -0.263001939  0.178051597
 [96]  4.122801339  0.383503480  0.468606691  3.792975214  3.002514152
[101]  4.061923901  3.374201651  3.612466763  3.055271379  3.202205726
[106]  3.344411803  3.225336277  3.783605396  3.949439289  3.468935143
[111]  3.201152516  3.424378282  0.524625135  2.596636249  3.697225619
[116]  3.877339066  3.862888515  1.954634920  0.239426808  0.117861028
[121]  4.142408710  2.476846287  1.276425909  3.439610528  2.989014605
[126]  4.043763621  3.914517758  3.186366621  2.118049051  3.650602032
[131]  3.366378059  3.306159487  3.857669186  3.959724574  3.966727584
[136]  3.363859757  2.823609147  0.482965364  3.245016391  3.341303826
[141]  4.056143365  4.103692398  2.230355626  3.827573721  2.635320242
[146]  3.894803216  1.363010210  1.572212193  1.437050144  3.394524910
[151]  3.766633152  3.836322385  3.723180598  3.090093319  3.219232444
[156]  3.195528912  1.896189316  3.133648403  3.804333778  3.799571845
[161]  2.900414060  3.496809041  3.831275217  3.727545491 -0.065868455
[166]  1.087738658  0.665583643  4.257393644  3.443550675  3.859952756
[171]  0.986764614  3.923724534 -0.113303679  2.701053157  3.793546057
[176]  4.388143585  1.397300441  3.822990000  3.508891318  1.844527082
[181]  2.504395525  3.266338318  2.970881325  3.537228852  3.627136549
[186]  2.754488605  3.065065532  0.502107714  2.520669776  2.794150251
[191]  3.002110719  3.261393939  2.077252859  2.976063431  2.011934804
[196]  3.973002108  0.466642362  3.292058155  0.551952618  2.142622849
[201]  2.943305728  2.264247029  4.139459944  2.887508723  2.205636846
[206]  1.913073067  1.875266393  3.206722397  3.960270932  2.209901715
[211]  3.843251880  2.089948674  1.067339784  2.276555711  1.213502261
[216]  3.317191068  0.791976166  1.115455184  3.169309357  3.008484722
[221]  2.782178024  3.602929706  3.656833872  2.827492472  0.688182819
[226]  1.966351810  0.828073050  1.754519670  0.238309395  2.296056330
[231]  2.837718783  2.178562890  2.685433882  1.002457696  2.505525706
[236]  0.763745561  2.400077374  1.734028199  2.623689466  2.481428369
[241]  0.457067684  2.267609421  0.637528463  2.640875588  0.916377223
[246]  2.055408687  2.598683503  4.194507230  4.058277765  4.079596422
[251]  3.455911162  3.210441614  3.674022319  3.854422849  2.326334379
[256]  3.575732964  3.620531000  2.923530289  2.201255734  2.290740780
[261]  2.190237630  3.196360484  0.691149488  2.408192727  1.417119711
[266]  1.827143396  2.524000953  2.580350847  2.487996710  3.272133269
[271]  3.064199279  2.288819025  3.842444546  0.266529895  2.560892835
[276]  2.750331847  2.267584382  0.856166196  2.599551112  3.375202116
[281]  0.895546681  1.294809840  2.457693536  1.512740666  3.755940070
[286]  3.042022926  2.800963293  3.152748679  3.917146536  3.551290678
[291]  3.560239870  3.415853557  1.702753507  3.195279509  1.009134640
[296]  1.452932612  1.413884116  0.877629950  1.409729290  1.878700644
[301]  0.676268052  3.027459461  2.260735043  1.558115408  2.357538054
[306]  3.070891282  1.088162930  2.181528566  0.387484930  1.596974274
[311]  1.425268454  1.321532773  0.310568734  2.240242234  0.839430909
[316]  2.342540458  0.058289259  0.353878270  1.184589878  2.189358579
[321]  1.820808924  1.453889310  1.212959353  3.470170490  2.011488764
[326]  1.642028578  1.045747705  0.766794138  1.087208465  2.553553243
[331]  1.113020587  1.067288626  2.576692175  1.365192146  0.783977545
[336]  0.659137145  0.797834832  0.813956394  2.009913514  1.379754533
[341]  2.426661690  1.039396698  3.002126949  1.920825149  2.776600656
[346]  1.888456681  1.668210793  0.591731322  2.778335587  2.319580396
[351]  0.392871044  0.375097537  3.375038514  2.092696546  0.352315369
[356]  1.692350053  0.457043646  3.524368033  1.786470181

In [45]:
lgbclsmin

      [,1]         [,2]         [,3]         [,4]         [,5]
 [1,] 0.0003561526 9.739440e-04 0.002192056  0.0076677582 0.9888100889
 [2,] 0.0004301271 1.135002e-03 0.001132329  0.9457427332 0.0515598091
 [3,] 0.0007444907 3.715920e-04 0.005577632  0.9335582313 0.0597480543
 [4,] 0.0047221160 9.788333e-01 0.006302990  0.0091273127 0.0010142664
 [5,] 0.0255916511 9.681919e-01 0.004052976  0.0015823276 0.0005811834
 [6,] 0.0082019045 9.874547e-01 0.002325651  0.0008590567 0.0011586551
 [7,] 0.1978381055 4.847555e-01 0.300471647  0.0125005839 0.0044341313
 [8,] 0.9734435009 1.721771e-02 0.007479343  0.0015310970 0.0003283472
 [9,] 0.0203194681 9.711633e-01 0.003193613  0.0037617021 0.0015618929
[10,] 0.0002362358 7.601886e-04 0.987757335  0.0072324093 0.0040138309
[11,] 0.0052295798 1.525238e-02 0.009385655  0.9626652607 0.0074671203
[12,] 0.2008381787 4.949398e-01 0.027576293  0.2415850286 0.0350607223
[13,] 0.0031305542 3.708947e-04 0.006681315  0.0043012184 0.9855160183
[14,] 0.0005735439 1.634092e-04 0.004104418  0.0148990849 0.9802595443
[15,] 0.0007730363 6.378918e-03 0.082788774  0.0482777514 0.8617815199
[16,] 0.0002701819 1.723540e-05 0.010892453  0.0104181569 0.9784019728
[17,] 0.0000587798 6.481269e-05 0.978120353  0.0009711365 0.0207849176
[18,] 0.0011988456 3.767727e-04 0.985327003  0.0042878646 0.0088095146
[19,] 0.9846768009 5.812817e-03 0.003660353  0.0008810642 0.0049689657
[20,] 0.0017826703 1.213869e-04 0.007714710  0.9879787391 0.0024024933
[21,] 0.0197770959 7.585696e-03 0.967650418  0.0043587176 0.0006280726
[22,] 0.0674094317 3.650565e-01 0.002267109  0.5504029559 0.0148640409
[23,] 0.0025296927 1.888779e-04 0.010041268  0.9862187957 0.0010213657
[24,] 0.0182965655 5.434913e-01 0.045909243  0.3858116715 0.0064911972
[25,] 0.0277398894 9.685087e-01 0.000908489  0.0024063903 0.0004365198
[26,] 0.9642744749 2.154780e-02 0.009965495  0.0033433505 0.0008688776
[27,] 0.0023259783 8.758325e-01 0.087258185  0.0312939446 0.0032894104
[28,] 0.0022712011 2.121809e-01 0.772896212  0.0119321176 0.0007195831
[29,] 0.9727435938 1.300039e-02 0.004036482  0.0047991821 0.0054203556
[30,] 0.0123611043 2.425473e-02 0.950691853  0.0072459611 0.0054463550
[31,] ⋮            ⋮            ⋮            ⋮            ⋮
[32,] 0.0006411284 0.7779219376 0.0181273153 0.1856184633 0.0176911553
[33,] 0.0019429432 0.9709884438 0.0191433394 0.0046841567 0.0032411169
[34,] 0.0022779309 0.9805257680 0.0153374591 0.0016052231 0.0002536188
[35,] 0.0016187275 0.0158225707 0.9457287625 0.0252467517 0.0115831876
[36,] 0.0088306265 0.9447771116 0.0161294983 0.0259923034 0.0042704602
[37,] 0.9522482386 0.0280972682 0.0113230251 0.0036551309 0.0046763372
[38,] 0.0022107374 0.9836154759 0.0118422087 0.0014121685 0.0009194096
[39,] 0.0150197228 0.9752822841 0.0020354920 0.0067123476 0.0009501535
[40,] 0.9466750724 0.0257097256 0.0019939366 0.0231636352 0.0024576302
[41,] 0.0060451983 0.1567316248 0.8046686155 0.0070289782 0.0255255831
[42,] 0.0086471731 0.0040832523 0.9865069646 0.0001487519 0.0006138581
[43,] 0.0104676928 0.8203580794 0.0096350158 0.1528691263 0.0066700857
[44,] 0.0152041833 0.9460510344 0.0123037688 0.0181788315 0.0082621821
[45,] 0.0006008942 0.0219995631 0.0204541829 0.9517013773 0.0052439824
[46,] 0.0001213241 0.0199950834 0.9785552107 0.0003784422 0.0009499396
[47,] 0.0290140483 0.0134049127 0.0179861542 0.0104671234 0.9291277613
[48,] 0.0032786610 0.0227223278 0.9409067360 0.0142599956 0.0188322796
[49,] 0.0028835888 0.0190386651 0.9664347056 0.0100367829 0.0016062576
[50,] 0.3410890664 0.5867180503 0.0031796010 0.0556059537 0.0134073285
[51,] 0.0055692598 0.0143030086 0.0011037075 0.9667161509 0.0123078732
[52,] 0.0267574016 0.4619905375 0.0266392972 0.4719696734 0.0126430902
[53,] 0.9783299171 0.0053578768 0.0071702795 0.0056714329 0.0034704936
[54,] 0.9841198174 0.0009033713 0.0006384143 0.0089288584 0.0054095386
[55,] 0.0185709177 0.0071182392 0.0212725528 0.0273343332 0.9257039571
[56,] 0.0020054318 0.0097296176 0.9665216741 0.0045282338 0.0172150426
[57,] 0.9763905023 0.0037823678 0.0038794474 0.0031208999 0.0128267826
[58,] 0.0152397169 0.0068181359 0.9496821691 0.0041821761 0.0240778020
[59,] 0.0423062339 0.6721310634 0.0215146721 0.2502031447 0.0138448858
[60,] 0.0014554083 0.0162283236 0.0138331974 0.0275538364 0.9409292343
[61,] 0.0266257637 0.2122168041 0.0806647807 0.0486039098 0.6318887417

In [46]:
datalength=dim(data)[1]
lgbclsm=matrix(lgbclsmin,m,datalength)
lgbclsminr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsminr[i,]=which.max(lgbclsm[,i])
}
lgbclsminr=lgbclsminr-1

In [47]:
lgbclsminr

      [,1]
 [1,] 4
 [2,] 2
 [3,] 1
 [4,] 3
 [5,] 1
 [6,] 3
 [7,] 4
 [8,] 0
 [9,] 4
[10,] 2
[11,] 3
[12,] 0
[13,] 2
[14,] 2
[15,] 3
[16,] 0
[17,] 2
[18,] 3
[19,] 3
[20,] 2
[21,] 3
[22,] 0
[23,] 2
[24,] 3
[25,] 1
[26,] 3
[27,] 0
[28,] 2
[29,] 2
[30,] 1
[31,] ⋮
[32,] 1
[33,] 1
[34,] 2
[35,] 3
[36,] 1
[37,] 4
[38,] 4
[39,] 3
[40,] 0
[41,] 2
[42,] 2
[43,] 4
[44,] 3
[45,] 1
[46,] 3
[47,] 0
[48,] 0
[49,] 0
[50,] 3
[51,] 1
[52,] 0
[53,] 0
[54,] 0
[55,] 2
[56,] 0
[57,] 4
[58,] 2
[59,] 0
[60,] 3
[61,] 3

In [48]:
xgbregmean=predict(xgb_mean_reg,alldataxgb)
xgbclsmean=predict(xgb_mean_cl,alldataxgb)
lgbregmean=predict(lgb_mean_reg,as.matrix(data))
lgbclsmean=predict(lgb_mean_cl,as.matrix(data))

In [49]:
lgbclsm=matrix(lgbclsmean,m,datalength)
lgbclsmeanr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsmeanr[i,]=which.max(lgbclsm[,i])
}
lgbclsmeanr=lgbclsmeanr-1

In [50]:
preallmin=cbind(xgbclsmin,xgbregmin)
preallmin=cbind(preallmin,lgbclsminr)
preallmin=cbind(preallmin,lgbregmin)

In [51]:
colnames(preallmin)=c('xgbclsmin','xgbregmin','lgbclsmin','lgbregmin')
head(preallmin)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 4         3.9998839 4         3.8729042
[2,] 3         3.0023022 2         3.3909022
[3,] 3         3.0000095 1         3.3132155
[4,] 1         1.0013728 3         1.2361608
[5,] 1         0.9992362 1         0.7726074
[6,] 1         0.9997280 3         1.0258343

In [52]:
preallmean=cbind(xgbclsmean,xgbregmean)
preallmean=cbind(preallmean,lgbclsmeanr)
preallmean=cbind(preallmean,lgbregmean)

In [53]:
head(preallmean)

     xgbclsmean xgbregmean      lgbregmean
[1,] 3           3.0005400181 4  2.9799629
[2,] 3           2.9992690086 2  2.7298096
[3,] 3           2.9999363422 1  3.2475792
[4,] 1           0.9997013211 3  0.9941867
[5,] 0          -0.0006854727 1 -0.0187494
[6,] 2           1.9995700121 3  1.7547153

In [54]:
colnames(preallmean)=c('xgbclsmean','xgbregmean','lgbclsmean','lgbregmean')
head(preallmean)

     xgbclsmean xgbregmean    lgbclsmean lgbregmean
[1,] 3           3.0005400181 4           2.9799629
[2,] 3           2.9992690086 2           2.7298096
[3,] 3           2.9999363422 1           3.2475792
[4,] 1           0.9997013211 3           0.9941867
[5,] 0          -0.0006854727 1          -0.0187494
[6,] 2           1.9995700121 3           1.7547153

In [55]:
end_time = Sys.time()
time_matrix[4,]=end_time-start_time

In [56]:
result_list=list(preallmin,preallmean,time_matrix)

In [57]:
save(result_list, file = "Weekly_nnetar_opt_pre_result.RData")

In [58]:
time_matrix

     user_time system_time elapsed_time
[1,] 4.6199644 4.6199644   4.6199644
[2,] 3.5019691 3.5019691   3.5019691
[3,] 2.8674052 2.8674052   2.8674052
[4,] 0.8890216 0.8890216   0.8890216

In [61]:
sum(xgbclsmean[index==2]==realbestmean[index==2])/length(realbestmean)

[1] 0.1197772

In [62]:
xgbclsmean[index==2]

  [1] 1 0 3 0 1 1 0 1 1 4 4 1 1 3 4 4 4 2 2 2 3 0 4 4 2 1 0 1 2 4 4 4 4 4 4 0 4
 [38] 4 2 4 4 4 3 4 3 2 4 2 4 3 4 0 4 1 0 2 1 4 4 3 2 3 3 0 2 2 0 0 2 3 3 4 3 3
 [75] 1 1 3 3 3 0 2 0 0 0 0 4 4 2 4 4 1 1 1 1 0 1 1 2 2 1 1 1 1 1 1 2 1 1

In [63]:
realbestmean[index==2]

  [1] 0 2 3 0 2 0 2 0 1 4 3 1 1 3 4 0 3 3 4 2 2 4 4 0 4 4 0 3 4 4 0 2 4 4 0 0 3
 [38] 4 4 4 2 4 2 2 2 3 4 4 0 3 3 1 4 1 0 2 3 1 3 2 3 1 1 0 2 1 0 0 3 3 2 0 0 1
 [75] 0 0 3 2 3 0 1 0 0 4 0 0 0 0 2 3 0 1 2 2 0 1 3 1 1 1 1 1 0 1 1 0 0 2

In [64]:
# 计算对误差
mean(abs(realbestmean[index==2] - xgbclsmean[index==2]))

[1] 1.111111